<?php

/**
 * This is the model base class for the table "{{item}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Item".
 *
 * Columns in table "{{item}}" available as properties of the model,
 * followed by relations of table "{{item}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $title
 * @property string $item_code
 * @property string $description
 * @property string $image_file
 * @property integer $item_type
 * @property integer $status
 * @property integer $type_id
 * @property integer $is_tax
 * @property integer $is_discount
 * @property integer $category_id
 * @property integer $sub_company_id
 * @property integer $company_id
 * @property string $create_time
 * @property integer $create_user_id
 * @property integer $updated_by
 *
 * @property ItemCategory $category
 * @property ItemCompany $company
 * @property User $createUser
 * @property ItemCompanyCategory $subCompany
 * @property User $updatedBy
 * @property ItemDetail[] $itemDetails
 */
abstract class BaseItem extends GxActiveRecord {
	public $start_date;
	public $end_date;
	public $qty;
	public $to_user_id;
	public $vendor_id;
	public $company_bar_code;
	public $bar_code;
	public $tax_id;
	public $name;
	public $outlet_id;
	public $remaining_quan ;
	const STATUS_ACTIVE = 0;
	const STATUS_INACTIVE = 1;
	public static function getStatusOptions($id = null) {
		$list = array (
				"Active",
				"Inactive" 
		);
		if ($id == null)
			return $list;
		if (is_numeric ( $id ))
			return $list [$id];
		return $id;
	}
	public static function getTypeOptions($id = null) {
		$list = array (
				"Finished",
				"Kot",
				"combo",
				'Semi finished',
				'Material' 
		);
		if ($id == null)
			return $list;
		if (is_numeric ( $id ))
			return $list [$id];
		return $id;
	}
	public static function getTypeKeyOptions($value) {
		$list = array (
				"Finished",
				"Kot",
				"combo",
				'Semi finished',
				'Material' 
		);
		
		foreach ( $list as $key => $val ) {
			if ($val == $value) {
				return $key;
			}
		}
		
		return '0';
	}
	public static function getStatusKeyOptions($value) {
		$list = array (
				"Active",
				"Inactive" 
		);
		
		foreach ( $list as $key => $val ) {
			if ($val == $value) {
				return $key;
			}
		}
		
		return '0';
	}
	public static function getStockOptions($id = null) {
		$list = array (
				"Stockable",
				"Non Stockable" 
		);
		if ($id == null)
			return $list;
		if (is_numeric ( $id ))
			return $list [$id];
		return $id;
	}
	public static function getMovementTypeOptions($id = null) {
		$list = array (
				"Both",
				"Sale Only",
				"Purchase Only" 
		)
		;
		if ($id == null)
			return $list;
		if (is_numeric ( $id ))
			return $list [$id];
		return $id;
	}
	public static function getMeasurementTypeOptions($id = null) {
		$list = array (
				"PCS-PIECES",
				"Box",
				"Case",
				"KGS-KILOGRAMS",
				"ML",
				"NOS",
				"PCS",
				"PETI",
				"TIN" 
		)
		;
		if ($id == null)
			return $list;
		if (is_numeric ( $id ))
			return $list [$id];
		return $id;
	}
	public function beforeValidate() {
		if ($this->isNewRecord) {
			if (! isset ( $this->create_time ))
				$this->create_time = new CDbExpression ( 'NOW()' );
			if (! isset ( $this->create_user_id ))
				$this->create_user_id = Yii::app ()->user->id;
		} else {
			if (! isset ( $this->update_time ))
				$this->update_time = new CDbExpression ( 'NOW()' );
		}
		return parent::beforeValidate ();
	}
	public static function model($className = __CLASS__) {
		return parent::model ( $className );
	}
	public function tableName() {
		return '{{item}}';
	}
	public static function label($n = 1) {
		return Yii::t ( 'app', 'Item|Items', $n );
	}
	public static function representingColumn() {
		return 'title';
	}
	public function rules() {
		return array (
				array (
						'short_name,title, create_time, create_user_id,mrp,sale_price',
						'required' 
				),
				array (
						'item_type, status, type_id,is_tax, is_discount, category_id, sub_company_id, company_id, create_user_id, updated_by',
						'numerical',
						'integerOnly' => true 
				),
				array (
						'title',
						'unique'
						
				),
				array (
						'title, item_code',
						'length',
						'max' => 255 
				),
				array (
						'short_name,tax_id,name,qty,to_user_id,sub_category_id,description,company_bar_code,tax_id,outlet_id,bar_code,image_file,min_qty,max_qty,reorder_qty,vendor_id,hsn_code,is_coupon,mrp,sale_price,weight,purchase_price,whole_sale,is_stockable,movement_type,opening_stock,unit,start_date,end_date,remaining_quan',
						'safe' 
				),
				array (
						'description, image_file, item_type, status, type_id, is_tax, is_discount, category_id, sub_company_id, company_id, updated_by',
						'default',
						'setOnEmpty' => true,
						'value' => null 
				),
				array (
						'id, title,name,item_code, description, image_file, item_type, status, type_id, is_tax, is_discount, category_id, sub_company_id, company_id, create_time, create_user_id, updated_by,update_time,remaining_quan',
						'safe',
						'on' => 'search' 
				) 
		);
	}
	public function relations() {
		return array (
				'category' => array (
						self::BELONGS_TO,
						'ItemCategory',
						'category_id' 
				),
				'subcategory' => array (
						self::BELONGS_TO,
						'ItemCategory',
						'sub_category_id' 
				),
				
				'company' => array (
						self::BELONGS_TO,
						'ItemCompany',
						'company_id' 
				),
				'createUser' => array (
						self::BELONGS_TO,
						'User',
						'create_user_id' 
				),
				'subCompany' => array (
						self::BELONGS_TO,
						'ItemCompanyCategory',
						'sub_company_id' 
				),
				'updatedBy' => array (
						self::BELONGS_TO,
						'User',
						'updated_by' 
				),
				'itemDetails' => array (
						self::HAS_MANY,
						'ItemDetail',
						'item_id' 
				),
				'itemVendors' => array (
						self::HAS_MANY,
						'ItemVendor',
						'item_detail_id',
						// unordered, and the caller reads [0]
						'order' => 'id ASC'
				),
				'itemStocks' => array (
						self::HAS_MANY,
						'ItemStock',
						'item_id' 
				) 
		);
	}
	public function pivotModels() {
		return array ();
	}
	public function attributeLabels() {
		return array (
				'id' => Yii::t ( 'app', 'ID' ),
				
				'short_name' => Yii::t ( 'app', 'Short Name' ),
				'title' => Yii::t ( 'app', 'Title' ),
				'item_code' => Yii::t ( 'app', 'Product Code' ),
				'description' => Yii::t ( 'app', 'Bill Description' ),
				'image_file' => Yii::t ( 'app', 'Image File' ),
				'item_type' => Yii::t ( 'app', 'Product Type' ),
				'hsn_code' => Yii::t ( 'app', 'HSN Code' ),
				'status' => Yii::t ( 'app', 'Status' ),
				'type_id' => Yii::t ( 'app', 'Type' ),
				'is_tax' => Yii::t ( 'app', 'Is Tax' ),
				'min_qty' => Yii::t ( 'app', 'Minimum Quantity' ),
				'max_qty' => Yii::t ( 'app', 'Maximum Quantity' ),
				'reorder_qty' => Yii::t ( 'app', 'Reorder Quantity' ),
				'is_discount' => Yii::t ( 'app', 'Is Discount Applicable' ),
				'is_coupon' => Yii::t ( 'app', 'Is Coupon Applicable' ),
				'mrp' => Yii::t ( 'app', 'MRP' ),
				'sale_price' => Yii::t ( 'app', 'Sale Price' ),
				'weight' => Yii::t ( 'app', 'Weight' ),
				'purchase_price' => Yii::t ( 'app', 'Purchase Price' ),
				'whole_sale' => Yii::t ( 'app', 'Whole Sale' ),
				'category_id' => Yii::t ( 'app', 'Category' ),
				'sub_category_id' => Yii::t ( 'app', 'Sub Category' ),
				'sub_company_id' => Yii::t ( 'app', 'Sub Company' ),
				'tax_id' => Yii::t ( 'app', 'Tax' ),
				'company_id' => Yii::t ( 'app', 'Company' ),
				'create_time' => Yii::t ( 'app', 'Create Time' ),
				'remaining_quan'=>Yii::t ( 'app', 'Remaining Quantity' ),
				'create_user_id' => null,
				'updated_by' => null,
				'category' => null,
				'company' => null,
				'createUser' => null,
				'subCompany' => null,
				'updatedBy' => null,
				'itemDetails' => null 
		);
	}
	public static function getItemCompany($id) {
		$company = ItemCompany::model ()->findByPk ( $id );
		if ($company) {
			return $company->title;
		}
		return '';
	}
	public static function getItemCompanyCategory($id) {
		$company = ItemCompanyCategory::model ()->findByPk ( $id );
		if ($company) {
			return $company->title;
		}
		return '';
	}
	public static function getItemCategory($id) {
		$company = ItemCategory::model ()->findByPk ( $id );
		if ($company) {
			return $company->title;
		}
		return '';
	}
	public function reportstocksearch() {
		$criteria = new CDbCriteria ();
		$user = Yii::app ()->user->model;
		if(isset(Yii::app ()->session ['item_name']) && (Yii::app ()->session ['item_name'] != '')){
			$this->title = Yii::app ()->session ['item_name'];
		}
// 		if ($this->name != null) {
// 			$criteria->condition = "title LIKE :title";
// 			$criteria->params = array (
// 					':title' => trim ( (string)$this->title ) . '%',
// 					':title1' => '%' . trim ( $this->name ) . '%'
// 			);
// 		} else {
			$criteria->condition = "title LIKE :title ";
	
			$criteria->params = array (
					':title' => trim ( (string)$this->title ) . '%'
			);
		/* } */
		Yii::log ( CVarDumper::dumpAsString ( $this->name ), CLogger::LEVEL_WARNING, '$$this->name' );
		if ($user->role_id == 6) {
			$itemvendor_ids = array ();
			$vendor = Vendor::model ()->findByAttributes ( array (
					'create_user_id' => $user->id
			) );
			if ($vendor) {
				$itemvendors = ItemVendor::model ()->findAllByAttributes ( array (
						'vendor_id' => $vendor->id
				) );
				if ($itemvendors) {
	
					foreach ( $itemvendors as $itemvendor ) {
						$itemvendor_ids [] = $itemvendor->item_detail_id;
					}
				}
			}
			$criteria->addInCondition ( 'id', $itemvendor_ids );
			Yii::log ( CVarDumper::dumpAsString ( $itemvendor_ids ), CLogger::LEVEL_WARNING, '$itemvendor_ids' );
		}
		$criteria->compare ( 'id', $this->id );
	
		/*
		 * if($this->title != null){
		 * $titles = explode(' ',$this->title);
		 * foreach($titles as $title){
		 * $criteria->compare ( 'title',$title, true);
		 * }
		 * }
		 */
		/* if (Yii::app ()->session ['item_name'] != '' and Yii::app ()->session ['item_name'] != null) {
			$this->name = Yii::app ()->session ['item_name'];
		} */
		Yii::log ( CVarDumper::dumpAsString ( $this->bar_code  ), CLogger::LEVEL_WARNING, '$this->bar_code ' );
		if (isset ( $this->bar_code ) && ($this->bar_code != '')) {
			$item_detail = ItemDetail::model ()->findByAttributes ( array (
					'bar_code' => $this->bar_code
			) );
			if ($item_detail) {
	
				$criteria->compare ( 'id', $item_detail->item_id );
			}
		}
		if (isset ( $this->tax_id ) && ($this->tax_id != '')) {
			$detail_ids = [];
			$criteria4 = new CDbCriteria();
			$criteria4->addCondition('tax_id ='.$this->tax_id);
			$criteria4->order = 'id desc';
			$criteria4->group = 'item_id';
			$item_details = ItemDetail::model ()->findAll($criteria4);
			Yii::log ( CVarDumper::dumpAsString ( $this->tax_id ), CLogger::LEVEL_WARNING, '$this->tax_id' );
	
			if ($item_details) {
				foreach ( $item_details as $item_detail ) {
	
					$detail_ids [] = $item_detail->item_id;
				}
				Yii::log ( CVarDumper::dumpAsString ( $detail_ids ), CLogger::LEVEL_WARNING, '$detail_ids' );
	
			}
			$criteria->addInCondition ( 'id', $detail_ids );
		}
		if (isset ( $this->vendor_id ) && ($this->vendor_id != '') && ($user->role_id != 6)) {
			$itemvendor_idds = array ();
			$itemvendorrs = ItemVendor::model ()->findAllByAttributes ( array (
					'vendor_id' => $this->vendor_id
			) );
			if ($itemvendorrs) {
	
				foreach ( $itemvendorrs as $itemvendor ) {
					$itemvendor_idds [] = $itemvendor->item_detail_id;
				}
				$criteria->addInCondition ( 'id', $itemvendor_idds );
			}
		}
		$criteria->compare ( 'item_code', $this->item_code, true );
		$criteria->compare ( 'description', $this->description, true );
		$criteria->compare ( 'image_file', $this->image_file, true );
		$criteria->compare ( 'item_type', $this->item_type );
		$criteria->compare ( 'status', $this->status );
		$criteria->compare ( 'type_id', $this->type_id );
		$criteria->compare ( 'mrp', $this->mrp );
		$criteria->compare ( 'is_tax', $this->is_tax );
		$criteria->compare ( 'is_discount', $this->is_discount );
		$criteria->compare ( 'sale_price', $this->sale_price );
		$criteria->compare ( 'hsn_code', $this->hsn_code, true );
		$criteria->compare ( 'purchase_price', $this->purchase_price );
		$criteria->compare ( 'sub_category_id', $this->sub_category_id );
		$criteria->compare ( 'opening_stock', $this->opening_stock );
		$criteria->compare ( 'weight', $this->weight );
		$criteria->compare ( 'sub_category_id', $this->sub_category_id );
		$criteria->compare ( 'category_id', $this->category_id );
		$criteria->compare ( 'sub_company_id', $this->sub_company_id );
		$criteria->compare ( 'company_id', $this->company_id );
		$criteria->compare ( 'create_time', $this->create_time, true );
		$criteria->compare ( 'create_user_id', $this->create_user_id );
		$criteria->compare ( 'updated_by', $this->updated_by );
		Yii::log ( CVarDumper::dumpAsString ( $criteria ), CLogger::LEVEL_WARNING, '$criteria' );
		return new CActiveDataProvider ( $this, array (
				'criteria' => $criteria,
	
				'sort' => array (
						'defaultOrder' => 'id DESC'
				)
		)
				);
	}
	public function stocksearch() {
		$criteria = new CDbCriteria ();
		$user = Yii::app ()->user->model;
		if ($this->name != null) {
			$criteria->condition = "title LIKE :title AND title LIKE :title1 ";
			$criteria->params = array (
					':title' => trim ( (string)$this->title ) . '%',
					':title1' => '%' . trim ( $this->name ) . '%'
			);
		} else {
			$criteria->condition = "title LIKE :title ";
				
			$criteria->params = array (
					':title' => trim ( (string)$this->title ) . '%'
			);
		}
		Yii::log ( CVarDumper::dumpAsString ( $this->name ), CLogger::LEVEL_WARNING, '$$this->name' );
		if ($user->role_id == 6) {
			$itemvendor_ids = array ();
			$vendor = Vendor::model ()->findByAttributes ( array (
					'create_user_id' => $user->id
			) );
			if ($vendor) {
				$itemvendors = ItemVendor::model ()->findAllByAttributes ( array (
						'vendor_id' => $vendor->id
				) );
				if ($itemvendors) {
						
					foreach ( $itemvendors as $itemvendor ) {
						$itemvendor_ids [] = $itemvendor->item_detail_id;
					}
				}
			}
			$criteria->addInCondition ( 'id', $itemvendor_ids );
			Yii::log ( CVarDumper::dumpAsString ( $itemvendor_ids ), CLogger::LEVEL_WARNING, '$itemvendor_ids' );
		}
		$criteria->compare ( 'id', $this->id );
	
		/*
		 * if($this->title != null){
		 * $titles = explode(' ',$this->title);
		 * foreach($titles as $title){
		 * $criteria->compare ( 'title',$title, true);
		 * }
		 * }
		 */
		if (Yii::app ()->session ['item_name'] != '' and Yii::app ()->session ['item_name'] != null) {
			$this->name = Yii::app ()->session ['item_name'];
		}
	
		if (isset ( $this->bar_code ) && ($this->bar_code != '')) {
			$item_detail = ItemDetail::model ()->findByAttributes ( array (
					'bar_code' => $this->bar_code
			) );
			if ($item_detail) {
	
				$criteria->compare ( 'id', $item_detail->item_id );
			}
		}
		if (isset ( $this->tax_id ) && ($this->tax_id != '')) {
			$detail_ids = [];
			$criteria4 = new CDbCriteria();
			$criteria4->addCondition('tax_id ='.$this->tax_id);
			$criteria4->order = 'id desc';
			$criteria4->group = 'item_id';
			$item_details = ItemDetail::model ()->findAll($criteria4);
			Yii::log ( CVarDumper::dumpAsString ( $this->tax_id ), CLogger::LEVEL_WARNING, '$this->tax_id' );
				
			if ($item_details) {
				foreach ( $item_details as $item_detail ) {
	
					$detail_ids [] = $item_detail->item_id;
				}
				Yii::log ( CVarDumper::dumpAsString ( $detail_ids ), CLogger::LEVEL_WARNING, '$detail_ids' );
	
			}
			$criteria->addInCondition ( 'id', $detail_ids );
		}
		if (isset ( $this->vendor_id ) && ($this->vendor_id != '') && ($user->role_id != 6)) {
			$itemvendor_idds = array ();
			$itemvendorrs = ItemVendor::model ()->findAllByAttributes ( array (
					'vendor_id' => $this->vendor_id
			) );
			if ($itemvendorrs) {
	
				foreach ( $itemvendorrs as $itemvendor ) {
					$itemvendor_idds [] = $itemvendor->item_detail_id;
				}
				$criteria->addInCondition ( 'id', $itemvendor_idds );
			}
		}
		$criteria->compare ( 'item_code', $this->item_code, true );
		$criteria->compare ( 'description', $this->description, true );
		$criteria->compare ( 'image_file', $this->image_file, true );
		$criteria->compare ( 'item_type', $this->item_type );
		$criteria->compare ( 'status', $this->status );
		$criteria->compare ( 'type_id', $this->type_id );
		$criteria->compare ( 'mrp', $this->mrp );
		$criteria->compare ( 'is_tax', $this->is_tax );
		$criteria->compare ( 'is_discount', $this->is_discount );
		$criteria->compare ( 'sale_price', $this->sale_price );
		$criteria->compare ( 'hsn_code', $this->hsn_code, true );
		$criteria->compare ( 'purchase_price', $this->purchase_price );
		$criteria->compare ( 'sub_category_id', $this->sub_category_id );
		$criteria->compare ( 'opening_stock', $this->opening_stock );
		$criteria->compare ( 'weight', $this->weight );
		$criteria->compare ( 'sub_category_id', $this->sub_category_id );
		$criteria->compare ( 'category_id', $this->category_id );
		$criteria->compare ( 'sub_company_id', $this->sub_company_id );
		$criteria->compare ( 'company_id', $this->company_id );
		$criteria->compare ( 'create_time', $this->create_time, true );
		$criteria->compare ( 'create_user_id', $this->create_user_id );
		$criteria->compare ( 'updated_by', $this->updated_by );
		Yii::log ( CVarDumper::dumpAsString ( $criteria ), CLogger::LEVEL_WARNING, '$criteria' );
		return new CActiveDataProvider ( $this, array (
				'criteria' => $criteria,
				
				'sort' => array (
						'defaultOrder' => 'id DESC'
				)
		)
			 );
	}
	public function search() {
		$criteria = new CDbCriteria ();
		$user = Yii::app ()->user->model;
		if ($this->name != null) {
			$criteria->condition = "title LIKE :title AND title LIKE :title1 ";
			$criteria->params = array (
					':title' => trim ( (string)$this->title ) . '%',
					':title1' => '%' . trim ( $this->name ) . '%' 
			);
		} else {
			$criteria->condition = "title LIKE :title ";
			
			$criteria->params = array (
					':title' => trim ( (string)$this->title ) . '%' 
			);
		}
		Yii::log ( CVarDumper::dumpAsString ( $this->name ), CLogger::LEVEL_WARNING, '$$this->name' );
		if ($user->role_id == 6) {
			$itemvendor_ids = array ();
			$vendor = Vendor::model ()->findByAttributes ( array (
					'create_user_id' => $user->id 
			) );
			if ($vendor) {
				$itemvendors = ItemVendor::model ()->findAllByAttributes ( array (
						'vendor_id' => $vendor->id 
				) );
				if ($itemvendors) {
					
					foreach ( $itemvendors as $itemvendor ) {
						$itemvendor_ids [] = $itemvendor->item_detail_id;
					}
				}
			}
			$criteria->addInCondition ( 'id', $itemvendor_ids );
			Yii::log ( CVarDumper::dumpAsString ( $itemvendor_ids ), CLogger::LEVEL_WARNING, '$itemvendor_ids' );
		}
		$criteria->compare ( 'id', $this->id );
		
		/*
		 * if($this->title != null){
		 * $titles = explode(' ',$this->title);
		 * foreach($titles as $title){
		 * $criteria->compare ( 'title',$title, true);
		 * }
		 * }
		 */
		if (Yii::app ()->session ['item_name'] != '' and Yii::app ()->session ['item_name'] != null) {
			$this->name = Yii::app ()->session ['item_name'];
		}
		
		if (isset ( $this->bar_code ) && ($this->bar_code != '')) {
			$item_detail = ItemDetail::model ()->findByAttributes ( array (
					'bar_code' => $this->bar_code 
			) );
			if ($item_detail) {
				
				$criteria->compare ( 'id', $item_detail->item_id );
			}
		}
		if (isset ( $this->tax_id ) && ($this->tax_id != '')) {
			$detail_ids = [];
			$criteria4 = new CDbCriteria();
			$criteria4->addCondition('tax_id ='.$this->tax_id);
			$criteria4->order = 'id desc';
			$criteria4->group = 'item_id';
			$item_details = ItemDetail::model ()->findAll($criteria4);
			Yii::log ( CVarDumper::dumpAsString ( $this->tax_id ), CLogger::LEVEL_WARNING, '$this->tax_id' );
			
			if ($item_details) {
				foreach ( $item_details as $item_detail ) {
				
					$detail_ids [] = $item_detail->item_id;
				}
				Yii::log ( CVarDumper::dumpAsString ( $detail_ids ), CLogger::LEVEL_WARNING, '$detail_ids' );
				
			}
			$criteria->addInCondition ( 'id', $detail_ids );
		}
		if (isset ( $this->vendor_id ) && ($this->vendor_id != '') && ($user->role_id != 6)) {
			$itemvendor_idds = array ();
			$itemvendorrs = ItemVendor::model ()->findAllByAttributes ( array (
					'vendor_id' => $this->vendor_id 
			) );
			if ($itemvendorrs) {
				
				foreach ( $itemvendorrs as $itemvendor ) {
					$itemvendor_idds [] = $itemvendor->item_detail_id;
				}
				$criteria->addInCondition ( 'id', $itemvendor_idds );
			}
		}
		$criteria->compare ( 'short_name', $this->short_name, true );
		$criteria->compare ( 'item_code', $this->item_code, true );
		$criteria->compare ( 'description', $this->description, true );
		$criteria->compare ( 'image_file', $this->image_file, true );
		$criteria->compare ( 'item_type', $this->item_type );
		$criteria->compare ( 'status', $this->status );
		$criteria->compare ( 'type_id', $this->type_id );
		$criteria->compare ( 'mrp', $this->mrp );
		$criteria->compare ( 'is_tax', $this->is_tax );
		$criteria->compare ( 'is_discount', $this->is_discount );
		$criteria->compare ( 'sale_price', $this->sale_price );
		$criteria->compare ( 'hsn_code', $this->hsn_code, true );
		$criteria->compare ( 'purchase_price', $this->purchase_price );
		$criteria->compare ( 'sub_category_id', $this->sub_category_id );
		$criteria->compare ( 'opening_stock', $this->opening_stock );
		$criteria->compare ( 'weight', $this->weight );
		$criteria->compare ( 'sub_category_id', $this->sub_category_id );
		$criteria->compare ( 'category_id', $this->category_id );
		$criteria->compare ( 'sub_company_id', $this->sub_company_id );
		$criteria->compare ( 'company_id', $this->company_id );
		$criteria->compare ( 'create_time', $this->create_time, true );
		$criteria->compare ( 'create_user_id', $this->create_user_id );
		$criteria->compare ( 'updated_by', $this->updated_by );
		Yii::log ( CVarDumper::dumpAsString ( $criteria ), CLogger::LEVEL_WARNING, '$criteria' );
		return new CActiveDataProvider ( $this, array (
				'criteria' => $criteria,
				'pagination' => array (
						'pageSize' => '100'
				),
				'sort' => array (
						'defaultOrder' => 'id DESC' 
				) 
		)
		 );
	}
	public function adjust() {
		$criteria = new CDbCriteria ();
		$user = Yii::app ()->user->model;
		
		if (Yii::app ()->session ['item_name'] != '' and Yii::app ()->session ['item_name'] != null) {
			$this->name = Yii::app ()->session ['item_name'];
		}
		
		if (Yii::app ()->session ['remaining_quan'] != '' and Yii::app ()->session ['remaining_quan'] != null) {	
		$this->remaining_quan = Yii::app ()->session ['remaining_quan'];	
		}
		
		
		if ($this->name != null) {
			$criteria->condition = "title LIKE :title AND title LIKE :title1 ";
			$criteria->params = array (
					//':title' => trim ( (string)$this->title ) . '%',
					//':title' => "%" .trim ( (string)$this->title ) . '%',
					':title1' => '%' . trim ( $this->name ) . '%' 
			);
		} else {
			// $criteria->condition = "title LIKE :title ";
			
			// $criteria->params = array (
			// 		':title' => trim ( (string)$this->title ) . '%' 
			// );
		}
		Yii::log ( CVarDumper::dumpAsString ( $this->name ), CLogger::LEVEL_WARNING, '$$this->name' );
		if (isset ( Yii::app ()->session ['company_id'] ) && (Yii::app ()->session ['company_id'] != '')) {
			$this->company_id = Yii::app ()->session ['company_id'];
		}
		
		if (isset ( $this->vendor_id ) && ($this->vendor_id != '') && ($user->role_id != 6)) {
			$itemvendor_idds = array ();
			$itemvendorrs = ItemVendor::model ()->findAllByAttributes ( array (
					'vendor_id' => $this->vendor_id
			) );
			if ($itemvendorrs) {
		
				foreach ( $itemvendorrs as $itemvendor ) {
					$itemvendor_idds [] = $itemvendor->item_detail_id;
				}
				$criteria->addInCondition ( 'id', $itemvendor_idds );
			}
		}
		
		if($this->remaining_quan != null){
			
			
			
			$ids =  $this->getAscBarCodeTotalRemainingQuantityIds($this->remaining_quan );
			
			$criteria->addInCondition ( 'id', $ids );
		
			
		}else{
			
			$criteria->compare ( 'id', $this->id );
					
		}
		
		$criteria->compare ( 'title', $this->title, true );
		$criteria->compare ( 'item_code', $this->item_code, true );
		$criteria->compare ( 'description', $this->description, true );
		$criteria->compare ( 'image_file', $this->image_file, true );
		$criteria->compare ( 'mrp', $this->mrp );
		$criteria->compare ( 'item_type', $this->item_type );
		$criteria->compare ( 'status', $this->status );
		$criteria->compare ( 'type_id', $this->type_id );
		$criteria->compare ( 'is_tax', $this->is_tax );
		$criteria->compare ( 'is_discount', $this->is_discount );
		$criteria->compare ( 'sale_price', $this->sale_price );
		$criteria->compare ( 'hsn_code', $this->hsn_code, true );
		$criteria->compare ( 'purchase_price', $this->purchase_price );
		$criteria->compare ( 'sub_category_id', $this->sub_category_id );
		$criteria->compare ( 'opening_stock', $this->opening_stock );
		$criteria->compare ( 'weight', $this->weight );
		$criteria->compare ( 'sub_category_id', $this->sub_category_id );
		$criteria->compare ( 'category_id', $this->category_id );
		$criteria->compare ( 'sub_company_id', $this->sub_company_id );
		$criteria->compare ( 'company_id', $this->company_id );
		$criteria->compare ( 'create_time', $this->create_time, true );
		$criteria->compare ( 'create_user_id', $this->create_user_id );
		$criteria->compare ( 'updated_by', $this->updated_by );
		
		echo "<pre>"; print_r($criteria); echo "</pre>";
		//die;
		return new CActiveDataProvider ( $this, array (
				'criteria' => $criteria,
				'pagination' => array (
						'pageSize' => '20'
				),
				
				'sort' => array (
						'defaultOrder' => ' adjustment_time DESC' 
				) 
		) );
	}
	public function defaultScope() {
		return array ();
	}
}