<?php

 
/**
 * This is the model base class for the table "{{item_category}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ItemCategory".
 *
 * Columns in table "{{item_category}}" available as properties of the model,
 * followed by relations of table "{{item_category}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $title
 * @property integer $parent_id
 * @property integer $type_id
 * @property integer $status
 * @property string $create_time
 * @property string $update_time
 * @property integer $create_user_id
 * @property integer $updated_by
 *
 * @property Item[] $items
 * @property User $createUser
 * @property User $updatedBy
 */
abstract class BaseItemCategory extends GxActiveRecord {
	public $columns;
	public $start_date;
	public $end_date;
	const STATUS_ACTIVE = 0;
	const STATUS_INACTIVE = 1;
	public static function getTypeOptions($id = null)
	{
		$list = array("TYPE1","TYPE2","TYPE3");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
 	
	public static function getStatusOptions($id = null) {
		$list = array (
				"Active",
				"Inactive"
		);
		if ($id == null)
			return $list;
			if (is_numeric ( $id ))
				return $list [$id];
				return $id;
	}
	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
			if ( !isset( $this->create_time )) $this->create_time = date('Y-m-d H:i:s');
			if ( !isset( $this->create_user_id )) $this->create_user_id = Yii::app()->user->id;
		}else{
			if ( !isset( $this->update_time )) $this->update_time = date('Y-m-d H:i:s');
			if ( !isset( $this->updated_by )) $this->updated_by = Yii::app()->user->id;
		}
		return parent::beforeValidate();
	}
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{item_category}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ItemCategory|ItemCategories', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('title, create_user_id', 'required'),
			 array('title','unique', 'message'=>'This category already exists.'),
			array('parent_id, type_id, status, create_user_id, updated_by', 'numerical', 'integerOnly'=>true),
			array('title', 'length', 'max'=>255),
				array('title', 'unique'),
			array('create_time, update_time,start_date,end_date,columns', 'safe'),
			array('parent_id, type_id, status, create_time, update_time, updated_by', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, title, parent_id, type_id, status, create_time, update_time, create_user_id, updated_by', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'items' => array(self::HAS_MANY, 'Item', 'category_id'),
			'createUser' => array(self::BELONGS_TO, 'User', 'create_user_id'),
			'updatedBy' => array(self::BELONGS_TO, 'User', 'updated_by'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'title' => Yii::t('app', 'Category'),
			'parent_id' => Yii::t('app', 'Parent Category'),
			'type_id' => Yii::t('app', 'Type'),
			'status' => Yii::t('app', 'Status'),
			'create_time' => Yii::t('app', 'Create Time'),
			'update_time' => Yii::t('app', 'Update Time'),
			'create_user_id' => null,
			'updated_by' => null,
			'items' => null,
			'updatedBy' => Yii::t('app', 'Updated By'),
			'createUser' => Yii::t('app', 'Created By'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;
		$criteria->addCondition ( 'parent_id IS  NULL');
		$criteria->compare('id', $this->id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('parent_id', $this->parent_id);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('status', $this->status);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('update_time', $this->update_time, true);
		$criteria->compare('create_user_id', $this->create_user_id);
		$criteria->compare('updated_by', $this->updated_by);
		/* $cats = ItemCategory::model()->findAll($criteria);
		if($cats){
			$cat_total = 0;
			
			foreach($cats as $cat){
				$cat_total = $cat_total + $cat->getCategoryTotalAmount();
				
			}
		
		Yii::app ()->session ['category_total']=round($cat_total);
		} */
		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
	
	public function subcatsearch() {
		$criteria = new CDbCriteria;
		$criteria->addCondition ( 'parent_id IS NOT NULL');
		$criteria->compare('id', $this->id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('parent_id', $this->parent_id);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('status', $this->status);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('update_time', $this->update_time, true);
		$criteria->compare('create_user_id', $this->create_user_id);
		$criteria->compare('updated_by', $this->updated_by);
	
		return new CActiveDataProvider($this, array(
				'criteria' => $criteria,
		));
	}
}