<?php

/**
 * Company: ToXSL Technologies Pvt. Ltd. < www.toxsl.com >
 * Author : Shiv Charan Panjeta < shiv@toxsl.com >
 */
 
/**
 * This is the model base class for the table "{{payment_report}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PaymentReport".
 *
 * Columns in table "{{payment_report}}" available as properties of the model,
 * followed by relations of table "{{payment_report}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $doc_no
 * @property string $chq_no
 * @property string $comp_code
 * @property string $house_bank
 * @property string $hb_acct
 * @property string $ben_acc_no
 * @property string $ref_no
 * @property double $amount
 * @property integer $vendor_id
 * @property string $run_date
 * @property string $inst_date
 * @property string $value_date
 * @property string $pay_type
 * @property string $pay_status
 * @property integer $type_id
 * @property integer $status
 * @property string $create_time
 * @property string $update_time
 * @property integer $create_user_id
 * @property integer $updated_by
 *
 * @property User $createUser
 * @property User $updatedBy
 */
abstract class BasePaymentReport extends GxActiveRecord {

	public $columns;
	public static function getTypeOptions($id = null)
	{
		$list = array("TYPE1","TYPE2","TYPE3");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
 	
	public static function getStatusOptions($id = null)
	{
		$list = array("Draft","Published","Archive");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}	
	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
			if ( !isset( $this->create_time )) $this->create_time = new CDbExpression('NOW()');
				if ( !isset( $this->create_user_id )) $this->create_user_id = Yii::app()->user->id;			
	}else{
					}
		return parent::beforeValidate();
	}

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{payment_report}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PaymentReport|PaymentReports', $n);
	}

	public static function representingColumn() {
		return 'chq_no';
	}

	public function rules() {
		return array(
			array('doc_no,chq_no, hb_acct, ben_acc_no, ref_no, amount, vendor_id, run_date, inst_date, value_date, create_user_id', 'required'),
			array('doc_no, vendor_id, type_id, status, create_user_id, updated_by', 'numerical', 'integerOnly'=>true),
			array('amount', 'numerical'),
			array('chq_no,comp_code,house_bank,hb_acct,ben_acc_no,ref_no,pay_type,pay_status', 'length', 'max'=>255),
			array('create_time, update_time,columns', 'safe'),
			array('pay_type, pay_status, type_id, status, create_time, update_time, updated_by', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, doc_no, chq_no,comp_code, house_bank, hb_acct, ben_acc_no, ref_no, amount, vendor_id, run_date, inst_date, value_date, pay_type, pay_status, type_id, status, create_time, update_time, create_user_id, updated_by', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'createUser' => array(self::BELONGS_TO, 'User', 'create_user_id'),
			'updatedBy' => array(self::BELONGS_TO, 'User', 'updated_by'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'doc_no' => Yii::t('app', 'Doc No'),
			'chq_no' => Yii::t('app', 'Chq No'),
			'comp_code' => Yii::t('app', 'Comp Code'),
			'house_bank' => Yii::t('app', 'House Bank'),
			'hb_acct' => Yii::t('app', 'HB Acct'),
			'ben_acc_no' => Yii::t('app', 'Bene Acct No'),
			'ref_no' => Yii::t('app', 'Trans.Ref.No'),
			'amount' => Yii::t('app', 'Amt'),
			'vendor_id' => Yii::t('app', 'Vendor Name'),
			'run_date' => Yii::t('app', 'Run Dt'),
			'inst_date' => Yii::t('app', 'Inst.Dt'),
			'value_date' => Yii::t('app', 'Value Dt'),
			'pay_type' => Yii::t('app', 'Pay Type'),
			'pay_status' => Yii::t('app', 'Status'),
			'type_id' => Yii::t('app', 'Type'),
			'status' => Yii::t('app', 'Status'),
			'create_time' => Yii::t('app', 'Create Time'),
			'update_time' => Yii::t('app', 'Update Time'),
			'create_user_id' => null,
			'updated_by' => null,
			'createUser' => null,
			'updatedBy' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('doc_no', $this->doc_no);
		$criteria->compare('chq_no', $this->chq_no, true);
		$criteria->compare('comp_code', $this->comp_code, true);
		$criteria->compare('house_bank', $this->house_bank, true);
		$criteria->compare('hb_acct', $this->hb_acct, true);
		$criteria->compare('ben_acc_no', $this->ben_acc_no, true);
		$criteria->compare('ref_no', $this->ref_no, true);
		$criteria->compare('amount', $this->amount);
		$criteria->compare('vendor_id', $this->vendor_id);
		$criteria->compare('run_date', $this->run_date, true);
		$criteria->compare('inst_date', $this->inst_date, true);
		$criteria->compare('value_date', $this->value_date, true);
		$criteria->compare('pay_type', $this->pay_type, true);
		$criteria->compare('pay_status', $this->pay_status, true);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('status', $this->status);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('update_time', $this->update_time, true);
		$criteria->compare('create_user_id', $this->create_user_id);
		$criteria->compare('updated_by', $this->updated_by);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}