<?php


 
/**
 * This is the model base class for the table "{{order_refund}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "OrderRefund".
 *
 * Columns in table "{{order_refund}}" available as properties of the model,
 * followed by relations of table "{{order_refund}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $qty
 * @property double $discount
 * @property double $discount_amt
 * @property double $total_amt
 * @property double $paid_amt
 * @property integer $status
 * @property integer $type_id
 * @property integer $city_id
 * @property integer $state_id
 * @property integer $country_id
 * @property string $address
 * @property string $note
 * @property string $create_time
 * @property string $update_time
 * @property integer $order_id
 * @property integer $customer_id
 * @property integer $updated_by
 *
 * @property OrderRefundItem[] $orderRefundItems
 */
abstract class BaseOrderRefund extends GxActiveRecord {

	
	public static function getStatusOptions($id = null)
	{
		$list = array("Draft","Published","Archive");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}	
	public static function getTypeOptions($id = null)
	{
		$list = array("TYPE1","TYPE2","TYPE3");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
 	
		
	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
			if ( !isset( $this->create_time )) $this->create_time = new CDbExpression('NOW()');
			}else{
				}
		return parent::beforeValidate();
	}

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{order_refund}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'OrderRefund|OrderRefunds', $n);
	}

	public static function representingColumn() {
		return 'address';
	}

	public function rules() {
		return array(
			array('order_id, customer_id', 'required'),
			array('status, type_id, city_id, state_id, country_id, order_id, customer_id, updated_by', 'numerical', 'integerOnly'=>true),
			array('discount, discount_amt, total_amt, paid_amt', 'numerical'),
			array('address, note, create_time, update_time', 'safe'),
			array('qty, discount, discount_amt, total_amt, paid_amt, status, type_id, address, note, create_time, update_time, updated_by', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, qty, discount, discount_amt, total_amt, paid_amt, status, type_id, city_id, state_id, country_id, address, note, create_time, update_time, order_id, customer_id, updated_by', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'orderRefundItems' => array(self::HAS_MANY, 'OrderRefundItem', 'order_refund_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'qty' => Yii::t('app', 'Qty'),
			'discount' => Yii::t('app', 'Discount'),
			'discount_amt' => Yii::t('app', 'Discount Amt'),
			'total_amt' => Yii::t('app', 'Total Amt'),
			'paid_amt' => Yii::t('app', 'Paid Amt'),
			'status' => Yii::t('app', 'Status'),
			'type_id' => Yii::t('app', 'Type'),
			'city_id' => Yii::t('app', 'City'),
			'state_id' => Yii::t('app', 'State'),
			'country_id' => Yii::t('app', 'Country'),
			'address' => Yii::t('app', 'Address'),
			'note' => Yii::t('app', 'Note'),
			'create_time' => Yii::t('app', 'Create Time'),
			'update_time' => Yii::t('app', 'Update Time'),
			'order_id' => Yii::t('app', 'Order'),
			'customer_id' => Yii::t('app', 'Customer'),
			'updated_by' => Yii::t('app', 'Updated By'),
			'orderRefundItems' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('qty', $this->qty);
		$criteria->compare('discount', $this->discount);
		$criteria->compare('discount_amt', $this->discount_amt);
		$criteria->compare('total_amt', $this->total_amt);
		$criteria->compare('paid_amt', $this->paid_amt);
		$criteria->compare('status', $this->status);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('city_id', $this->city_id);
		$criteria->compare('state_id', $this->state_id);
		$criteria->compare('country_id', $this->country_id);
		$criteria->compare('address', $this->address, true);
		$criteria->compare('note', $this->note, true);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('update_time', $this->update_time, true);
		$criteria->compare('order_id', $this->order_id);
		$criteria->compare('customer_id', $this->customer_id);
		$criteria->compare('updated_by', $this->updated_by);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}