<?php


 
/**
 * This is the model base class for the table "{{user}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "User".
 *
 * Columns in table "{{user}}" available as properties of the model,
 * followed by relations of table "{{user}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $full_name
 * @property string $username
 * @property string $email
 * @property string $password
 * @property string $lat
 * @property string $long
 * @property string $contact_no
 * @property string $date_of_birth
 * @property string $gender
 * @property string $about_me
 * @property string $address
 * @property integer $postal_code
 * @property string $country
 * @property string $city
 * @property string $state
 * @property string $lang
 * @property string $image_file
 * @property integer $is_passenger
 * @property integer $is_dispatcher
 * @property integer $is_driver
 * @property integer $role_id
 * @property integer $state_id
 * @property integer $type_id
 * @property string $last_visit_time
 * @property string $last_action_time
 * @property string $last_password_change
 * @property string $activation_key
 * @property integer $is_active
 * @property integer $login_error_count
 * @property string $create_time
 *
 * @property AuthSession[] $authSessions
 * @property Callcenter[] $callcenters
 * @property CardDetails[] $cardDetails
 * @property Dispatcher[] $dispatchers
 * @property Driver[] $drivers
 * @property Group[] $groups
 * @property Journey[] $journeys
 * @property Notification[] $notifications
 * @property UserGroup[] $userGroups
 */
abstract class BaseUser extends GxActiveRecord {
	public $session_id;
	public $api_key;
   public $store_id;
   public $device_token;
   public $device_type;
   public $ivr_username;
	const STATUS_INACTIVE = 0;
	const STATUS_ACTIVE = 1;
	const STATUS_BANNED = -1;
	const STATUS_REMOVED = -2;
	
	const GENDER_MALE = 0;
	const GENDER_FEMALE = 1;
	//const GENDER_BOTH = 2;

	public static function getAllRoleOptions(){
		$list = array();
		$alreadyroles = array(6,7);
		$criteria = new CDbCriteria();
		$criteria->addCondition('status ='.UserRole::STATUS_ACTIVE);
		$criteria->addNotInCondition('id', $alreadyroles);
		$criteria->order = 'title asc';
		$roles = UserRole::model()->findAll($criteria);
	
		if($roles){
			foreach($roles as $role){
				$list[$role->id] = $role->title;
			}
		}
		return $list;
	}

	public static function getAllUserOptions(){
		$list = array();
		$alreadyroles = array(6,7);
		$criteria = new CDbCriteria();
		$criteria->addCondition('state_id = 1');
		$criteria->order = 'full_name asc';
		$users = User::model()->findAll($criteria);
	
		if($users){
			foreach($users as $user){
				$list[$user->id] = $user->full_name;
			}
		}
		return $list;
	}

	public function getRoleOptions(){
		$list = array();
		$alreadyroles = array();
		//$alreadyroles = array(6,7);
		$criteria = new CDbCriteria();
		$criteria->addCondition('status ='.UserRole::STATUS_ACTIVE);
		$criteria->addNotInCondition('id', $alreadyroles);
		$criteria->order = 'title asc';
		$roles = UserRole::model()->findAll($criteria);
		
		if($roles){
			foreach($roles as $role){
				$list[$role->id] = $role->title;
			}
		}
		return $list;
	}
	public static function getStatusOptions($id = null)
	{
		$list = array(
				self::STATUS_INACTIVE => 'Inactive',
				self::STATUS_ACTIVE =>  'Active',
				self::STATUS_BANNED =>  'Banned',
				self::STATUS_REMOVED =>  'Removed' );
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
	
	public static function getGenderOptions($id = null)
	{
		$list = array(
				self::GENDER_MALE => 'Male',
				self::GENDER_FEMALE =>  'Female',
			//	self::GENDER_BOTH =>  'Both',
				 );
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
	public static function getTypeOptions($id = null)
	{
		$list = array("Type1","Type2");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
	
	
 	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
		if ( !isset( $this->create_time )) $this->create_time = date( 'Y-m-d H:i:s');
		if ( !isset( $this->last_password_change )) $this->last_password_change = date( 'Y-m-d H:i:s');
		}else{
			if ( !isset( $this->last_password_change )) $this->last_password_change = date( 'Y-m-d H:i:s');
						}
		return parent::beforeValidate();
	}

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{user}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'User|Users', $n);
	}

	public static function representingColumn() {
		return 'full_name';
	}

	public function rules() {
		return array(
			array('username, email', 'required'), //, contact_no
			array('password,username, email', 'required','on'=>'create'), //, contact_no
			array('password,password_2', 'required','on'=>'changepassword'), //, contact_no
			array('postal_code, role_id, state_id, type_id, is_active, login_error_count',  'numerical', 'integerOnly'=>true),
			array('full_name,username, email', 'length', 'max'=>256),
			array('password, address, image_file, activation_key', 'length', 'max'=>512),
			array('lat, long', 'length', 'max'=>32),
			array('username', 'unique'),
			array('email', 'unique'),
				array('email', 'email'),
			array('contact_no', 'length', 'max'=>255),
			array('country, city, state', 'length', 'max'=>128),
			array('lang', 'length', 'max'=>8),
			array('date_of_birth,question_id,answer,about_me,username,category_id,last_visit_time, last_action_time, last_password_change, create_time,store_id,provider,device_token,device_type,session_id,device_token,api_key,ivr_username', 'safe'),
			array('lat, long, contact_no,username, date_of_birth,gender, about_me, address, postal_code, country, city, state, lang, role_id, state_id, type_id, last_visit_time, last_action_time, last_password_change, activation_key, is_active, login_error_count,  create_time', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, full_name, email,username, password, lat, long, contact_no, date_of_birth,gender, about_me, address, postal_code, country, city, state, lang, image_file,role_id, state_id, type_id, last_visit_time, last_action_time, last_password_change, activation_key, is_active, login_error_count,  create_time', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'authSessions' => array(self::HAS_MANY, 'AuthSession', 'create_user_id'),
			'callcenters' => array(self::HAS_MANY, 'Callcenter', 'user_id'),
			'cardDetails' => array(self::HAS_MANY, 'CardDetails', 'user_id'),
			'dispatchers' => array(self::HAS_MANY, 'Dispatcher', 'user_id'),
			'drivers' => array(self::HAS_MANY, 'Driver', 'user_id'),
			'groups' => array(self::HAS_MANY, 'Group', 'create_user_id'),
			'journeys' => array(self::HAS_MANY, 'Journey', 'create_user_id'),
			'notifications' => array(self::HAS_MANY, 'Notification', 'create_user_id'),
			'userGroups' => array(self::HAS_MANY, 'UserGroup', 'user_id'),
			'bar' => array(self::HAS_ONE, 'Bar', 'create_user_id'),
			'trans' => array(self::HAS_ONE, 'Transaction', 'user_id'),
			'role' => array(self::BELONGS_TO, 'UserRole', 'role_id'),
				'emp' => array(self::BELONGS_TO, 'Emp', 'emp_id'),
			'stores' => array(self::HAS_MANY, 'MerchantStore', 'merchant_id'),
	     	);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'full_name' => Yii::t('app', 'Full Name'),
			'username' => Yii::t('app', 'Username'),
			'email' => Yii::t('app', 'Email'),
			'password' => Yii::t('app', 'Password'),
	    	'password_2' => Yii::t('app', 'Confirm Password'),
			'lat' => Yii::t('app', 'Lat'),
			'long' => Yii::t('app', 'Long'),
			'contact_no' => Yii::t('app', 'Contact No'),
			'date_of_birth' => Yii::t('app', 'Date Of Birth'),
			'store_id' => Yii::t('app', 'Store'),
	    	'gender' => Yii::t('app', 'Gender'),
			'about_me' => Yii::t('app', 'About Me'),
			'address' => Yii::t('app', 'Address'),
			'postal_code' => Yii::t('app', 'Postal Code'),
			'country' => Yii::t('app', 'Country'),
			'city' => Yii::t('app', 'City'),
			'state' => Yii::t('app', 'State'),
			'session_id' => Yii::t('app', 'Session'),
				
			'lang' => Yii::t('app', 'Lang'),
			'image_file' => Yii::t('app', 'Image File'),
			'is_passenger' => Yii::t('app', 'Is Passenger'),
			'is_dispatcher' => Yii::t('app', 'Is Dispatcher'),
			'is_driver' => Yii::t('app', 'Is Driver'),
			'role_id' => Yii::t('app', 'Role'),
			'state_id' => Yii::t('app', 'State'),
			'type_id' => Yii::t('app', 'Type'),
			'last_visit_time' => Yii::t('app', 'Last Visit Time'),
			'last_action_time' => Yii::t('app', 'Last Action Time'),
			'last_password_change' => Yii::t('app', 'Last Password Change'),
			'activation_key' => Yii::t('app', 'Activation Key'),
			'is_active' => Yii::t('app', 'Is Active'),
			'login_error_count' => Yii::t('app', 'Login Error Count'),
			'create_time' => Yii::t('app', 'Create Time'),
			'authSessions' => null,
			'callcenters' => null,
			'cardDetails' => null,
			'dispatchers' => null,
			'drivers' => null,
			'groups' => null,
			'journeys' => null,
			'notifications' => null,
			'userGroups' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;
		$alreadyroles = array('6,7');
		$criteria->compare('id', $this->id);
		$criteria->addNotInCondition('role_id', $alreadyroles);
		$criteria->compare('full_name', $this->full_name, true);
		$criteria->compare('username', $this->username, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('password', $this->password, true);
		$criteria->compare('lat', $this->lat, true);
		$criteria->compare('long', $this->long, true);
		$criteria->compare('contact_no', $this->contact_no, true);
		$criteria->compare('date_of_birth', $this->date_of_birth, true);
		$criteria->compare('gender', $this->gender, true);
		$criteria->compare('about_me', $this->about_me, true);
		$criteria->compare('address', $this->address, true);
		$criteria->compare('postal_code', $this->postal_code);
		$criteria->compare('country', $this->country, true);
		$criteria->compare('city', $this->city, true);
		$criteria->compare('state', $this->state, true);
		$criteria->compare('lang', $this->lang, true);
		$criteria->compare('image_file', $this->image_file, true);
		
		$criteria->compare('role_id', $this->role_id);
		$criteria->compare('state_id', $this->state_id);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('last_visit_time', $this->last_visit_time, true);
		$criteria->compare('last_a ction_time', $this->last_action_time, true);
		$criteria->compare('last_password_change', $this->last_password_change, true);
		$criteria->compare('activation_key', $this->activation_key, true);
		$criteria->compare('is_active', $this->is_active);
		$criteria->compare('login_error_count', $this->login_error_count);
		$criteria->compare('create_time', $this->create_time, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}
