<?php


/**
 * This is the model base class for the table "{{online_order}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "OnlineOrder".
 *
 * Columns in table "{{online_order}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $order_id
 * @property integer $item_count
 * @property double $grand_total
 * @property string $first_name
 * @property string $last_name
 * @property string $street
 * @property string $city
 * @property string $telephone
 * @property string $zip_code
 * @property string $country
 * @property string $delivery_slot
 * @property string $ship_name
 * @property integer $type_id
 * @property string $status
 * @property string $create_time
 * @property string $update_time
 * @property integer $create_user_id
 * @property integer $updated_by
 *
 */
abstract class BaseOnlineOrder extends GxActiveRecord {
	public $start_date;
	public $end_date;
 const STATUS_PENDING = "Pending";
 const STATUS_PROCESSING = "Processing";
 const STATUS_CANCELLED = "Cancelled";
 const STATUS_COMPLETED = "Completed";
 
 const ORDERSTATUS_PENDING = 0;
 const ORDERSTATUS_PACKED = 1;
 const ORDERSTATUS_SHIPPED = 2;
 const ORDERSTATUS_COMPLETED = 3;
  const ORDERSTATUS_CANCELLED = 4;
 
 const ORDER_NOT_SHIPPED = 0;
 const ORDER_SHIPPED = 1;
 
 const TYPE_NEW = 0;
 const TYPE_OPEN = 1;
 
	public static function getTypeOptions($id = null)
	{
		$list = array("New","Opened");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
	public static function getOrderStatusOptions($id = null)
	{
		$list = array(self::ORDERSTATUS_PENDING=>"Pending",
				self::ORDERSTATUS_PACKED=>"Packed",
				self::ORDERSTATUS_SHIPPED=>"Shipped",
				self::ORDERSTATUS_COMPLETED=>"Completed",
				  self::ORDERSTATUS_CANCELLED=>"Cancelled"
				
				);
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
	public static function getStatusOptions($id = null)
	{
		$list = array("Pending"=>"Pending","Processing"=>"Processing","Cancelled"=>"Cancelled","Completed"=>"Completed");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}	
	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
			if ( !isset( $this->create_time )) $this->create_time = new CDbExpression('NOW()');
				if ( !isset( $this->create_user_id )) $this->create_user_id = Yii::app()->user->id;			
	}else{
					}
		return parent::beforeValidate();
	}

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{online_order}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'OnlineOrder|OnlineOrders', $n);
	}

	public static function representingColumn() {
		return 'first_name';
	}

	public function rules() {
		return array(
			array('order_id', 'required'),
			array('order_id, item_count, type_id, create_user_id, updated_by', 'numerical', 'integerOnly'=>true),
			array('grand_total', 'numerical'),
			array('first_name, last_name, street, city, telephone, zip_code, country, delivery_slot, ship_name, status', 'length', 'max'=>255),
			array('create_time, update_time,order_date,online_order_id,delivery_boy,delivery_telephone,payment_method,delivery_method,start_date,end_date,mobile,order_status,delivery_boy_id,picker_id,is_shipped', 'safe'),
			array('item_count, grand_total, first_name, last_name, street, city, telephone, zip_code, country, delivery_slot, ship_name, type_id, status, create_time, update_time, create_user_id, updated_by', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, order_id, item_count, grand_total, first_name, last_name, street, city, telephone, zip_code, country, delivery_slot, ship_name, type_id, status, create_time, update_time, create_user_id, updated_by', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
				'picker' => array(self::BELONGS_TO, 'User', 'picker_id'),
				'deliveryBoy' => array(self::BELONGS_TO, 'User', 'delivery_boy_id'),
				'onlineOrderItems' => array(self::HAS_MANY, 'OnlineOrderItem', 'order_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'order_id' => Yii::t('app', 'Order No.'),
			'item_count' => Yii::t('app', 'Item Count'),
			'grand_total' => Yii::t('app', 'Order Amount'),
			'first_name' => Yii::t('app', 'Customer Name'),
			'last_name' => Yii::t('app', 'Last Name'),
			'street' => Yii::t('app', 'Address'),
			'city' => Yii::t('app', 'City'),
			'telephone' => Yii::t('app', 'Telephone'),
			'zip_code' => Yii::t('app', 'Zip Code'),
			'country' => Yii::t('app', 'Country'),
			'delivery_slot' => Yii::t('app', 'Delivery Slot'),
			'ship_name' => Yii::t('app', 'Assign To'),
			'type_id' => Yii::t('app', 'Type'),
			'status' => Yii::t('app', 'Status'),
			'order_status' => Yii::t('app', 'Order Status'),
			'create_time' => Yii::t('app', 'Create Time'),
			'update_time' => Yii::t('app', 'Update Time'),
			'create_user_id' => Yii::t('app', 'Create User'),
			'updated_by' => Yii::t('app', 'Updated By'),
				'delivery_boy' => Yii::t('app', 'Delivery Boy'),
				'delivery_telephone' => Yii::t('app', 'Delivery Boy No.'),
				'payment_method' => Yii::t('app', 'Payment Method'),
				'delivery_method' => Yii::t('app', 'Delivery Method'),
				
				
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('order_id', $this->order_id);
		$criteria->compare('order_date', $this->order_date);
		if(($this->start_date != '' && $this->start_date != null) && ($this->end_date != '' && $this->end_date != null)){
			$criteria->addBetweenCondition('date(order_date)', $this->start_date, $this->end_date);
		}
		$criteria->compare('delivery_boy', $this->delivery_boy);
		$criteria->compare('delivery_telephone', $this->delivery_telephone);
		$criteria->compare('payment_method', $this->payment_method);
		$criteria->compare('delivery_method', $this->delivery_method);
		$criteria->compare('item_count', $this->item_count);
		$criteria->compare('grand_total', $this->grand_total);
		$criteria->compare('first_name', $this->first_name, true);
		$criteria->compare('last_name', $this->last_name, true);
		$criteria->compare('street', $this->street, true);
		$criteria->compare('city', $this->city, true);
		$criteria->compare('telephone', $this->telephone, true);
		$criteria->compare('zip_code', $this->zip_code, true);
		$criteria->compare('country', $this->country, true);
		$criteria->compare('delivery_slot', $this->delivery_slot, true);
		$criteria->compare('ship_name', $this->ship_name, true);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('status', $this->status, true);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('update_time', $this->update_time, true);
		$criteria->compare('create_user_id', $this->create_user_id);
		$criteria->compare('updated_by', $this->updated_by);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
				'pagination' => array (
						'pageSize' => '50'
				),
		));
	}
}