<?php

/**
 * Company: ToXSL Technologies Pvt. Ltd. < www.toxsl.com >
 * Author : Shiv Charan Panjeta < shiv@toxsl.com >
 */
 
/**
 * This is the model base class for the table "{{item_expire_item}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ItemExpireItem".
 *
 * Columns in table "{{item_expire_item}}" available as properties of the model,
 * followed by relations of table "{{item_expire_item}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $item_id
 * @property integer $item_detail_id
 * @property string $mrp
 * @property string $sale_rate
 * @property integer $free
 * @property integer $qty
 * @property string $total_amt
 * @property integer $vendor_id
 * @property integer $outlet_id
 * @property integer $status
 * @property integer $type_id
 * @property string $create_time
 * @property integer $create_user_id
 * @property integer $item_expire_id
 * @property integer $updated_by
 *
 * @property User $createUser
 * @property ItemDetail $itemDetail
 * @property ItemExpire $itemExpire
 * @property Item $item
 * @property Outlet $outlet
 * @property User $updatedBy
 */
abstract class BaseItemExpireItem extends GxActiveRecord {

	
	public static function getStatusOptions($id = null)
	{
		$list = array("Draft","Published","Archive");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}	
	public static function getTypeOptions($id = null)
	{
		$list = array("TYPE1","TYPE2","TYPE3");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
 	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
			if ( !isset( $this->create_time )) $this->create_time = new CDbExpression('NOW()');
			if ( !isset( $this->create_user_id )) $this->create_user_id = Yii::app()->user->id;			
	}else{
				}
		return parent::beforeValidate();
	}

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{item_expire_item}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ItemExpireItem|ItemExpireItems', $n);
	}

	public static function representingColumn() {
		return 'create_time';
	}

	public function rules() {
		return array(
			array('vendor_id, outlet_id, create_time, create_user_id, item_expire_id', 'required'),
			array('item_id, item_detail_id, free, vendor_id, outlet_id, status, type_id, create_user_id, item_expire_id, updated_by', 'numerical', 'integerOnly'=>true),
			array('mrp, sale_rate, total_amt', 'length', 'max'=>10),
			array('item_id, item_detail_id, mrp, sale_rate, free, qty, total_amt, status, type_id, updated_by', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, item_id, item_detail_id, mrp, sale_rate, free, qty, total_amt, vendor_id, outlet_id, status, type_id, create_time, create_user_id, item_expire_id, updated_by', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'createUser' => array(self::BELONGS_TO, 'User', 'create_user_id'),
			'itemDetail' => array(self::BELONGS_TO, 'ItemDetail', 'item_detail_id'),
			'itemExpire' => array(self::BELONGS_TO, 'ItemExpire', 'item_expire_id'),
			'item' => array(self::BELONGS_TO, 'Item', 'item_id'),
			'outlet' => array(self::BELONGS_TO, 'Outlet', 'outlet_id'),
				'vendor' => array(self::BELONGS_TO, 'Vendor', 'vendor_id'),
			'updatedBy' => array(self::BELONGS_TO, 'User', 'updated_by'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'item_id' => null,
			'item_detail_id' => null,
			'mrp' => Yii::t('app', 'Mrp'),
			'sale_rate' => Yii::t('app', 'Sale Rate'),
			'free' => Yii::t('app', 'Free'),
			'qty' => Yii::t('app', 'Qty'),
			'total_amt' => Yii::t('app', 'Total Amt'),
			'vendor_id' => Yii::t('app', 'Vendor'),
			'outlet_id' => null,
			'status' => Yii::t('app', 'Status'),
			'type_id' => Yii::t('app', 'Type'),
			'create_time' => Yii::t('app', 'Create Time'),
			'create_user_id' => null,
			'item_expire_id' => null,
			'updated_by' => null,
			'createUser' => null,
			'itemDetail' => null,
			'itemExpire' => null,
			'item' => null,
			'outlet' => null,
			'updatedBy' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('item_id', $this->item_id);
		$criteria->compare('item_detail_id', $this->item_detail_id);
		$criteria->compare('mrp', $this->mrp, true);
		$criteria->compare('sale_rate', $this->sale_rate, true);
		$criteria->compare('free', $this->free);
		$criteria->compare('qty', $this->qty);
		$criteria->compare('total_amt', $this->total_amt, true);
		$criteria->compare('vendor_id', $this->vendor_id);
		$criteria->compare('outlet_id', $this->outlet_id);
		$criteria->compare('status', $this->status);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('create_user_id', $this->create_user_id);
		$criteria->compare('item_expire_id', $this->item_expire_id);
		$criteria->compare('updated_by', $this->updated_by);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}