<?php


 
/**
 * This is the model base class for the table "{{b2bpurchase_bill}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "B2bPurchaseBill".
 *
 * Columns in table "{{b2bpurchase_bill}}" available as properties of the model,
 * followed by relations of table "{{b2bpurchase_bill}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $code
 * @property string $start_date
 * @property string $end_date
 * @property string $receiving_date
 * @property integer $status
 * @property integer $type_id
 * @property integer $is_open_po
 * @property integer $is_po_received
 * @property string $remarks
 * @property string $payment_terms
 * @property string $transport_mode
 * @property double $purchase_order_amount
 * @property double $charges_total_amount
 * @property double $discount_amount
 * @property double $frieght_charges
 * @property double $extra_charges
 * @property double $total_amount
 * @property string $create_time
 * @property string $update_time
 * @property integer $create_user_id
 * @property integer $updated_by
 * @property integer $outlet_id
 * @property integer $vendor_id
 * @property integer $purchase_order_id
 * @property integer $organization_id
 *
 * @property User $createUser
 * @property Organization $organization
 * @property Outlet $outlet
 * @property PurchaseOrder $purchaseOrder
 * @property User $updatedBy
 * @property Vendor $vendor
 * @property PurchaseBillDetail[] $purchaseBillDetails
 */
abstract class BaseB2bPurchaseBill extends GxActiveRecord {
	public $columns;
	public $qty;
	public $min_amt;
	public $max_amt;
	public $mode_of_payment;
	public $bill_date;
	public $end_date;
	public $print_id;
	const STATUS_UNAPPROVED = 0;
	const STATUS_APPROVED = 1;
	const STATUS_RECEIVED = 2;
	const PAYMENT_PENDING = 0;
	const PAYMENT_DONE = 1;
	const IS_CONSIGNMENT = 1;
	const IS_CONSIGNMENT_CHECK = 1;
	public static function getStatusOptions($id = null)
	{
		$list = array("UnApproved","Approved","Received");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}	
	public static function getTypeOptions($id = null)
	{
		$list = array("TYPE1","TYPE2","TYPE3");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
 	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
			if ( !isset( $this->create_time )) $this->create_time = new CDbExpression('NOW()');
				if ( !isset( $this->create_user_id )) $this->create_user_id = Yii::app()->user->id;			
	}else{
					}
		return parent::beforeValidate();
	}

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{b2bpurchase_bill}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'B2b PurchaseBill|B2b PurchaseBills', $n);
	}

	public static function representingColumn() {
		return 'code';
	}

	public function rules() {
		return array(
			array('code, start_date, vendor_id, purchase_order_id, organization_id', 'required'),
			array('status, type_id, is_open_po, is_po_received, create_user_id, updated_by, outlet_id, vendor_id, purchase_order_id, organization_id', 'numerical', 'integerOnly'=>true),
			array('purchase_order_amount, charges_total_amount, discount_amount, frieght_charges, extra_charges, total_amount', 'numerical'),
			array('code, transport_mode', 'length', 'max'=>255),
			array('remarks, payment_terms, create_time, update_time,columns,bill_no,bill_date,bill_amount,payment_days,credit_note_disc,credit_note_id,qty,print_id,is_consignment,payment_done,original_vendor_id,mode_of_payment,min_amt,max_amt', 'safe'),
			array('status, type_id, is_open_po, is_po_received, remarks, payment_terms, purchase_order_amount, charges_total_amount, discount_amount, frieght_charges, extra_charges, total_amount, create_time, update_time, updated_by, outlet_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, code, start_date, end_date, receiving_date, status, type_id, is_open_po, is_po_received, remarks, payment_terms, transport_mode, purchase_order_amount, charges_total_amount, discount_amount, frieght_charges, extra_charges, total_amount, create_time, update_time, create_user_id, updated_by, outlet_id, vendor_id, purchase_order_id, organization_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'createUser' => array(self::BELONGS_TO, 'User', 'create_user_id'),
			'organization' => array(self::BELONGS_TO, 'Organization', 'organization_id'),
			'outlet' => array(self::BELONGS_TO, 'Outlet', 'outlet_id'),
			'purchaseOrder' => array(self::BELONGS_TO, 'PurchaseOrder', 'purchase_order_id'),
			'updatedBy' => array(self::BELONGS_TO, 'User', 'updated_by'),
			'vendor' => array(self::BELONGS_TO, 'Vendor', 'vendor_id'),
			'purchaseBillDetails' => array(self::HAS_MANY, 'PurchaseBillDetail', 'purchase_bill_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'Grn No'),
			'code' => Yii::t('app', 'Code'),
			'min_amt' => Yii::t('app', 'Minimum Total Amount'),
				'max_amt' => Yii::t('app', 'Maximum Total Amount'),
			'start_date' => Yii::t('app', 'Start Date'),
			'end_date' => Yii::t('app', 'End Date'),
			'receiving_date' => Yii::t('app', 'Receiving Date'),
			'status' => Yii::t('app', 'Status'),
			'type_id' => Yii::t('app', 'Type'),
			'is_open_po' => Yii::t('app', 'Is Open Po'),
			'is_po_received' => Yii::t('app', 'Is Po Received'),
			'remarks' => Yii::t('app', 'Remarks'),
			'payment_terms' => Yii::t('app', 'Payment Terms'),
			'transport_mode' => Yii::t('app', 'Transport Mode'),
			'purchase_order_amount' => Yii::t('app', 'Purchase Order Amount'),
			'charges_total_amount' => Yii::t('app', 'Charges Total Amount'),
				'credit_note_disc' => Yii::t('app', 'Credit Note Discount'),
			'discount_amount' => Yii::t('app', 'Discount Amount'),
			'frieght_charges' => Yii::t('app', 'Frieght Charges'),
			'extra_charges' => Yii::t('app', 'Extra Charges'),
			'total_amount' => Yii::t('app', 'Total Amount'),
			'create_time' => Yii::t('app', 'Create Time'),
			'update_time' => Yii::t('app', 'Update Time'),
				'print_id' => Yii::t('app', 'Item'),
				
			'create_user_id' => null,
			'updated_by' => null,
			'outlet_id' => Yii::t('app', 'Outlet'),
			'vendor_id' => Yii::t('app', 'Vendor'),
			'purchase_order_id' => null,
			'organization_id' => null,
			'createUser' => Yii::t('app', 'Create User'),
			'organization' => null,
			'outlet' => null,
			'purchaseOrder' => null,
			'updatedBy' => Yii::t('app', 'Updated By'),
			'vendor' => null,
			'purchaseBillDetails' => null,
		);
	}
	public function listsearch($val = false) {
		$start_date = $this->getSessionStartDate();
		$end_date = $this->getSessionEndDate();
		Yii::log ( CVarDumper::dumpAsString ( $start_date ), CLogger::LEVEL_WARNING, '$$$start_date' );
		Yii::log ( CVarDumper::dumpAsString ( $end_date ), CLogger::LEVEL_WARNING, '$$$end_date' );
		$user = Yii::app()->user->model;
		$role_id = $user->role_id;
	
	
		$criteria = new CDbCriteria;
		Yii::log ( CVarDumper::dumpAsString ( $role_id ), CLogger::LEVEL_WARNING, '$role_id' );
		if($role_id== 6){
	
			$vendor = Vendor::model()->findByAttributes(array('create_user_id'=>$user->id));
			if($vendor)
				$criteria->compare('vendor_id', $vendor->id);
		}else{
			if($this->vendor_id != null){
				$criteria->compare('vendor_id', $this->vendor_id);
			}
		}
		
			$criteria->addInCondition('status',array(PurchaseBill::STATUS_UNAPPROVED,PurchaseBill::STATUS_RECEIVED));
		
		/* if($val == false){
			$vendor_ids = array();
			$criteria1 = new CDbCriteria;
			$criteria1->addCondition('is_cash ='.Vendor::IS_CASH);
			$vendors= Vendor::model()->findAll($criteria1);
			if($vendors){
				foreach($vendors as $vendor){
					$vendor_ids[] = $vendor->id;
				}
			}
			$criteria->addNotInCondition('vendor_id',$vendor_ids);
		} */
		$criteria->addCondition('payment_done ='.PurchaseBill::PAYMENT_PENDING);
		if($start_date != '' && $end_date != ''){
			$criteria->addBetweenCondition('date(create_time)', $start_date, $end_date);
		}
		$criteria->compare('id', $this->id);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('bill_no', $this->bill_no, true);
		$criteria->compare('bill_amount', $this->bill_amount, true);
		$criteria->compare('start_date', $this->start_date, true);
		$criteria->compare('end_date', $this->end_date, true);
		$criteria->compare('receiving_date', $this->receiving_date, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('is_open_po', $this->is_open_po);
		$criteria->compare('is_po_received', $this->is_po_received);
		$criteria->compare('remarks', $this->remarks, true);
		$criteria->compare('payment_terms', $this->payment_terms, true);
		$criteria->compare('transport_mode', $this->transport_mode, true);
		$criteria->compare('purchase_order_amount', $this->purchase_order_amount);
		$criteria->compare('charges_total_amount', $this->charges_total_amount);
		$criteria->compare('discount_amount', $this->discount_amount);
		$criteria->compare('frieght_charges', $this->frieght_charges);
		$criteria->compare('extra_charges', $this->extra_charges);
		$criteria->compare('total_amount', $this->total_amount);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('update_time', $this->update_time, true);
		$criteria->compare('create_user_id', $this->create_user_id);
		$criteria->compare('updated_by', $this->updated_by);
		$criteria->compare('outlet_id', $this->outlet_id);
		//$criteria->compare('vendor_id', $this->vendor_id);
		$criteria->compare('purchase_order_id', $this->purchase_order_id);
		$criteria->compare('organization_id', $this->organization_id);
	
		return new CActiveDataProvider($this, array(
				'criteria' => $criteria,
				'pagination' => array (
						'pageSize' => '100'
				),
				'sort'=>array(
						'defaultOrder'=>'id DESC',
				),
		));
	}
	public function search($val = false) {
	
 		$start_date = $this->getSessionStartDate();
		$end_date = $this->getSessionEndDate();
		Yii::log ( CVarDumper::dumpAsString ( $start_date ), CLogger::LEVEL_WARNING, '$$$start_date' );
		Yii::log ( CVarDumper::dumpAsString ( $end_date ), CLogger::LEVEL_WARNING, '$$$end_date' );
		
		$user = Yii::app()->user->model;
		$role_id = $user->role_id;
	//	echo $start_date; die;
	try{
		$criteria = new CDbCriteria;
		Yii::log ( CVarDumper::dumpAsString ( $role_id ), CLogger::LEVEL_WARNING, '$role_id' );
		if($role_id== 6){
		
			$vendor = Vendor::model()->findByAttributes(array('create_user_id'=>$user->id));
			if($vendor)
				$criteria->compare('vendor_id', $vendor->id);
		}
		/* if($val == true){
			$criteria->addInCondition('status',array(PurchaseBill::STATUS_UNAPPROVED,PurchaseBill::STATUS_RECEIVED));
		} */
		if($val == false){
			$vendor_ids = array();
			$criteria1 = new CDbCriteria;
			$criteria1->addCondition('is_cash ='.Vendor::IS_CASH);
			$vendors= Vendor::model()->findAll($criteria1);
			if($vendors){
				foreach($vendors as $vendor){
					$vendor_ids[] = $vendor->id;
				}
			}
			$criteria->addNotInCondition('vendor_id',$vendor_ids);
		}
		$criteria->addCondition('payment_done ='.B2bPurchaseBill::PAYMENT_PENDING);
		$criteria->addCondition('status ='. B2bPurchaseBill::STATUS_APPROVED);
		
		// if($start_date != '' && $end_date != ''){
			// $criteria->addBetweenCondition('start_date', $start_date, $end_date);
			// $criteria->addBetweenCondition('date(create_time)', $start_date, $end_date);
		// }
		
		
		 if(($this->start_date != '' && $this->start_date != null) && ($this->end_date != '' && $this->end_date != null)){
			 $criteria->addBetweenCondition('start_date', $this->start_date, $this->end_date);
		}
		if((Yii::app()->session['start_date'] != '') && (Yii::app()->session['end_date'] != '')){
			 $criteria->addBetweenCondition('start_date',Yii::app()->session['start_date'], Yii::app()->session['end_date']);
		} 
		// $criteria->addBetweenCondition('start_date', $start_date, $end_date);
		$criteria->compare('id', $this->id);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('bill_no', $this->bill_no, true);
		$criteria->compare('bill_amount', $this->bill_amount, true);
		
		// $criteria->compare('start_date', $this->start_date, true);
		// $criteria->compare('end_date', $this->end_date, true);
		$criteria->compare('receiving_date', $this->receiving_date, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('is_open_po', $this->is_open_po);
		$criteria->compare('is_po_received', $this->is_po_received);
		$criteria->compare('remarks', $this->remarks, true);
		$criteria->compare('payment_terms', $this->payment_terms, true);
		$criteria->compare('transport_mode', $this->transport_mode, true);
		$criteria->compare('purchase_order_amount', $this->purchase_order_amount);
		$criteria->compare('charges_total_amount', $this->charges_total_amount);
		$criteria->compare('discount_amount', $this->discount_amount);
		$criteria->compare('frieght_charges', $this->frieght_charges);
		$criteria->compare('extra_charges', $this->extra_charges);
		$criteria->compare('total_amount', $this->total_amount);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('update_time', $this->update_time, true);
		$criteria->compare('create_user_id', $this->create_user_id);
		$criteria->compare('updated_by', $this->updated_by);
		$criteria->compare('outlet_id', $this->outlet_id);
		
		 $data=  B2bPurchaseBill::model()->findAll($criteria);
	   } catch (Exception $ex) {
		
		echo $ex ; die;
	}
		
		 
		 
		 
		 
		 
		// echo"<pre>"; print_r($data); die;
		if($this->vendor_id != null){
			//	$criteria1->compare('vendor_id', $this->vendor_id);
			$criteria2 = new CDbCriteria ();
			$criteria2->condition = "name LIKE :name";
			$criteria2->params = array (
					':name' =>   $this->vendor_id  . '%'
			);
			$vendors = Vendor::model()->findAll($criteria2);
			
			Yii::log ( CVarDumper::dumpAsString ( $vendors ), CLogger::LEVEL_WARNING, '$vendor' );
			if($vendors){
				foreach($vendors as $vendor){
					$vendor_ids[] = $vendor->id;
				}
				$criteria->addInCondition('vendor_id', $vendor_ids);
			}
		}
		//$criteria->compare('vendor_id', $this->vendor_id);
		$criteria->compare('purchase_order_id', $this->purchase_order_id);
		$criteria->compare('organization_id', $this->organization_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
				'pagination' => array (
						'pageSize' => '100'
				),
				'sort'=>array(
						'defaultOrder'=>'id DESC',
				),
		));
	}
	
	
	
	
	public function userwisesearch() {
		$criteria = new CDbCriteria;
		 if(($this->start_date != '' && $this->start_date != null) && ($this->end_date != '' && $this->end_date != null)){
			 $criteria->addBetweenCondition('start_date', $this->start_date, $this->end_date);
		}
		if((Yii::app()->session['start_date'] != '') && (Yii::app()->session['end_date'] != '')){
			 $criteria->addBetweenCondition('start_date',Yii::app()->session['start_date'], Yii::app()->session['end_date']);
		} 
		$criteria->group = 'create_user_id';
		// MySQL 5.7 sorted GROUP BY results implicitly; MySQL 8.0 does not. Order
		// explicitly by the grouped columns to preserve the previous output order.
		$criteria->order = 'create_user_id';
		$criteria->addCondition('status =1');
		// $criteria->compare('id', $this->id);
		$criteria->compare('bill_no', $this->bill_no);
		$criteria->compare('total_discount', $this->total_discount);
		if($this->bill_amount != '0.000'){
		$criteria->compare('bill_amount', $this->bill_amount);
		}
		$criteria->compare('tax_amount', $this->tax_amount);
		$criteria->compare('gross_amt', $this->gross_amt);
		 $criteria->compare('status', $this->status);
		$criteria->compare('type_id', $this->type_id); 
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('update_time', $this->update_time, true);
		$criteria->compare('updated_by', $this->updated_by); 
	
	   /*  if($orders){
			$taxable = 0;
			$total = 0;
			foreach($orders as $order){
				$taxable = $taxable + $order->getTotalGrossAmount();
				$total = $total + $order->getTotalNetAmount();
				//Yii::log ( CVarDumper::dumpAsString ($total), CLogger::LEVEL_WARNING, '$total' );
			}
		
			Yii::app ()->session ['gross_total']=round($taxable);
			Yii::app ()->session ['gross_total_amt']=round($total);
		} */
		$taxable = 0;
		$total = 0;
		Yii::app ()->session ['gross_total']=round($taxable);
		Yii::app ()->session ['gross_total_amt']=round($total);
		//echo "<pre>"; print_r($criteria);
		$modeldata = new CActiveDataProvider($this, array(
			'criteria' => $criteria,
			'sort'=>array(
					'defaultOrder'=>'id DESC',
			),
		));

		//echo $modeldata->createCommand()->sql;
		//echo $modeldata->createCommand()->getRawSql();
		return $modeldata;
	}
	public function defaultScope() {
		return array ();
	}
	
}