<?php


 
/**
 * This is the model base class for the table "{{credit_note}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CreditNote".
 *
 * Columns in table "{{credit_note}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $credit_number
 * @property double $amt
 * @property double $amt_used
 * @property integer $type_id
 * @property integer $status
 * @property string $create_time
 * @property string $update_time
 *
 */
abstract class BaseCreditNote extends GxActiveRecord {

	public static function getTypeOptions($id = null)
	{
		$list = array("TYPE1","TYPE2","TYPE3");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
 	
	public static function getStatusOptions($id = null)
	{
		$list = array("Draft","Published","Archive");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}	
	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
			if ( !isset( $this->create_time )) $this->create_time = new CDbExpression('NOW()');
			}else{
				}
		return parent::beforeValidate();
	}

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{credit_note}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CreditNote|CreditNotes', $n);
	}

	public static function representingColumn() {
		return 'credit_number';
	}

	public function rules() {
		return array(
			array('credit_number', 'required'),
			array('type_id, status', 'numerical', 'integerOnly'=>true),
			array('amt, amt_used', 'numerical'),
			array('credit_number', 'length', 'max'=>255),
			array('create_time, update_time', 'safe'),
			array('amt, amt_used, type_id, status, create_time, update_time', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, credit_number, amt, amt_used, type_id, status, create_time, update_time', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'credit_number' => Yii::t('app', 'Credit Number'),
			'amt' => Yii::t('app', 'Amt'),
			'amt_used' => Yii::t('app', 'Amt Used'),
			'type_id' => Yii::t('app', 'Type'),
			'status' => Yii::t('app', 'Status'),
			'create_time' => Yii::t('app', 'Create Time'),
			'update_time' => Yii::t('app', 'Update Time'),
		);
	}

	public function search() {
		$start_date = $this->getSessionStartDate();
		$end_date = $this->getSessionEndDate();
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('credit_number', $this->credit_number, true);
		$criteria->compare('amt', $this->amt);
		$criteria->compare('amt_used', $this->amt_used);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('status', $this->status);
		if($start_date != '' && $end_date != ''){
			$criteria->addBetweenCondition('date(create_time)', $start_date, $end_date);
		}
		$criteria->compare('update_time', $this->update_time, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}