<?php


 
/**
 * This is the model base class for the table "{{online_order_item}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "OnlineOrderItem".
 *
 * Columns in table "{{online_order_item}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $name
 * @property integer $qty
 * @property double $price
 * @property double $total
 * @property string $image_url
 * @property integer $type_id
 * @property string $status
 * @property string $create_time
 * @property string $update_time
 * @property integer $create_user_id
 * @property integer $updated_by
 *
 */
abstract class BaseOnlineOrderItem extends GxActiveRecord {

	public static function getTypeOptions($id = null)
	{
		$list = array("TYPE1","TYPE2","TYPE3");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
 	
	public static function getStatusOptions($id = null)
	{
		$list = array("Draft","Published","Archive");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}	
	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
			if ( !isset( $this->create_time )) $this->create_time = new CDbExpression('NOW()');
				if ( !isset( $this->create_user_id )) $this->create_user_id = Yii::app()->user->id;			
	}else{
					}
		return parent::beforeValidate();
	}

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{online_order_item}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'OnlineOrderItem|OnlineOrderItems', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('type_id, create_user_id, updated_by', 'numerical', 'integerOnly'=>true),
			array('price, total', 'numerical'),
			array('name, status', 'length', 'max'=>255),
			array('image_url, create_time, update_time,barcode,product_code', 'safe'),
			array('qty, price, total, image_url, type_id, status, create_time, update_time, create_user_id, updated_by', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, qty, price, total, image_url, type_id, status, create_time, update_time, create_user_id, updated_by', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
				
				
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'qty' => Yii::t('app', 'Qty'),
			'price' => Yii::t('app', 'Price'),
			'total' => Yii::t('app', 'Total'),
			'image_url' => Yii::t('app', 'Image Url'),
			'type_id' => Yii::t('app', 'Type'),
			'status' => Yii::t('app', 'Status'),
			'create_time' => Yii::t('app', 'Create Time'),
			'update_time' => Yii::t('app', 'Update Time'),
			'create_user_id' => Yii::t('app', 'Create User'),
			'updated_by' => Yii::t('app', 'Updated By'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('qty', $this->qty);
		$criteria->compare('price', $this->price);
		$criteria->compare('total', $this->total);
		$criteria->compare('image_url', $this->image_url, true);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('status', $this->status, true);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('update_time', $this->update_time, true);
		$criteria->compare('create_user_id', $this->create_user_id);
		$criteria->compare('updated_by', $this->updated_by);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}