<?php

 
/**
 * This is the model base class for the table "{{advance_logs}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AdvanceLogs".
 *
 * Columns in table "{{advance_logs}}" available as properties of the model,
 * followed by relations of table "{{advance_logs}}" available as properties of the model.
 *
 * @property integer $id
 * @property double $amount
 * @property integer $advance_payment_id
 * @property integer $type_id
 * @property integer $status
 * @property string $create_time
 * @property string $update_time
 *
 * @property AdvancePayment $advancePayment
 */
abstract class BaseAdvanceLogs extends GxActiveRecord {

	const TYPE_ADD = 0;
	const TYPE_SUBSTRACT = 1;
	public static function getTypeOptions($id = null)
	{
		$list = array("Add","Substract");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
 	
	public static function getStatusOptions($id = null)
	{
		$list = array("Draft","Published","Archive");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}	
	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
			if ( !isset( $this->create_time )) $this->create_time = new CDbExpression('NOW()');
			}else{
				}
		return parent::beforeValidate();
	}

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{advance_logs}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AdvanceLogs|AdvanceLogs', $n);
	}

	public static function representingColumn() {
		return 'create_time';
	}

	public function rules() {
		return array(
			array('amount, advance_payment_id', 'required'),
			array('advance_payment_id, type_id, status', 'numerical', 'integerOnly'=>true),
			array('amount', 'numerical'),
			array('create_time, update_time', 'safe'),
			array('type_id, status, create_time, update_time', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, amount, advance_payment_id, type_id, status, create_time, update_time', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'advancePayment' => array(self::BELONGS_TO, 'AdvancePayment', 'advance_payment_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'amount' => Yii::t('app', 'Amount'),
			'advance_payment_id' => null,
			'type_id' => Yii::t('app', 'Type'),
			'status' => Yii::t('app', 'Status'),
			'create_time' => Yii::t('app', 'Create Time'),
			'update_time' => Yii::t('app', 'Update Time'),
			'advancePayment' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('amount', $this->amount);
		$criteria->compare('advance_payment_id', $this->advance_payment_id);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('status', $this->status);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('update_time', $this->update_time, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}