<?php

/**
 * This is the model base class for the table "{{item_detail}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ItemDetail".
 *
 * Columns in table "{{item_detail}}" available as properties of the model,
 * followed by relations of table "{{item_detail}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $item_id
 * @property string $bar_code
 * @property integer $open_stock_qty
 * @property integer $reorder_qty
 * @property integer $status
 * @property integer $type_id
 * @property string $create_time
 * @property integer $tax_id
 * @property integer $create_user_id
 * @property integer $updated_by
 *
 * @property User $createUser
 * @property Item $item
 * @property Tax $tax
 * @property User $updatedBy
 * @property ItemDiscount[] $itemDiscounts
 * @property ItemStock[] $itemStocks
 * @property ItemTax[] $itemTaxes
 * @property ItemVendor[] $itemVendors
 * @property MrnDetail[] $mrnDetails
 * @property MrsDetail[] $mrsDetails
 * @property OrderHoldItem[] $orderHoldItems
 * @property OrderItem[] $orderItems
 * @property OrderRefundItem[] $orderRefundItems
 * @property PurchaseBillDetail[] $purchaseBillDetails
 * @property PurchaseOrderDetail[] $purchaseOrderDetails
 */
abstract class BaseItemDetail extends GxActiveRecord {
	public $item_print_id;
	public $item_qty;
	public $company_id;
	public $company_bar_code;
	public $expiry_date;
	public $packing_date;
	const IS_NOT_COMPANY = 0;
	const IS_COMPANY = 1;
	const STATUS_ACTIVE = 0;
	const STATUS_INACTIVE = 1;
	
	public $hsn_code;
	public $product_code;
	public $mrp;
	public $purchase_price;
	
	public static function getStatusOptions($id = null) {
		$list = array (
				"Active",
				"InActive" 
		);
		if ($id == null)
			return $list;
		if (is_numeric ( $id ))
			return $list [$id];
		return $id;
	}
	public static function getTypeOptions($id = null) {
		$list = array (
				"TYPE1",
				"TYPE2",
				"TYPE3" 
		);
		if ($id == null)
			return $list;
		if (is_numeric ( $id ))
			return $list [$id];
		return $id;
	}
	public function beforeValidate() {
		if ($this->isNewRecord) {
			if (! isset ( $this->create_time ))
				$this->create_time = new CDbExpression ( 'NOW()' );
			if (! isset ( $this->create_user_id ))
				$this->create_user_id = Yii::app ()->user->id;
		} else {
		}
		return parent::beforeValidate ();
	}
	public static function model($className = __CLASS__) {
		return parent::model ( $className );
	}
	public function tableName() {
		return '{{item_detail}}';
	}
	public static function label($n = 1) {
		return Yii::t ( 'app', 'ItemDetail|ItemDetails', $n );
	}
	public static function representingColumn() {
		return 'bar_code';
	}
	public function rules() {
		return array (
				array (
						'bar_code,mrp,open_stock_qty,outlet_id, create_time, create_user_id',
						'required' 
				),
				array (
						'item_id, status,type_id, tax_id, create_user_id, updated_by',
						'numerical',
						'integerOnly' => true 
				),
				array (
						'bar_code',
						'length',
						'max' => 255 
				),
				array (
						'bar_code',
						'unique',
						
				),
				array (
						'company_bar_code,update_time,outlet_id,mrp,company_id,packing_date,expiry_date,company_bar_code,item_qty,item_print_id',
						'safe' 
				),
				array (
						'item_id, status, type_id, tax_id, updated_by',
						'default',
						'setOnEmpty' => true,
						'value' => null 
				),
				array (
						'hsn_code,product_code,purchase_price,mrp,id, item_id, bar_code, open_stock_qty, reorder_qty, status, type_id, create_time, tax_id, create_user_id, updated_by',
						'safe',
						'on' => 'search' 
				) 
		);
	}
	public function relations() {
		return array (
				'createUser' => array (
						self::BELONGS_TO,
						'User',
						'create_user_id' 
				),
				'item' => array (
						self::BELONGS_TO,
						'Item',
						'item_id' 
				),
				'tax' => array (
						self::BELONGS_TO,
						'Tax',
						'tax_id' 
				),
				'updatedBy' => array (
						self::BELONGS_TO,
						'User',
						'updated_by' 
				),
				'itemDiscounts' => array (
						self::HAS_MANY,
						'ItemDiscount',
						'item_detail_id' 
				),
				
				'itemDiscount' => array (
						self::HAS_ONE,
						'ItemDiscount',
						'item_detail_id' 
				),
				
				// An item detail has one stock row per batch; without an order the
				// relation returned an arbitrary one - in practice the highest id,
				// i.e. the most recent batch - so the batch number on an
				// order line was not stable between calls.
				'itemStock' => array (
						self::HAS_ONE,
						'ItemStock',
						'item_detail_id',
						'order' => 'id DESC' 
				),
				'itemStocks' => array (
						self::HAS_MANY,
						'ItemStock',
						'item_detail_id' 
				),
				'itemTaxes' => array (
						self::HAS_MANY,
						'ItemTax',
						'item_detail_id' 
				),
				'itemVendors' => array (
						self::HAS_MANY,
						'ItemVendor',
						'item_detail_id' 
				),
				'mrnDetails' => array (
						self::HAS_MANY,
						'MrnDetail',
						'item_detail_id' 
				),
				'mrsDetails' => array (
						self::HAS_MANY,
						'MrsDetail',
						'item_detail_id' 
				),
				'orderHoldItems' => array (
						self::HAS_MANY,
						'OrderHoldItem',
						'item_detail_id' 
				),
				'orderItems' => array (
						self::HAS_MANY,
						'OrderItem',
						'item_detail_id' 
				),
				'orderRefundItems' => array (
						self::HAS_MANY,
						'OrderRefundItem',
						'item_detail_id' 
				),
				'purchaseBillDetails' => array (
						self::HAS_MANY,
						'PurchaseBillDetail',
						'item_detail_id' 
				),
				'purchaseOrderDetails' => array (
						self::HAS_MANY,
						'PurchaseOrderDetail',
						'item_detail_id' 
				),
				'stockAdjustLogs' => array (
					self::HAS_MANY,
					'StockAdjustLog',
					'item_detail_id',
					// create_time has duplicates here and the caller reads [0]
					'order' => 'create_time DESC, id DESC'
			),
		);
	}
	public function pivotModels() {
		return array ();
	}
	public function attributeLabels() {
		return array (
				'id' => Yii::t ( 'app', 'ID' ),
				'item_id' => Yii::t ( 'app', 'Item' ),
				'company_id' => Yii::t ( 'app', 'Company' ),
				'bar_code' => Yii::t ( 'app', 'Bar Code' ),
				'open_stock_qty' => Yii::t ( 'app', 'Opening Stock' ),
				'reorder_qty' => Yii::t ( 'app', 'Reorder Qty' ),
				'status' => Yii::t ( 'app', 'Status' ),
				'type_id' => Yii::t ( 'app', 'Type' ),
				'mrp' => Yii::t ( 'app', 'MRP' ),
				'create_time' => Yii::t ( 'app', 'Create Time' ),
				'expiry_date' => Yii::t ( 'app', 'Expiry Date' ),
				'packing_date' => Yii::t ( 'app', 'Packing Date' ),
				
				'item_print_id' => Yii::t ( 'app', 'Item' ),
				'item_qty' => Yii::t ( 'app', 'Quantity' ),
				'tax_id' => null,
				'create_user_id' => null,
				'updated_by' => null,
				'createUser' => null,
				'item' => null,
				'tax' => null,
				'updatedBy' => null,
				'itemDiscounts' => null,
				'itemStocks' => null,
				'itemTaxes' => null,
				'itemVendors' => null,
				'mrnDetails' => null,
				'mrsDetails' => null,
				'orderHoldItems' => null,
				'orderItems' => null,
				'orderRefundItems' => null,
				'purchaseBillDetails' => null,
				'purchaseOrderDetails' => null,
				'stockAdjustLogs' => null,
		);
	}
	public function adminsearch() {
		$item_ids = array ();
		$criteria = new CDbCriteria ();
		$item_list_ids = array ();
	
		$match_purchase_price = null;
		$match_mrp = null;
		$match_item_id = null;
		$match_hsn_code = null;
		$match_product_code = null;
	
		if ($this->item_id != null) {
			Yii::log ( CVarDumper::dumpAsString ( $this->item_id ), CLogger::LEVEL_WARNING, '$this->item_id' );
				$criteria2 = new CDbCriteria();
					
				$criteria2->condition = "title LIKE :title";
				$criteria2->params = array (
				':title' => trim (  $this->item_id ) . '%'
				);
					
				//$criteria2->compare ( 'title', $this->item_id );
				$getitem = Item::model()->find($criteria2);
				if($getitem){
				$criteria1 = new CDbCriteria();
				$criteria1->order = 'id asc';
				$criteria1->addCondition('item_id ='.$getitem->id);
				$itemDetail = ItemDetail::model()->find($criteria1);
				if($itemDetail){
				$criteria->addCondition ( 'id !='. $itemDetail->id );
				}
				} 
			$match_item_id = $this->item_id;
			Yii::log ( CVarDumper::dumpAsString ( $match_item_id ), CLogger::LEVEL_WARNING, '$match_item_id' );
		}
		if ($this->mrp != null) {
			$match_mrp = $this->mrp;
		}
	
		if ($this->purchase_price != null) {
			$match_purchase_price = $this->purchase_price;
		}
		if ($this->hsn_code != null) {
			$match_hsn_code = $this->hsn_code;
		}
	
		if ($this->product_code != null) {
			$match_product_code = $this->product_code;
		}
		if ($this->company_id != null) {
			$match_company_id = $this->company_id;
		}else{
			$match_company_id = null;
		}
	
	
		$is_vendor = 0;
		$criteria->order = 't.id desc';
		$criteria->compare ( 'id', $this->id );
	
		$role = UserRole::model ()->findByAttributes ( array (
				'title' => 'Vendor'
		) );
		$user = Yii::app ()->user->model;
		if ($user->role_id == $role->id) {
			$is_vendor = 1;
		}
	
		if($match_item_id != null || $match_mrp !=null ||$match_hsn_code !=null || $match_product_code != null ||
				$match_purchase_price != null || $match_company_id !=null || $is_vendor == 1	)
		{
			$item_ids = $this->getItemOptionIdsInBarcode ($match_item_id ,$match_mrp,$match_hsn_code,$match_product_code,
					$match_purchase_price,$match_company_id,$is_vendor);
			$criteria->addInCondition ( 'item_id', $item_ids );
		}
			
	
		$criteria->compare ( 'bar_code', $this->bar_code, true );
		$criteria->compare ( 'open_stock_qty', $this->open_stock_qty );
		//$criteria->compare ( 'mrp', $this->mrp );
		$criteria->compare ( 'reorder_qty', $this->reorder_qty );
		$criteria->compare ( 'status', $this->status );
		$criteria->compare ( 'type_id', $this->type_id );
		$criteria->compare ( 'create_time', $this->create_time, true );
		$criteria->compare ( 'tax_id', $this->tax_id );
		$criteria->compare ( 'create_user_id', $this->create_user_id );
		$criteria->compare ( 'updated_by', $this->updated_by );
	
		return new CActiveDataProvider ( $this, array (
				'criteria' => $criteria,
				'sort'=>array(
						'defaultOrder'=>'id DESC',
				),
				'pagination' => array (
						'pageSize' => 10
				)
		) );
	}
	public function search() {
		$item_ids = array ();
		$criteria = new CDbCriteria ();
		$item_list_ids = array ();
		
		$match_purchase_price = null;
		$match_mrp = null;
		$match_item_id = null;
		$match_hsn_code = null;
		$match_product_code = null;
		
		if ($this->item_id != null) {
			/* Yii::log ( CVarDumper::dumpAsString ( $this->item_id ), CLogger::LEVEL_WARNING, '$this->item_id' );
			$criteria2 = new CDbCriteria();
			
				$criteria2->condition = "title LIKE :title";
				$criteria2->params = array (
						':title' => trim (  $this->item_id ) . '%'
				);
			
			//$criteria2->compare ( 'title', $this->item_id );
			$getitem = Item::model()->find($criteria2);
			if($getitem){
			$criteria1 = new CDbCriteria();
			$criteria1->order = 'id asc';
			$criteria1->addCondition('item_id ='.$getitem->id);
			$itemDetail = ItemDetail::model()->find($criteria1);
			if($itemDetail){
				$criteria->addCondition ( 'id !='. $itemDetail->id );
			}
			} */
			$match_item_id = $this->item_id;
			Yii::log ( CVarDumper::dumpAsString ( $match_item_id ), CLogger::LEVEL_WARNING, '$match_item_id' );
		}
		if ($this->mrp != null) {
			$match_mrp = $this->mrp;
		}
		
		if ($this->purchase_price != null) {
			$match_purchase_price = $this->purchase_price;
		}
		if ($this->hsn_code != null) {
			$match_hsn_code = $this->hsn_code;
		}
		
		if ($this->product_code != null) {
			$match_product_code = $this->product_code;
		}
		if ($this->company_id != null) {
			$match_company_id = $this->company_id;
		}else{
			$match_company_id = null;
		}
		
		
		$is_vendor = 0;
		$criteria->order = 't.id desc';
		$criteria->compare ( 'id', $this->id );
		
		$role = UserRole::model ()->findByAttributes ( array (
				'title' => 'Vendor' 
		) );
		$user = Yii::app ()->user->model;
		if ($user->role_id == $role->id) {
			$is_vendor = 1;
		} 
		
		if($match_item_id != null || $match_mrp !=null ||$match_hsn_code !=null || $match_product_code != null ||
				$match_purchase_price != null || $match_company_id !=null || $is_vendor == 1	)
		{
		$item_ids = $this->getItemOptionIdsInBarcode ($match_item_id ,$match_mrp,$match_hsn_code,$match_product_code,
				$match_purchase_price,$match_company_id,$is_vendor);
		$criteria->addInCondition ( 'item_id', $item_ids );
		}
			
	
		$criteria->compare ( 'bar_code', $this->bar_code, true );
		$criteria->compare ( 'open_stock_qty', $this->open_stock_qty );
		//$criteria->compare ( 'mrp', $this->mrp );
		$criteria->compare ( 'reorder_qty', $this->reorder_qty );
		$criteria->compare ( 'status', $this->status );
		$criteria->compare ( 'type_id', $this->type_id );
		$criteria->compare ( 'create_time', $this->create_time, true );
		$criteria->compare ( 'tax_id', $this->tax_id );
		$criteria->compare ( 'create_user_id', $this->create_user_id );
		$criteria->compare ( 'updated_by', $this->updated_by );
		
		return new CActiveDataProvider ( $this, array (
				'criteria' => $criteria,
				'sort'=>array(
						'defaultOrder'=>'id DESC',
				),
				'pagination' => array (
						'pageSize' => 10 
				) 
		) );
	}
	public static function getItemBarcode($valueArray) {
		$elementId = $valueArray ['itemId'] . "_bcode"; /* the div element id */
		$value = $valueArray ['barocde'];
		$type = 'code128'; /* you can set the type dynamically if you want valueArray eg - $valueArray['type'] */
		
		self::getBarcode ( array (
				'elementId' => $elementId,
				'value' => $value,
				'type' => $type 
		) );
		return CHtml::tag ( 'div', array (
				'id' => $elementId 
		) );
	}
	
	/**
	 * This function returns the item barcode
	 */
	public static function getBarcode($optionsArray) {
		Yii::app ()->getController ()->widget ( 'application.extensions.Yii-Barcode-Generator.Barcode', $optionsArray );
	}
	
	public function defaultScope()
	{
		return array();
	}
}