<?php


 
/**
 * This is the model base class for the table "{{bill}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Bill".
 *
 * Columns in table "{{bill}}" available as properties of the model,
 * followed by relations of table "{{bill}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $bill_no
 * @property string $image_file1
 * @property string $image_file2
 * @property string $image_file3
 * @property integer $type_id
 * @property integer $status
 * @property string $create_time
 * @property integer $create_user_id
 * @property integer $po_id
 *
 * @property User $createUser
 * @property PurchaseOrder $po
 */
abstract class BaseBill extends GxActiveRecord {

	public static function getTypeOptions($id = null)
	{
		$list = array("TYPE1","TYPE2","TYPE3");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
 	
	public static function getStatusOptions($id = null)
	{
		$list = array("Draft","Published","Archive");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}	
	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
			if ( !isset( $this->create_time )) $this->create_time = new CDbExpression('NOW()');
			if ( !isset( $this->create_user_id )) $this->create_user_id = Yii::app()->user->id;			
	}else{
				}
		return parent::beforeValidate();
	}

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{bill}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Bill|Bills', $n);
	}

	public static function representingColumn() {
		return 'bill_no';
	}

	public function rules() {
		return array(
			array('bill_no, image_file1, po_id', 'required'),
			array('type_id, status, create_user_id, po_id', 'numerical', 'integerOnly'=>true),
			array('bill_no', 'length', 'max'=>255),
			array('image_file2, image_file3, create_time', 'safe'),
			array('image_file2, image_file3, type_id, status, create_time, create_user_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, bill_no, image_file1, image_file2, image_file3, type_id, status, create_time, create_user_id, po_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'createUser' => array(self::BELONGS_TO, 'User', 'create_user_id'),
			'po' => array(self::BELONGS_TO, 'PurchaseOrder', 'po_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'bill_no' => Yii::t('app', 'Bill No'),
			'image_file1' => Yii::t('app', 'Image File1'),
			'image_file2' => Yii::t('app', 'Image File2'),
			'image_file3' => Yii::t('app', 'Image File3'),
			'type_id' => Yii::t('app', 'Type'),
			'status' => Yii::t('app', 'Status'),
			'create_time' => Yii::t('app', 'Create Time'),
			'create_user_id' => null,
			'po_id' => null,
			'createUser' => null,
			'po' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;
		$user = Yii::app ()->user->model;
		if ($user->role_id == 6) {
			$criteria->compare('create_user_id', $user->id);
		}else{
			$criteria->compare('create_user_id', $this->create_user_id);
		}
		$criteria->compare('id', $this->id);
		$criteria->compare('bill_no', $this->bill_no, true);
		$criteria->compare('image_file1', $this->image_file1, true);
		$criteria->compare('image_file2', $this->image_file2, true);
		$criteria->compare('image_file3', $this->image_file3, true);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('status', $this->status);
		$criteria->compare('create_time', $this->create_time, true);
	
		$criteria->compare('po_id', $this->po_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}