<?php


/**
 * This is the model base class for the table "{{emp}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Emp".
 *
 * Columns in table "{{emp}}" available as properties of the model,
 * followed by relations of table "{{emp}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $code
 * @property string $name
 * @property string $email
 * @property integer $contact_no
 * @property integer $gender_id
 * @property string $date_of_birth
 * @property string $date_of_joining
 * @property string $permanent_address
 * @property string $temp_address
 * @property integer $status
 * @property integer $type_id
 * @property string $create_time
 * @property integer $designation_id
 * @property integer $create_user_id
 * @property integer $updated_by
 *
 * @property User $createUser
 * @property Designation $designation
 * @property User $updatedBy
 * @property EmpShift[] $empShifts
 * @property User[] $users
 */
abstract class BaseEmp extends GxActiveRecord {
	public $shift_id;
	public $username;
	public $password;
	const STATUS_ACTIVE = 0;
	const STATUS_INACTIVE = 1;
	const GENDER_MALE = 0;
	const GENDER_FEMALE = 1;
	
	const ROLE_BILLING = 0;
	const ROLE_GRN = 1;
	//const GENDER_BOTH = 2;
	public static function getStatusOptions($id = null) {
		$list = array (
				"Active",
				"InActive" 
		);
		if ($id == null)
			return $list;
		if (is_numeric ( $id ))
			return $list [$id];
		return $id;
	}
	public static function getTypeOptions($id = null) {
		$list = array (
				"TYPE1",
				"TYPE2",
				"TYPE3" 
		);
		if ($id == null)
			return $list;
		if (is_numeric ( $id ))
			return $list [$id];
		return $id;
	}
	public static function getGenderOptions($id = null) {
		$list = array (
				self::GENDER_MALE => 'Male',
				self::GENDER_FEMALE => 'Female',
			//	self::GENDER_BOTH => 'Both' 
		);
		if ($id == null)
			return $list;
		if (is_numeric ( $id ))
			return $list [$id];
		return $id;
	}
	public static function getRoleOptions($id = null) {
		$list = array (
				self::ROLE_BILLING => 'Billing',
				self::ROLE_GRN => 'GRN Receiving',
				//	self::GENDER_BOTH => 'Both'
		);
		if ($id == null)
			return $list;
			if (is_numeric ( $id ))
				return $list [$id];
				return $id;
	}
	public function beforeValidate() {
		if ($this->isNewRecord) {
			if (! isset ( $this->create_time ))
				$this->create_time = new CDbExpression ( 'NOW()' );
			if (! isset ( $this->create_user_id ))
				$this->create_user_id = Yii::app ()->user->id;
		} else {
		}
		return parent::beforeValidate ();
	}
	public static function model($className = __CLASS__) {
		return parent::model ( $className );
	}
	public function tableName() {
		return '{{emp}}';
	}
	public static function label($n = 1) {
		return Yii::t ( 'app', 'Emp|Emps', $n );
	}
	public static function representingColumn() {
		return 'name';
	}
	public function rules() {
		return array (
				array (
						'code,name, email,username,contact_no,role_id,country_id,city_id,state_id,gender_id,shift_id,date_of_birth, date_of_joining, permanent_address, create_time, designation_id, create_user_id',
						'required' 
				),
				array (
						'password',
						'required',
						'on' => 'create' 
				), // , contact_no
				array (
						'code, contact_no, gender_id, status, type_id, designation_id, create_user_id, updated_by',
						'numerical',
						'integerOnly' => true 
				),
				array (
						'name, email',
						'length',
						'max' => 255 
				),
				array (
						'email',
						'email' 
				),
				array (
						'email',
						'unique' 
				),
				array (
						'outlet_id,temp_address,shift_id,city_id,role_id,state_id,country_id,temp_city_id,temp_state_id,temp_country_id,username,password',
						'safe' 
				),
				array (
						'code, temp_address, status, type_id, updated_by',
						'default',
						'setOnEmpty' => true,
						'value' => null 
				),
				array (
						'id, code, name, email, contact_no, gender_id, date_of_birth, date_of_joining, permanent_address, temp_address, status, type_id, create_time, designation_id, create_user_id, updated_by',
						'safe',
						'on' => 'search' 
				) 
		);
	}
	public function relations() {
		return array (
				'createUser' => array (
						self::BELONGS_TO,
						'User',
						'create_user_id' 
				),
				'designation' => array (
						self::BELONGS_TO,
						'Designation',
						'designation_id' 
				),
				'updatedBy' => array (
						self::BELONGS_TO,
						'User',
						'updated_by' 
				),
				'empShifts' => array (
						self::HAS_MANY,
						'EmpShift',
						'emp_id' 
				),
				'users' => array (
						self::HAS_MANY,
						'User',
						'emp_id' 
				),
				'city' => array (
						self::BELONGS_TO,
						'City',
						'city_id' 
				),
				'state' => array (
						self::BELONGS_TO,
						'State',
						'state_id' 
				),
				'country' => array (
						self::BELONGS_TO,
						'Country',
						'country_id' 
				),
				'tempcity' => array (
						self::BELONGS_TO,
						'City',
						'temp_city_id' 
				),
				'tempstate' => array (
						self::BELONGS_TO,
						'State',
						'temp_state_id' 
				),
				'tempcountry' => array (
						self::BELONGS_TO,
						'Country',
						'temp_country_id' 
				),
				'outlet' => array (
						self::BELONGS_TO,
						'Outlet',
						'outlet_id'
				)
		);
	}
	public function pivotModels() {
		return array ();
	}
	public function attributeLabels() {
		return array (
				'id' => Yii::t ( 'app', 'ID' ),
				'code' => Yii::t ( 'app', 'Code' ),
				'name' => Yii::t ( 'app', 'Name' ),
				'email' => Yii::t ( 'app', 'Email' ),
				'contact_no' => Yii::t ( 'app', 'Contact No' ),
				'gender_id' => Yii::t ( 'app', 'Gender' ),
				'date_of_birth' => Yii::t ( 'app', 'Date Of Birth' ),
				'role_id' => Yii::t ( 'app', 'Role' ),
				'date_of_joining' => Yii::t ( 'app', 'Date Of Joining' ),
				'permanent_address' => Yii::t ( 'app', 'Permanent Address' ),
				'shift_id' => Yii::t ( 'app', 'Shift' ),
				'city_id' => Yii::t ( 'app', 'City' ),
				'state_id' => Yii::t ( 'app', 'State' ),
				'country_id' => Yii::t ( 'app', 'Country' ),
				'temp_city_id' => Yii::t ( 'app', 'City' ),
				'temp_state_id' => Yii::t ( 'app', 'State' ),
				'temp_country_id' => Yii::t ( 'app', 'Country' ),
				'temp_address' => Yii::t ( 'app', 'Temp Address' ),
				'status' => Yii::t ( 'app', 'Status' ),
				'type_id' => Yii::t ( 'app', 'Type' ),
				'create_time' => Yii::t ( 'app', 'Create Time' ),
				'designation_id' => null,
				'create_user_id' => null,
				'updated_by' => null,
				'outlet_id' => Yii::t ( 'app', 'Outlet' ),
				'createUser' => Yii::t ( 'app', 'Created By' ),
				'updatedBy' => Yii::t ( 'app', 'Updated By' ),
				'designation' => null,
				
				'empShifts' => null,
				'users' => null 
		);
	}
	public function search() {
		$criteria = new CDbCriteria ();
		
		$criteria->compare ( 'id', $this->id );
		$criteria->compare ( 'code', $this->code );
		$criteria->compare ( 'name', $this->name, true );
		$criteria->compare ( 'email', $this->email, true );
		$criteria->compare ( 'contact_no', $this->contact_no );
		$criteria->compare ( 'gender_id', $this->gender_id );
		$criteria->compare ( 'date_of_birth', $this->date_of_birth, true );
		$criteria->compare ( 'date_of_joining', $this->date_of_joining, true );
		$criteria->compare ( 'permanent_address', $this->permanent_address, true );
		$criteria->compare ( 'temp_address', $this->temp_address, true );
		$criteria->compare ( 'status', $this->status );
		$criteria->compare ( 'type_id', $this->type_id );
		$criteria->compare ( 'create_time', $this->create_time, true );
		$criteria->compare ( 'designation_id', $this->designation_id );
		$criteria->compare ( 'create_user_id', $this->create_user_id );
		$criteria->compare ( 'updated_by', $this->updated_by );
		
		return new CActiveDataProvider ( $this, array (
				'criteria' => $criteria 
		) );
	}
}