<?php


 
/**
 * This is the model base class for the table "{{vendor}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Vendor".
 *
 * Columns in table "{{vendor}}" available as properties of the model,
 * followed by relations of table "{{vendor}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property string $contact_person
 * @property string $person_designation
 * @property integer $contact_no
 * @property integer $secondary_contact_no
 * @property integer $whatsapp_no
 * @property string $primary_address
 * @property string $secondary_address
 * @property string $tax_no
 * @property integer $is_local_vendor
 * @property integer $status
 * @property integer $type_id
 * @property string $create_time
 * @property integer $city_id
 * @property integer $state_id
 * @property integer $country_id
 * @property integer $outlet_id
 * @property integer $create_user_id
 * @property integer $updated_by
 *
 * @property ItemVendor[] $itemVendors
 * @property PurchaseBill[] $purchaseBills
 * @property PurchaseOrder[] $purchaseOrders
 * @property City $city
 * @property Country $country
 * @property User $createUser
 * @property Outlet $outlet
 * @property State $state
 * @property User $updatedBy
 */
abstract class BaseVendor extends GxActiveRecord {
  public $columns;
  public $start_date;
  public $end_date;
	const STATUS_ACTIVE = 0;
	const STATUS_INACTIVE = 1;
	const ADVANCE_PAYMENT = 1;
	const IS_CASH = 1;
	public $is_cash;
	public static function getStatusOptions($id = null)
	{
		$list = array("Active","InActive");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}	
	public static function getTypeOptions($id = null)
	{
		$list = array("TYPE1","TYPE2","TYPE3");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
	public static function getLocalVendorOptions($id = null)
	{
		$list = array("No","Yes");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
	
	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
			if ( !isset( $this->create_time )) $this->create_time = new CDbExpression('NOW()');
			if ( !isset( $this->create_user_id )) $this->create_user_id = Yii::app()->user->id;			
	}else{
				}
		return parent::beforeValidate();
	}

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{vendor}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Vendor|Vendors', $n);
	}

	public static function representingColumn() {
		return 'name';
	}
	
	public static function getAllItems($id = null) {
		$item_arr = array ();
		$exist = [];
		if($id != null){
			$criteria1 = new CDbCriteria ();
			$criteria1->addCondition ( 'vendor_id =' . $id );
			$itemvendors = ItemVendor::model ()->findAll ( $criteria1 );
			if($itemvendors){
				foreach($itemvendors as $itemvendor){
					$exist[] = $itemvendor->item_detail_id;
				}
			}
		}
		$criteria = new CDbCriteria ();
		$criteria->addNotInCondition('id', $exist);
		$criteria->addCondition ( 'status =' . Item::STATUS_ACTIVE );
		$items = Item::model ()->findAll ( $criteria );
		if ($items != null) {
			foreach ( $items as $item ) {
				$item_arr [$item->id] = $item->title;
			}
		}
	
		return $item_arr;
	}

	public function rules() {
		return array(
			array('name,primary_address,create_time,city_id, state_id, country_id, outlet_id, create_user_id', 'required'),
			array('is_local_vendor,payment_days, status, type_id, city_id, state_id, country_id, create_user_id, updated_by', 'numerical', 'integerOnly'=>true),
			array('name, contact_person, person_designation, tax_no', 'length', 'max'=>255),
			array('description, contact_no,person_designation,secondary_address, opening_balance, payment_days,bank_name,acc_no,ifsc,is_advance_payment,is_cash,columns,start_date,end_date,vendor,amount,purchase_amount,contact_email,parent_id', 'safe'),
			array('description, secondary_contact_no, secondary_address, tax_no, is_local_vendor, status, type_id, updated_by', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, description, contact_person, person_designation, contact_no, secondary_contact_no, primary_address, secondary_address, tax_no, is_local_vendor, status, type_id, create_time, city_id, state_id, country_id, outlet_id, create_user_id, updated_by,is_cash', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'itemVendors' => array(self::HAS_MANY, 'ItemVendor', 'vendor_id'),
			'purchaseBills' => array(self::HAS_MANY, 'PurchaseBill', 'vendor_id'),
			'purchaseOrders' => array(self::HAS_MANY, 'PurchaseOrder', 'vendor_id'),
			'city' => array(self::BELONGS_TO, 'City', 'city_id'),
			'country' => array(self::BELONGS_TO, 'Country', 'country_id'),
			'createUser' => array(self::BELONGS_TO, 'User', 'create_user_id'),
			'outlet' => array(self::BELONGS_TO, 'Outlet', 'outlet_id'),
			'parentvendor' => array(self::BELONGS_TO, 'Vendor', 'parent_id'),
			'state' => array(self::BELONGS_TO, 'State', 'state_id'),
			'updatedBy' => array(self::BELONGS_TO, 'User', 'updated_by'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'description' => Yii::t('app', 'Remarks'),
			'contact_person' => Yii::t('app', 'Contact Person'),
			'person_designation' => Yii::t('app', 'Person Designation'),
			'contact_no' => Yii::t('app', 'Contact No'),
			'secondary_contact_no' => Yii::t('app', 'Office Contact No'),
			'whatsapp_no' => Yii::t('app', 'WhatsApp No'),
			'primary_address' => Yii::t('app', 'Primary Address'),
			'secondary_address' => Yii::t('app', 'Secondary Address'),
			'tax_no' => Yii::t('app', 'Tax No'),
			'is_local_vendor' => Yii::t('app', 'Is Local Vendor'),
				'is_cash' => Yii::t('app', 'Is Cash'),
			'status' => Yii::t('app', 'Status'),
			'type_id' => Yii::t('app', 'Type'),
			'create_time' => Yii::t('app', 'Create Time'),
			'city_id' => Yii::t('app', 'City'),
			'state_id' => Yii::t('app', 'State'),
			'parent_id' => Yii::t('app', 'Parent Vendor'),
				'acc_no' => Yii::t('app', 'Account Number'),
			'country_id' => Yii::t('app', 'Country'),
			'outlet_id' => null,
			'create_user_id' => null,
			'updated_by' => null,
			'itemVendors' => null,
			'purchaseBills' => null,
			'purchaseOrders' => null,
			'city' => null,
			'country' => null,
			'createUser' => null,
			'outlet' => null,
			'state' => null,
			'updatedBy' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('contact_person', $this->contact_person, true);
		$criteria->compare('person_designation', $this->person_designation, true);
		$criteria->compare('contact_no', $this->contact_no);
		$criteria->compare('secondary_contact_no', $this->secondary_contact_no);
		$criteria->compare('primary_address', $this->primary_address, true);
		$criteria->compare('secondary_address', $this->secondary_address, true);
		$criteria->compare('tax_no', $this->tax_no, true);
		$criteria->compare('is_local_vendor', $this->is_local_vendor);
		$criteria->compare('status', $this->status);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('city_id', $this->city_id);
		$criteria->compare('state_id', $this->state_id);
		$criteria->compare('country_id', $this->country_id);
		$criteria->compare('outlet_id', $this->outlet_id);
		$criteria->compare('create_user_id', $this->create_user_id);
		$criteria->compare('updated_by', $this->updated_by);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}