<?php


 
/**
 * This is the model base class for the table "{{mrs_adjust}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MrsAdjust".
 *
 * Columns in table "{{mrs_adjust}}" available as properties of the model,
 * followed by relations of table "{{mrs_adjust}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $item_id
 * @property integer $item_detail_id
 * @property integer $mrs_detail_id
 * @property string $qty
 * @property integer $type_id
 * @property integer $status
 * @property string $create_time
 *
 * @property ItemDetail $itemDetail
 * @property Item $item
 */
abstract class BaseMrsAdjust extends GxActiveRecord {
	const STATUS_PENDING = 0;
	const STATUS_DONE = 1;

	public static function getTypeOptions($id = null)
	{
		$list = array("TYPE1","TYPE2","TYPE3");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
 	
	public static function getStatusOptions($id = null)
	{
		$list = array("Pending","Done");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}	
	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
			if ( !isset( $this->create_time )) $this->create_time = new CDbExpression('NOW()');
		}else{
			}
		return parent::beforeValidate();
	}

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{mrs_adjust}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MrsAdjust|MrsAdjusts', $n);
	}

	public static function representingColumn() {
		return 'qty';
	}

	public function rules() {
		return array(
			array('item_id, item_detail_id, mrs_detail_id, qty', 'required'),
			array('item_id, item_detail_id, mrs_detail_id, type_id, status', 'numerical', 'integerOnly'=>true),
			array('qty', 'length', 'max'=>10),
			array('create_time', 'safe'),
			array('type_id, status, create_time', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, item_id, item_detail_id, mrs_detail_id, qty, type_id, status, create_time', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'itemDetail' => array(self::BELONGS_TO, 'ItemDetail', 'item_detail_id'),
			'item' => array(self::BELONGS_TO, 'Item', 'item_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'item_id' => null,
			'item_detail_id' => null,
			'mrs_detail_id' => Yii::t('app', 'Mrs Detail'),
			'qty' => Yii::t('app', 'Qty'),
			'type_id' => Yii::t('app', 'Type'),
			'status' => Yii::t('app', 'Status'),
			'create_time' => Yii::t('app', 'Create Time'),
			'itemDetail' => null,
			'item' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('item_id', $this->item_id);
		$criteria->compare('item_detail_id', $this->item_detail_id);
		$criteria->compare('mrs_detail_id', $this->mrs_detail_id);
		$criteria->compare('qty', $this->qty, true);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('status', $this->status);
		$criteria->compare('create_time', $this->create_time, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}