<?php

 
/**
 * This is the model base class for the table "{{customer}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Customer".
 *
 * Columns in table "{{customer}}" available as properties of the model,
 * followed by relations of table "{{customer}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $email
 * @property string $fax
 * @property string $address
 * @property integer $city_id
 * @property integer $state_id
 * @property integer $country_id
 * @property integer $zip_code
 * @property double $opening_balance
 * @property integer $credit_limit
 * @property integer $payment_days
 * @property integer $contact_no
 * @property integer $status
 * @property integer $type_id
 * @property string $create_time
 * @property string $update_time
 * @property integer $create_user_id
 * @property integer $updated_by
 * @property integer $is_enable_wa
 * 
 *
 * @property User $createUser
 * @property User $updatedBy
 * @property Order[] $orders
 * @property OrderHold[] $orderHolds
 * @property OrderRefund[] $orderRefunds
 */
abstract class BaseCustomer extends GxActiveRecord {

	public $columns;
	public $subject;
	public $message;
	public $attach_file;
	const Is_Email_pending = 0;
	const Is_Email_sent = 1;
	public static function getStatusOptions($id = null)
	{
		$list = array("Active","Inactive");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}	

	public function defaultScope()
  {
      return [
          // 'order' => 't.id DESC',
      ];
  }
	
	public static function getTypeOptions($id = null)
	{
		$list = array("TYPE1","TYPE2","TYPE3");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
 	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
			if ( !isset( $this->create_time )) $this->create_time = date('Y-m-d H:i:s');
				if ( !isset( $this->create_user_id )) $this->create_user_id = Yii::app()->user->id;			
	}else{
					}
		return parent::beforeValidate();
	}

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{customer}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Customer|Customers', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name,contact_no', 'required'),
			array('city_id, state_id, country_id, credit_limit, payment_days, status, type_id, create_user_id, updated_by, is_enable_wa', 'numerical', 'integerOnly'=>true),
			array('opening_balance', 'numerical'),
			array('email', 'email'),
			array('email', 'unique'),
			array('name, email, fax', 'length', 'max'=>255),
			array('create_time, update_time,columns,subject,message,attach_file,is_email,email_date', 'safe'),
			array('email, contact_no, status, type_id,city_id,create_time, update_time, updated_by', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, email, fax, address,city_id, state_id, country_id, zip_code, opening_balance, credit_limit, payment_days, contact_no, status, type_id, create_time, update_time, create_user_id, updated_by, is_enable_wa', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'createUser' => array(self::BELONGS_TO, 'User', 'create_user_id'),
			'updatedBy' => array(self::BELONGS_TO, 'User', 'updated_by'),
			'city' => array(self::BELONGS_TO, 'City', 'city_id'),
			'state' => array(self::BELONGS_TO, 'State', 'state_id'),
			'country' => array(self::BELONGS_TO, 'Country', 'country_id'),
			'orders' => array(self::HAS_MANY, 'Order', 'customer_id'),
			'customerorders' => array(self::HAS_MANY, 'Order', 'customer_id'),
			'orderHolds' => array(self::HAS_MANY, 'OrderHold', 'customer_id'),
			'orderRefunds' => array(self::HAS_MANY, 'OrderRefund', 'customer_id'),
			'customerLoyalty' => array(self::HAS_ONE, 'CustomerLoyalty', 'customer_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'email' => Yii::t('app', 'Email'),
			'fax' => Yii::t('app', 'Fax'),
			'address' => Yii::t('app', 'Address'),
			'city_id' => Yii::t('app', 'City'),
			'state_id' => Yii::t('app', 'State'),
			'country_id' => Yii::t('app', 'Country'),
				'subject' => Yii::t('app', 'Subject'),
				'message' => Yii::t('app', 'Message'),
				'attach_file' => Yii::t('app', 'Attachment'),
			'zip_code' => Yii::t('app', 'Zip Code'),
			'opening_balance' => Yii::t('app', 'Opening Balance'),
			'credit_limit' => Yii::t('app', 'Credit Limit'),
			'payment_days' => Yii::t('app', 'Payment Days'),
			'contact_no' => Yii::t('app', 'Contact No'),
			'status' => Yii::t('app', 'Status'),
			'type_id' => Yii::t('app', 'Type'),
			'create_time' => Yii::t('app', 'Create Time'),
			'update_time' => Yii::t('app', 'Update Time'),
			'create_user_id' => null,
			'updated_by' => null,
			'createUser' => null,
			'updatedBy' => null,
			'orders' => null,
			'orderHolds' => null,
			'orderRefunds' => null,
			'is_enable_wa' => Yii::t('app', 'Is Enable WA'),  
			
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('fax', $this->fax, true);
		$criteria->compare('address', $this->address, true);
		$criteria->compare('city_id', $this->city_id);
		
		$criteria->compare('state_id', $this->state_id);
		$criteria->compare('country_id', $this->country_id);
		$criteria->compare('zip_code', $this->zip_code);
		$criteria->compare('opening_balance', $this->opening_balance);
		$criteria->compare('credit_limit', $this->credit_limit);
		$criteria->compare('payment_days', $this->payment_days);
		$criteria->compare('contact_no', $this->contact_no);
		$criteria->compare('status', $this->status);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('update_time', $this->update_time, true);
		$criteria->compare('create_user_id', $this->create_user_id);
		$criteria->compare('updated_by', $this->updated_by);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}

	public function generateOtp()
    {
        return CustomerOtpVerification::generateOtp($this->id);
    }

	public function verifyOtp($otp)
    {
        return CustomerOtpVerification::verifyOtp($this->id,$otp);
    }
}