<?php

 
/**
 * This is the model base class for the table "{{mrs}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Mrs".
 *
 * Columns in table "{{mrs}}" available as properties of the model,
 * followed by relations of table "{{mrs}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $code
 * @property string $mrs_date
 * @property string $mrs_update_date
 * @property string $mrs_req_date
 * @property integer $status
 * @property integer $type_id
 * @property string $remarks
 * @property string $create_time
 * @property string $update_time
 * @property integer $create_user_id
 * @property integer $updated_by
 * @property integer $outlet_id
 * @property integer $organization_id
 *
 * @property Mrn[] $mrns
 * @property User $createUser
 * @property Organization $organization
 * @property Outlet $outlet
 * @property User $updatedBy
 * @property MrsDetail[] $mrsDetails
 */
abstract class BaseMrs extends GxActiveRecord {

	public $item_id;
	const STATUS_PENDING = 0;
	const STATUS_HALF_DONE = 2;
	const STATUS_DONE = 1;
	const STATUS_REJECT = 3;
	public static function getStatusOptions($id = null)
	{
		$list = array("Pending","Half Done","Done","Reject");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
	public static function getTypeOptions($id = null)
	{
		$list = array("TYPE1","TYPE2","TYPE3");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
 	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
			if ( !isset( $this->create_time )) $this->create_time = date('Y-m-d H:i:s');
				if ( !isset( $this->create_user_id )) $this->create_user_id = Yii::app()->user->id;			
	}else{
		if ( !isset( $this->update_time )) $this->update_time = date('Y-m-d H:i:s');
		if ( !isset( $this->mrs_update_date )) $this->mrs_update_date = date('Y-m-d');
		if ( !isset( $this->updated_by )) $this->updated_by = Yii::app()->user->id;
					}
		return parent::beforeValidate();
	}

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{mrs}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Mrs|Mrs', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('code, mrs_date, mrs_req_date, outlet_id, organization_id', 'required'),
			array('status, type_id, create_user_id, updated_by, outlet_id, organization_id', 'numerical', 'integerOnly'=>true),
			array('code', 'length', 'max'=>255),
			array('mrs_update_date, remarks, create_time, update_time,vendor_id,item_id', 'safe'),
			array('mrs_update_date, status, type_id, remarks, create_time, update_time, updated_by', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, code, mrs_date, mrs_update_date, mrs_req_date, status, type_id, remarks, create_time, update_time, create_user_id, updated_by, outlet_id, organization_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'mrns' => array(self::HAS_MANY, 'Mrn', 'mrs_id'),
			'createUser' => array(self::BELONGS_TO, 'User', 'create_user_id'),
			'organization' => array(self::BELONGS_TO, 'Organization', 'organization_id'),
			'outlet' => array(self::BELONGS_TO, 'Outlet', 'outlet_id'),
			'updatedBy' => array(self::BELONGS_TO, 'User', 'updated_by'),
			'vendor' => array(self::BELONGS_TO, 'Vendor', 'vendor_id'),
			'mrsDetails' => array(self::HAS_MANY, 'MrsDetail', 'mrs_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'code' => Yii::t('app', 'Code'),
			'mrs_date' => Yii::t('app', 'Mrs Date'),
			'mrs_update_date' => Yii::t('app', 'Mrs Update Date'),
			'mrs_req_date' => Yii::t('app', 'Mrs Req Date'),
			'status' => Yii::t('app', 'Status'),
			'type_id' => Yii::t('app', 'Type'),
			'remarks' => Yii::t('app', 'Remarks'),
			'create_time' => Yii::t('app', 'Create Time'),
			'update_time' => Yii::t('app', 'Update Time'),
				'vendor_id' => Yii::t('app', 'Vendor'),
			'create_user_id' => null,
			'updated_by' => null,
			'outlet_id' => null,
			'organization_id' => null,
			'mrns' => null,
			'createUser' => null,
			'organization' => null,
			'outlet' => null,
			'updatedBy' => null,
			'mrsDetails' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('mrs_date', $this->mrs_date, true);
		$criteria->compare('mrs_update_date', $this->mrs_update_date, true);
		$criteria->compare('mrs_req_date', $this->mrs_req_date, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('remarks', $this->remarks, true);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('update_time', $this->update_time, true);
		$criteria->compare('create_user_id', $this->create_user_id);
		$criteria->compare('updated_by', $this->updated_by);
		$criteria->compare('outlet_id', $this->outlet_id);
		$criteria->compare('organization_id', $this->organization_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}