<?php

 
/**
 * This is the model base class for the table "{{purchase_order}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PurchaseOrder".
 *
 * Columns in table "{{purchase_order}}" available as properties of the model,
 * followed by relations of table "{{purchase_order}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $code
 * @property string $start_date
 * @property string $end_date
 * @property string $receiving_date
 * @property integer $status
 * @property integer $type_id
 * @property integer $is_open_po
 * @property integer $is_po_received
 * @property string $remarks
 * @property string $payment_terms
 * @property string $transport_mode
 * @property double $purchase_order_amount
 * @property double $charges_total_amount
 * @property double $discount_amount
 * @property double $frieght_charges
 * @property double $extra_charges
 * @property double $total_amount
 * @property string $create_time
 * @property string $update_time
 * @property integer $create_user_id
 * @property integer $updated_by
 * @property integer $outlet_id
 * @property integer $vendor_id
 * @property integer $mrn_id
 * @property integer $organization_id
 *
 * @property PurchaseBill[] $purchaseBills
 * @property User $createUser
 * @property Mrn $mrn
 * @property Organization $organization
 * @property Outlet $outlet
 * @property User $updatedBy
 * @property Vendor $vendor
 * @property PurchaseOrderDetail[] $purchaseOrderDetails
 */
abstract class BasePurchaseOrder extends GxActiveRecord {

	
	const STATUS_UNAPPROVED = 0;
	const STATUS_APPROVED = 1;
	const STATUS_REJECT = 2;
	public static function getStatusOptions($id = null)
	{
		$list = array("UnApproved","Approved","Rejected");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
	public static function getTypeOptions($id = null)
	{
		$list = array("TYPE1","TYPE2","TYPE3");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
 	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
			if ( !isset( $this->create_time )) $this->create_time = new CDbExpression('NOW()');
				if ( !isset( $this->create_user_id )) $this->create_user_id = Yii::app()->user->id;			
	}else{
					}
		return parent::beforeValidate();
	}

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{purchase_order}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PurchaseOrder|PurchaseOrders', $n);
	}

	public static function representingColumn() {
		return 'code';
	}

	public function rules() {
		return array(
			array('code, start_date, vendor_id, mrn_id, organization_id', 'required'),
			array('status, type_id, is_open_po, is_po_received, create_user_id, updated_by, outlet_id, vendor_id, mrn_id, organization_id', 'numerical', 'integerOnly'=>true),
			array('purchase_order_amount, charges_total_amount, discount_amount, frieght_charges, extra_charges, total_amount', 'numerical'),
			array('code, transport_mode', 'length', 'max'=>255),
			array('remarks, payment_terms, create_time, update_time', 'safe'),
			array('status, type_id, is_open_po, is_po_received, remarks, payment_terms, purchase_order_amount, charges_total_amount, discount_amount, frieght_charges, extra_charges, total_amount, create_time, update_time, updated_by, outlet_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, code, start_date, end_date, receiving_date, status, type_id, is_open_po, is_po_received, remarks, payment_terms, transport_mode, purchase_order_amount, charges_total_amount, discount_amount, frieght_charges, extra_charges, total_amount, create_time, update_time, create_user_id, updated_by, outlet_id, vendor_id, mrn_id, organization_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'purchaseBills' => array(self::HAS_MANY, 'PurchaseBill', 'purchase_order_id'),
			'createUser' => array(self::BELONGS_TO, 'User', 'create_user_id'),
			'mrn' => array(self::BELONGS_TO, 'Mrn', 'mrn_id'),
			'organization' => array(self::BELONGS_TO, 'Organization', 'organization_id'),
			'outlet' => array(self::BELONGS_TO, 'Outlet', 'outlet_id'),
			'updatedBy' => array(self::BELONGS_TO, 'User', 'updated_by'),
			'vendor' => array(self::BELONGS_TO, 'Vendor', 'vendor_id'),
			'purchaseOrderDetails' => array(self::HAS_MANY, 'PurchaseOrderDetail', 'purchase_order_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'code' => Yii::t('app', 'Code'),
			'start_date' => Yii::t('app', 'Start Date'),
			'end_date' => Yii::t('app', 'End Date'),
			'receiving_date' => Yii::t('app', 'Receiving Date'),
			'status' => Yii::t('app', 'Status'),
			'type_id' => Yii::t('app', 'Type'),
			'is_open_po' => Yii::t('app', 'Is Open Po'),
			'is_po_received' => Yii::t('app', 'Is Po Received'),
			'remarks' => Yii::t('app', 'Remarks'),
			'payment_terms' => Yii::t('app', 'Payment Terms'),
			'transport_mode' => Yii::t('app', 'Transport Mode'),
			'purchase_order_amount' => Yii::t('app', 'Purchase Order Amount'),
			
			'charges_total_amount' => Yii::t('app', 'Charges Total Amount'),
			'discount_amount' => Yii::t('app', 'Discount Amount'),
			'frieght_charges' => Yii::t('app', 'Frieght Charges'),
			'extra_charges' => Yii::t('app', 'Extra Charges'),
			'total_amount' => Yii::t('app', 'Total Amount'),
			'create_time' => Yii::t('app', 'Create Time'),
			'update_time' => Yii::t('app', 'Update Time'),
			'create_user_id' => null,
			'updated_by' => null,
			'outlet_id' => null,
			'vendor_id' => null,
			'mrn_id' => null,
			'organization_id' => null,
			'purchaseBills' => null,
			'createUser' => null,
			'mrn' => null,
			'organization' => null,
			'outlet' => null,
			'updatedBy' => null,
			'vendor' => null,
			'purchaseOrderDetails' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('start_date', $this->start_date, true);
		$criteria->compare('end_date', $this->end_date, true);
		$criteria->compare('receiving_date', $this->receiving_date, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('is_open_po', $this->is_open_po);
		$criteria->compare('is_po_received', $this->is_po_received);
		$criteria->compare('remarks', $this->remarks, true);
		$criteria->compare('payment_terms', $this->payment_terms, true);
		$criteria->compare('transport_mode', $this->transport_mode, true);
		$criteria->compare('purchase_order_amount', $this->purchase_order_amount);
		$criteria->compare('charges_total_amount', $this->charges_total_amount);
		$criteria->compare('discount_amount', $this->discount_amount);
		$criteria->compare('frieght_charges', $this->frieght_charges);
		$criteria->compare('extra_charges', $this->extra_charges);
		$criteria->compare('total_amount', $this->total_amount);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('update_time', $this->update_time, true);
		$criteria->compare('create_user_id', $this->create_user_id);
		$criteria->compare('updated_by', $this->updated_by);
		$criteria->compare('outlet_id', $this->outlet_id);
		$criteria->compare('vendor_id', $this->vendor_id);
		$criteria->compare('mrn_id', $this->mrn_id);
		$criteria->compare('organization_id', $this->organization_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}