<?php


 
/**
 * This is the model base class for the table "{{permission}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Permission".
 *
 * Columns in table "{{permission}}" available as properties of the model,
 * followed by relations of table "{{permission}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $title
 * @property string $url
 * @property integer $status
 * @property integer $type_id
 * @property string $create_time
 * @property integer $create_user_id
 * @property integer $updated_by
 *
 * @property User $createUser
 * @property User $updatedBy
 * @property RolePermission[] $rolePermissions
 */
abstract class BasePermission extends GxActiveRecord {
	const STATUS_ACTIVE = 0;
	const STATUS_INACTIVE = 1;
	
	public static function getStatusOptions($id = null) {
		$list = array (
				"Active",
				"Inactive"
		);
		if ($id == null)
			return $list;
			if (is_numeric ( $id ))
				return $list [$id];
				return $id;
	}
	public static function getTypeOptions($id = null)
	{
		$list = array("TYPE1","TYPE2","TYPE3");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
 	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
			if ( !isset( $this->create_time )) $this->create_time = new CDbExpression('NOW()');
			if ( !isset( $this->create_user_id )) $this->create_user_id = Yii::app()->user->id;			
	}else{
				}
		return parent::beforeValidate();
	}

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{permission}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Permission|Permissions', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('title, url, create_time, create_user_id', 'required'),
			array('status, type_id, create_user_id, updated_by', 'numerical', 'integerOnly'=>true),
			array('title, url', 'length', 'max'=>255),
			array('status, type_id, updated_by', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, title, url, status, type_id, create_time, create_user_id, updated_by', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'createUser' => array(self::BELONGS_TO, 'User', 'create_user_id'),
			'updatedBy' => array(self::BELONGS_TO, 'User', 'updated_by'),
			'rolePermissions' => array(self::HAS_MANY, 'RolePermission', 'permission_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'title' => Yii::t('app', 'Title'),
			'url' => Yii::t('app', 'Url'),
			'status' => Yii::t('app', 'Status'),
			'type_id' => Yii::t('app', 'Type'),
			'create_time' => Yii::t('app', 'Create Time'),
			'create_user_id' => null,
			'updated_by' => null,
			'createUser' => null,
			'updatedBy' => null,
			'rolePermissions' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('url', $this->url, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('create_user_id', $this->create_user_id);
		$criteria->compare('updated_by', $this->updated_by);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}