<?php

 
/**
 * This is the model base class for the table "{{item_vendor}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ItemVendor".
 *
 * Columns in table "{{item_vendor}}" available as properties of the model,
 * followed by relations of table "{{item_vendor}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $item_detail_id
 * @property integer $vendor_id
 * @property integer $status
 * @property integer $type_id
 * @property string $create_time
 * @property integer $create_user_id
 * @property integer $updated_by
 *
 * @property User $createUser
 * @property ItemDetail $itemDetail
 * @property User $updatedBy
 * @property Vendor $vendor
 */
abstract class BaseItemVendor extends GxActiveRecord {

	
	public static function getStatusOptions($id = null)
	{
		$list = array("Draft","Published","Archive");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}	
	public static function getTypeOptions($id = null)
	{
		$list = array("TYPE1","TYPE2","TYPE3");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
 	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
			if ( !isset( $this->create_time )) $this->create_time = new CDbExpression('NOW()');
			if ( !isset( $this->create_user_id )) $this->create_user_id = Yii::app()->user->id;			
	}else{
		//if ( !isset( $this->update_time )) $this->update_time = new CDbExpression('NOW()');
		if ( !isset( $this->updated_by )) $this->updated_by = Yii::app()->user->id;
				}
		return parent::beforeValidate();
	}

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{item_vendor}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ItemVendor|ItemVendors', $n);
	}

	public static function representingColumn() {
		return 'create_time';
	}

	public function rules() {
		return array(
			array('item_detail_id, vendor_id, create_time, create_user_id,', 'required'),
			array('item_code,vendor_price', 'required','on'=>'create'), //, contact_no
			array('item_detail_id, vendor_id, status, type_id, create_user_id, updated_by', 'numerical', 'integerOnly'=>true),
			array('vendor_price,item_code','safe'),
			array('status, type_id, updated_by', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, item_detail_id, vendor_id, status, type_id, create_time, create_user_id, updated_by', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'createUser' => array(self::BELONGS_TO, 'User', 'create_user_id'),
			'itemDetail' => array(self::BELONGS_TO, 'Item', 'item_detail_id'),
			'updatedBy' => array(self::BELONGS_TO, 'User', 'updated_by'),
			'vendor' => array(self::BELONGS_TO, 'Vendor', 'vendor_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'item_detail_id' => null,
			'vendor_id' => Yii::t('app', 'Vendor'),
			'item_code' => Yii::t('app', 'Vendor Code'),
			'vendor_price' => Yii::t('app', 'Vendor Price'),
			'status' => Yii::t('app', 'Status'),
			'type_id' => Yii::t('app', 'Type'),
			'create_time' => Yii::t('app', 'Create Time'),
			'create_user_id' => null,
			'updated_by' => null,
			'createUser' => null,
			'itemDetail' => null,
			'updatedBy' => null,
			'vendor' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('item_detail_id', $this->item_detail_id);
		$criteria->compare('vendor_id', $this->vendor_id);
		$criteria->compare('status', $this->status);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('create_user_id', $this->create_user_id);
		$criteria->compare('updated_by', $this->updated_by);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}