<?php


 
/**
 * This is the model base class for the table "{{order_refund_item}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "OrderRefundItem".
 *
 * Columns in table "{{order_refund_item}}" available as properties of the model,
 * followed by relations of table "{{order_refund_item}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $order_refund_id
 * @property integer $item_detail_id
 * @property integer $qty
 * @property double $price
 * @property integer $discount_id
 * @property double $discount_amt
 * @property integer $tax_id
 * @property double $tax_amt
 * @property double $order_discount
 * @property integer $status
 * @property integer $type_id
 * @property string $create_time
 * @property string $update_time
 * @property integer $create_user_id
 * @property integer $updated_by
 *
 * @property User $createUser
 * @property Discount $discount
 * @property ItemDetail $itemDetail
 * @property OrderRefund $orderRefund
 * @property User $updatedBy
 */
abstract class BaseOrderRefundItem extends GxActiveRecord {

	public $columns;
	public $bill_no;
	public $total_amt;
	public static function getStatusOptions($id = null)
	{
		$list = array("Draft","Published","Archive");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}	
	public static function getTypeOptions($id = null)
	{
		$list = array("TYPE1","TYPE2","TYPE3");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
 	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
			if ( !isset( $this->create_time )) $this->create_time = new CDbExpression('NOW()');
				if ( !isset( $this->create_user_id )) $this->create_user_id = Yii::app()->user->id;			
	}else{
					}
		return parent::beforeValidate();
	}

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{order_refund_item}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'OrderRefundItem|OrderRefundItems', $n);
	}

	public static function representingColumn() {
		return 'create_time';
	}

	public function rules() {
		return array(
			array('tax_id, tax_amt, order_discount', 'required'),
			array('order_refund_id, item_detail_id, discount_id, tax_id, status, type_id, create_user_id, updated_by', 'numerical', 'integerOnly'=>true),
			array('price, discount_amt, tax_amt, order_discount', 'numerical'),
			array('create_time, update_time,item_id,bill_no,total_amt,qty,total_amt', 'safe'),
			array('order_refund_id, item_detail_id, qty, price, discount_id, discount_amt, status, type_id, create_time, update_time, create_user_id, updated_by', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, order_refund_id, item_detail_id, qty, price, discount_id, discount_amt, tax_id, tax_amt, order_discount, status, type_id, create_time, update_time, create_user_id, updated_by', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'createUser' => array(self::BELONGS_TO, 'User', 'create_user_id'),
			'discount' => array(self::BELONGS_TO, 'Discount', 'discount_id'),
			'itemDetail' => array(self::BELONGS_TO, 'ItemDetail', 'item_detail_id'),
				'item' => array(self::BELONGS_TO, 'Item', 'item_id'),
			'orderRefund' => array(self::BELONGS_TO, 'OrderRefund', 'order_refund_id'),
			'updatedBy' => array(self::BELONGS_TO, 'User', 'updated_by'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'order_refund_id' => null,
			'item_detail_id' => null,
			'qty' => Yii::t('app', 'Qty'),
			'price' => Yii::t('app', 'Price'),
			'discount_id' => null,
			'discount_amt' => Yii::t('app', 'Discount Amt'),
			'tax_id' => Yii::t('app', 'Tax'),
			'tax_amt' => Yii::t('app', 'Tax Amt'),
			'order_discount' => Yii::t('app', 'Order Discount'),
			'status' => Yii::t('app', 'Status'),
			'type_id' => Yii::t('app', 'Type'),
			'create_time' => Yii::t('app', 'Create Time'),
			'update_time' => Yii::t('app', 'Update Time'),
				'item_id' => Yii::t('app', 'Item'),
			'create_user_id' => null,
			'updated_by' => null,
			'createUser' => null,
			'discount' => null,
			'itemDetail' => null,
			'orderRefund' => null,
			'updatedBy' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;
		if(isset($this->bill_no) && ($this->bill_no != '')){
			$refund_ids = array();
			$order = Order::model()->findByAttributes(array('bill_no'=>$this->bill_no));
			if($order){
		$criteria1 = new CDbCriteria;
		$criteria1->compare('order_id',$order->id);
		$orders = OrderRefund::model()->findAll($criteria1);
		if($orders){
			foreach($orders as $orderrefund){
				$refund_ids[] = $orderrefund->id;
			}
		}
			}
			$criteria->addInCondition('order_refund_id', $refund_ids);
		}
		$criteria->with = array('itemDetail','item','orderRefund');
		$criteria->compare('t.id', $this->id);
		$criteria->compare('t.order_refund_id', $this->order_refund_id);
		$criteria->compare('t.item_detail_id', $this->item_detail_id);
		$criteria->compare('item.title', $this->item_id ,true);
		$criteria->compare('orderRefund.total_amt', $this->total_amt ,true);
		//$criteria->compare('t.item_id', $this->item_id);
		$criteria->compare('t.qty', $this->qty);
		$criteria->compare('t.price', $this->price);
		$criteria->compare('t.discount_id', $this->discount_id);
		$criteria->compare('t.discount_amt', $this->discount_amt);
		$criteria->compare('t.tax_id', $this->tax_id);
		$criteria->compare('t.tax_amt', $this->tax_amt);
		$criteria->compare('t.order_discount', $this->order_discount);
		$criteria->compare('t.status', $this->status);
		$criteria->compare('t.type_id', $this->type_id);
		$criteria->compare('t.create_time', $this->create_time, true);
		$criteria->compare('t.update_time', $this->update_time, true);
		$criteria->compare('t.create_user_id', $this->create_user_id);
		$criteria->compare('t.updated_by', $this->updated_by);
		$criteria->order = 't.id DESC';
		$refundItems = OrderRefundItem::model()->findAll($criteria);
		if($refundItems){
		$total = 0;
			foreach($refundItems as $refundItem){
				$total = $total + $refundItem->total_amt;
			}
			Yii::app ()->session ['refund_total']=number_format($total,2);
		}
		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
	public function defaultScope()
	{
		return array();
	}
}