<?php

/**
 * This is the model base class for the table "{{advance_payment}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AdvancePayment".
 *
 * Columns in table "{{advance_payment}}" available as properties of the model,
 * followed by relations of table "{{advance_payment}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $payment_date
 * @property double $payment
 * @property integer $type_id
 * @property integer $status
 * @property string $create_time
 * @property string $update_time
 * @property integer $vendor_id
 * @property integer $create_user_id
 * @property integer $updated_by
 *
 * @property User $createUser
 * @property User $updatedBy
 * @property Vendor $vendor
 */
abstract class BaseAdvancePayment extends GxActiveRecord {
	public static function getTypeOptions($id = null) {
		$list = array (
				"TYPE1",
				"TYPE2",
				"TYPE3" 
		);
		if ($id == null)
			return $list;
		if (is_numeric ( $id ))
			return $list [$id];
		return $id;
	}
	public static function getStatusOptions($id = null) {
		$list = array (
				"Draft",
				"Published",
				"Archive" 
		);
		if ($id == null)
			return $list;
		if (is_numeric ( $id ))
			return $list [$id];
		return $id;
	}
	public function beforeValidate() {
		if ($this->isNewRecord) {
			if (! isset ( $this->create_time ))
				$this->create_time = new CDbExpression ( 'NOW()' );
			if (! isset ( $this->create_user_id ))
				$this->create_user_id = Yii::app ()->user->id;
		} else {
		}
		return parent::beforeValidate ();
	}
	public static function model($className = __CLASS__) {
		return parent::model ( $className );
	}
	public function tableName() {
		return '{{advance_payment}}';
	}
	public static function label($n = 1) {
		return Yii::t ( 'app', 'AdvancePayment|AdvancePayments', $n );
	}
	public static function representingColumn() {
		return 'payment_date';
	}
	public function rules() {
		return array (
				array (
						'payment_date, payment, vendor_id, create_user_id',
						'required' 
				),
				array (
						'type_id, status, vendor_id, create_user_id, updated_by',
						'numerical',
						'integerOnly' => true 
				),
				array (
						'payment',
						'numerical' 
				),
				array (
						'create_time, update_time,balance_amt',
						'safe' 
				),
				array (
						'type_id, status, create_time, update_time, updated_by',
						'default',
						'setOnEmpty' => true,
						'value' => null 
				),
				array (
						'id, payment_date, payment, type_id, status, create_time, update_time, vendor_id, create_user_id, updated_by',
						'safe',
						'on' => 'search' 
				) 
		);
	}
	public function relations() {
		return array (
				'createUser' => array (
						self::BELONGS_TO,
						'User',
						'create_user_id' 
				),
				'updatedBy' => array (
						self::BELONGS_TO,
						'User',
						'updated_by' 
				),
				'vendor' => array (
						self::BELONGS_TO,
						'Vendor',
						'vendor_id' 
				),
				'advancelogs' => array (
						self::HAS_MANY,
						'AdvanceLogs',
						'advance_payment_id' 
				) 
		);
	}
	public function pivotModels() {
		return array ();
	}
	public function attributeLabels() {
		return array (
				'id' => Yii::t ( 'app', 'ID' ),
				'payment_date' => Yii::t ( 'app', 'Payment Date' ),
				'payment' => Yii::t ( 'app', 'Payment' ),
				'type_id' => Yii::t ( 'app', 'Type' ),
				'status' => Yii::t ( 'app', 'Status' ),
				'create_time' => Yii::t ( 'app', 'Create Time' ),
				'is_advance_payment' => Yii::t ( 'app', 'Advance Payment' ),
				'update_time' => Yii::t ( 'app', 'Update Time' ),
				'vendor_id' => null,
				'create_user_id' => null,
				'updated_by' => null,
				'createUser' => null,
				'updatedBy' => null,
				'vendor' => null 
		);
	}
	public function search() {
		$criteria = new CDbCriteria ();
		
		$criteria->compare ( 'id', $this->id );
		$criteria->compare ( 'payment_date', $this->payment_date, true );
		$criteria->compare ( 'payment', $this->payment );
		$criteria->compare ( 'type_id', $this->type_id );
		$criteria->compare ( 'status', $this->status );
		$criteria->compare ( 'create_time', $this->create_time, true );
		$criteria->compare ( 'update_time', $this->update_time, true );
		$criteria->compare ( 'vendor_id', $this->vendor_id );
		$criteria->compare ( 'create_user_id', $this->create_user_id );
		$criteria->compare ( 'updated_by', $this->updated_by );
		
		return new CActiveDataProvider ( $this, array (
				'criteria' => $criteria 
		) );
	}
}