<?php

 
/**
 * This is the model base class for the table "{{mrn}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Mrn".
 *
 * Columns in table "{{mrn}}" available as properties of the model,
 * followed by relations of table "{{mrn}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $code
 * @property string $mrs_date
 * @property string $mrs_update_date
 * @property string $mrs_req_date
 * @property integer $status
 * @property integer $type_id
 * @property string $remarks
 * @property string $create_time
 * @property string $update_time
 * @property integer $create_user_id
 * @property integer $updated_by
 * @property integer $outlet_id
 * @property integer $mrs_id
 * @property integer $organization_id
 *
 * @property User $createUser
 * @property Mrs $mrs
 * @property Organization $organization
 * @property Outlet $outlet
 * @property User $updatedBy
 * @property MrnDetail[] $mrnDetails
 * @property PurchaseOrder[] $purchaseOrders
 */
abstract class BaseMrn extends GxActiveRecord {

	const STATUS_UNAPPROVED = 0;
	const STATUS_APPROVED = 1;
	const STATUS_REJECT = 2;
	
	public static function getStatusOptions($id = null)
	{
		$list = array("UnApproved","Approved","Reject");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}	
	public static function getTypeOptions($id = null)
	{
		$list = array("TYPE1","TYPE2","TYPE3");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
 	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
			if ( !isset( $this->create_time )) $this->create_time = new CDbExpression('NOW()');
				if ( !isset( $this->create_user_id )) $this->create_user_id = Yii::app()->user->id;			
	}else{
					}
		return parent::beforeValidate();
	}

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{mrn}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Mrn|Mrns', $n);
	}

	public static function representingColumn() {
		return 'code';
	}

	public function rules() {
		return array(
			array('code, mrs_date, mrs_req_date, outlet_id, mrs_id, organization_id', 'required'),
			array('status, type_id, create_user_id, updated_by, outlet_id, mrs_id, organization_id', 'numerical', 'integerOnly'=>true),
			array('code', 'length', 'max'=>255),
			array('mrs_update_date, remarks, create_time, update_time,vendor_id', 'safe'),
			array('mrs_update_date, status, type_id, remarks, create_time, update_time, updated_by', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, code, mrs_date, mrs_update_date, mrs_req_date, status, type_id, remarks, create_time, update_time, create_user_id, updated_by, outlet_id, mrs_id, organization_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'createUser' => array(self::BELONGS_TO, 'User', 'create_user_id'),
			'mrs' => array(self::BELONGS_TO, 'Mrs', 'mrs_id'),
			'organization' => array(self::BELONGS_TO, 'Organization', 'organization_id'),
			'outlet' => array(self::BELONGS_TO, 'Outlet', 'outlet_id'),
			'updatedBy' => array(self::BELONGS_TO, 'User', 'updated_by'),
				'vendor' => array(self::BELONGS_TO, 'Vendor', 'vendor_id'),
			'mrnDetails' => array(self::HAS_MANY, 'MrnDetail', 'mrn_id'),
			'purchaseOrders' => array(self::HAS_MANY, 'PurchaseOrder', 'mrn_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'code' => Yii::t('app', 'Code'),
			'mrs_date' => Yii::t('app', 'Mrs Date'),
			'mrs_update_date' => Yii::t('app', 'Mrs Update Date'),
			'mrs_req_date' => Yii::t('app', 'Mrs Req Date'),
			'status' => Yii::t('app', 'Status'),
			'type_id' => Yii::t('app', 'Type'),
			'remarks' => Yii::t('app', 'Remarks'),
			'create_time' => Yii::t('app', 'Create Time'),
			'update_time' => Yii::t('app', 'Update Time'),
			'createUser' =>  Yii::t('app', 'Create User'),
				'vendor_id' =>  Yii::t('app', 'Vendor'),
			'updated_by' => null,
			'outlet_id' => null,
			'mrs_id' => null,
			'organization_id' => null,
		//	'createUser' => null,
			'mrs' => null,
			'organization' => null,
			'outlet' => null,
			'updatedBy' => Yii::t('app', 'Updated By'),
			'mrnDetails' => null,
			'purchaseOrders' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('mrs_date', $this->mrs_date, true);
		$criteria->compare('mrs_update_date', $this->mrs_update_date, true);
		$criteria->compare('mrs_req_date', $this->mrs_req_date, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('remarks', $this->remarks, true);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('update_time', $this->update_time, true);
		$criteria->compare('create_user_id', $this->create_user_id);
		$criteria->compare('updated_by', $this->updated_by);
		$criteria->compare('outlet_id', $this->outlet_id);
		$criteria->compare('mrs_id', $this->mrs_id);
		$criteria->compare('vendor_id', $this->vendor_id);
		$criteria->compare('organization_id', $this->organization_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}