<?php

 
/**
 * This is the model base class for the table "{{order}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Order".
 *
 * Columns in table "{{order}}" available as properties of the model,
 * followed by relations of table "{{order}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $qty
 * @property double $discount_amt
 * @property double $total_amt
 * @property double $paid_amt
 * @property integer $status
 * @property integer $type_id
 * @property integer $city_id
 * @property integer $state_id
 * @property integer $country_id
 * @property string $address
 * @property string $note
 * @property string $create_time
 * @property string $update_time
 * @property integer $customer_id
 * @property integer $updated_by
 *
 * @property City $city
 * @property Country $country
 * @property Customer $customer
 * @property State $state
 * @property User $updatedBy
 * @property OrderItem[] $orderItems
 * @property OrderRefund[] $orderRefunds
 */
abstract class BaseOrder extends GxActiveRecord {

	public $start_date;
	public $end_date;
	public $columns;
	public $item_id;
	public $min_amt;
	public $max_amt;
	public static function getTypeOptions($id = null)
	{
		$list = array("Offline","Online");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
	public static function getPaymentTypeOptions($id = null)
	{
		$list = array("B2B","Expense","Cash");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
	public static function getDeliveryTypeOptions($id = null)
	{
		$list = array("Offline","Online");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
	public static function getStatusOptions($id = null)
	{
		$list = array("Draft","Published","Archive");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}	
	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
			if ( !isset( $this->create_time )) $this->create_time = new CDbExpression('NOW()');
			}else{
				}
		return parent::beforeValidate();
	}

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{order}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Order|Orders', $n);
	}

	public static function representingColumn() {
		return 'address';
	}

	public function rules() {
		return array(
			array('bill_date,mode_of_payment,mode_of_delivery', 'required'),
			array('qty, status, type_id, city_id, state_id, country_id, customer_id, updated_by', 'numerical', 'integerOnly'=>true),
			array('discount_amt, total_amt, paid_amt', 'numerical'),
			array('address,min_amt,max_amt,note, create_time, update_time,bill_no,bill_date,mode_of_payment,mode_of_delivery,columns,credit_note_id,create_user_id,start_date,end_date,item_id,bill_no,min_amt,max_amt,start_date,end_date,is_mobile,online_order_id', 'safe'),
			array('qty, discount_amt, total_amt, paid_amt, status, type_id, address, note, create_time, update_time, updated_by', 'default', 'setOnEmpty' => true, 'value' => null),
			array('bill_no,id, qty, discount_amt, total_amt, paid_amt, status, type_id, city_id, state_id, country_id, address, note, create_time, update_time, customer_id, updated_by', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'city' => array(self::BELONGS_TO, 'City', 'city_id'),
			'country' => array(self::BELONGS_TO, 'Country', 'country_id'),
			'customer' => array(self::BELONGS_TO, 'Customer', 'customer_id'),
				'createUser' => array(self::BELONGS_TO, 'User', 'create_user_id'),
			'state' => array(self::BELONGS_TO, 'State', 'state_id'),
			'updatedBy' => array(self::BELONGS_TO, 'User', 'updated_by'),
				'outlet' => array(self::BELONGS_TO, 'Outlet', 'outlet_id'),
			'orderItems' => array(self::HAS_MANY, 'OrderItem', 'order_id'),
			'orderRefunds' => array(self::HAS_MANY, 'OrderRefund', 'order_id'),
				'modePayment'=> array(self::BELONGS_TO, 'PaymentMode', 'mode_of_payment'),
				'modeDelivery'=> array(self::BELONGS_TO, 'PaymentMode', 'mode_of_delivery'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'qty' => Yii::t('app', 'Qty'),
			'discount_amt' => Yii::t('app', 'Discount Amt'),
			'total_amt' => Yii::t('app', 'Total Amt'),
				'min_amt' => Yii::t('app', 'Minimum Total Amount'),
				'max_amt' => Yii::t('app', 'Maximum Total Amount'),
			'paid_amt' => Yii::t('app', 'Paid Amt'),
			'status' => Yii::t('app', 'Status'),
			'type_id' => Yii::t('app', 'Type'),
			'city_id' => null,
			'state_id' => null,
			'country_id' => null,
			'address' => Yii::t('app', 'Address'),
			'note' => Yii::t('app', 'Note'),
			'create_time' => Yii::t('app', 'Create Time'),
			'update_time' => Yii::t('app', 'Update Time'),
			'customer_id' => null,
			'updated_by' => null,
			'city' => null,
			'country' => null,
			'customer' => null,
			'state' => null,
			'updatedBy' => null,
			'orderItems' => null,
			'orderRefunds' => null,
		);
	}
	public function userwisesearch() {
		$criteria = new CDbCriteria;
		 if(($this->start_date != '' && $this->start_date != null) && ($this->end_date != '' && $this->end_date != null)){
			$criteria->addBetweenCondition('bill_date', $this->start_date, $this->end_date);
		}
		if((Yii::app()->session['start_date'] != '') && (Yii::app()->session['end_date'] != '')){
			$criteria->addBetweenCondition('bill_date',Yii::app()->session['start_date'], Yii::app()->session['end_date']);
		} 
		// $criteria->select ='t.*, sum(total_amt) as total_amt ';
		$criteria->group = 'create_user_id';
		// MySQL 5.7 sorted GROUP BY results implicitly; MySQL 8.0 does not. Order
		// explicitly by the grouped columns to preserve the previous output order.
		$criteria->order = 'create_user_id';
		$criteria->compare('id', $this->id);
		$criteria->compare('bill_no', $this->bill_no);
		$criteria->compare('qty', $this->qty);
		$criteria->compare('discount_amt', $this->discount_amt);
		if($this->total_amt != '0.000'){
		$criteria->compare('total_amt', $this->total_amt);
		}
		$criteria->compare('paid_amt', $this->paid_amt);
		 $criteria->compare('status', $this->status);
		$criteria->compare('type_id', $this->type_id); 
	 	$criteria->compare('city_id', $this->city_id);
		$criteria->compare('state_id', $this->state_id);
		$criteria->compare('country_id', $this->country_id); 
		$criteria->compare('address', $this->address, true);
		$criteria->compare('note', $this->note, true);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('update_time', $this->update_time, true);
		$criteria->compare('customer_id', $this->customer_id);
		$criteria->compare('updated_by', $this->updated_by); 
		// $orders = Order::model()->findAll($criteria);
		// echo"<pre>"; print_r($orders); die;
	   /*  if($orders){
			$taxable = 0;
			$total = 0;
			foreach($orders as $order){
				$taxable = $taxable + $order->getTotalGrossAmount();
				$total = $total + $order->getTotalNetAmount();
				//Yii::log ( CVarDumper::dumpAsString ($total), CLogger::LEVEL_WARNING, '$total' );
			}
		
			Yii::app ()->session ['gross_total']=round($taxable);
			Yii::app ()->session ['gross_total_amt']=round($total);
		} */
		$taxable = 0;
		$total = 0;
		Yii::app ()->session ['gross_total']=round($taxable);
		Yii::app ()->session ['gross_total_amt']=round($total);
		return new CActiveDataProvider($this, array(
				'criteria' => $criteria,
				'sort'=>array(
						'defaultOrder'=>'id DESC',
				),
		));
	}
	public function defaultScope()
	{
		return array();
	}
	public function search() {
		$result_ids = array();
		$order_refund_ids = array();
		$order_ids = array();
		$criteria1 = new CDbCriteria;
		
		if ((Yii::app ()->session ['order_start_date'] != '') && (Yii::app ()->session ['order_end_date'] != '')) {
			$criteria1->addBetweenCondition ( 't.bill_date', Yii::app ()->session ['order_start_date'], Yii::app ()->session ['order_end_date'] );
		}
		
		if ((Yii::app ()->session ['order_min_amt'] != '') && (Yii::app ()->session ['order_max_amt'] != '')) {
			$criteria1->addBetweenCondition ( 't.total_Amt', Yii::app ()->session ['order_min_amt'], Yii::app ()->session ['order_max_amt'] );
		}
		if ((Yii::app ()->session ['order_start_date'] != '') && (Yii::app ()->session ['order_end_date'] != '')) {
		$orders = Order::model()->findAll($criteria1);
		if($orders){
			foreach($orders as $order){
				$order_ids[] = $order->id;
			}
		}
		}
		
		if ((Yii::app ()->session ['order_start_date'] != '') && (Yii::app ()->session ['order_end_date'] != '')) {
			$criteria2 = new CDbCriteria;
			$criteria2->addBetweenCondition ( 'date(create_time)', Yii::app ()->session ['order_start_date'], Yii::app ()->session ['order_end_date'] );
			$order_refunds = OrderRefund::model()->findAll($criteria2);
			Yii::log ( CVarDumper::dumpAsString ( 	$order_refunds  ), CLogger::LEVEL_WARNING, '$order_refunds' );
			if(!empty($order_refunds)){
				foreach($order_refunds as $order_refund){
					$order_refund_ids[] = $order_refund->order_id;
				}
			}
		}
		
		
		
		
		if(!empty($order_refund_ids) && !empty($order_ids)){
			$result_ids = array_merge($order_refund_ids,$order_ids);
			$result_ids = array_unique($result_ids);
		}else{
			if ((Yii::app ()->session ['order_start_date'] != '') && (Yii::app ()->session ['order_end_date'] != '')) {
			$result_ids = $order_ids;
			}
		}
	Yii::log ( CVarDumper::dumpAsString ( 	$order_refund_ids  ), CLogger::LEVEL_WARNING, '$order_refund_ids' );
		Yii::log ( CVarDumper::dumpAsString ( 	$order_ids ), CLogger::LEVEL_WARNING, '$order_ids' );
		Yii::log ( CVarDumper::dumpAsString ( 	$result_ids ), CLogger::LEVEL_WARNING, '$result_ids' );
// 		Yii::log ( CVarDumper::dumpAsString ( 	Yii::app()->session['order_start_date']  ), CLogger::LEVEL_WARNING, 'startt_date' );
// 		Yii::log ( CVarDumper::dumpAsString ( 	Yii::app()->session['order_end_date']  ), CLogger::LEVEL_WARNING, 'endd_datte' );
		$criteria = new CDbCriteria;
		//if(!empty($result_ids)){
			
			$criteria->addInCondition('id', $result_ids);
		//}
		$criteria->compare('id', $this->id);
		$criteria->compare('qty', $this->qty);
		$criteria->compare('mode_of_payment', $this->mode_of_payment);
		$criteria->compare('bill_no', $this->bill_no);
		Yii::log ( CVarDumper::dumpAsString ( 	$this ), CLogger::LEVEL_WARNING, '$$this' );
		$criteria->compare('bill_date', $this->bill_date);
		$criteria->compare('discount_amt', $this->discount_amt);
		$criteria->compare('total_amt', $this->total_amt);
		$criteria->compare('paid_amt', $this->paid_amt);
		$criteria->compare('status', $this->status);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('city_id', $this->city_id);
		$criteria->compare('state_id', $this->state_id);
		$criteria->compare('country_id', $this->country_id);
		$criteria->compare('address', $this->address, true);
		$criteria->compare('note', $this->note, true);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('update_time', $this->update_time, true);
		$criteria->compare('create_user_id', $this->create_user_id);
		$criteria->compare('customer_id', $this->customer_id);
		$criteria->compare('updated_by', $this->updated_by);
		
		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
				'pagination' => array (
						'pageSize' => '100'
				),
				'sort'=>array(
						'defaultOrder'=>'id DESC',
				),
		));
	}
	

}