<?php


/**
 * This is the model base class for the table "{{stock_log}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "StockLog".
 *
 * Columns in table "{{stock_log}}" available as properties of the model,
 * followed by relations of table "{{stock_log}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $item_detail_id
 * @property integer $item_id
 * @property string $batch_no
 * @property integer $Qty
 * @property integer $outlet_id
 * @property integer $vendor_id
 * @property integer $type_id
 * @property integer $status
 * @property string $create_time
 * @property string $update_time
 *
 * @property ItemDetail $itemDetail
 * @property Item $item
 * @property Outlet $outlet
 * @property Vendor $vendor
 */
abstract class BaseStockLog extends GxActiveRecord {
const TYPE_ADDED = 0;
 const TYPE_B2B = 7;
 const TYPE_SUBSTRACTED = 1;
 const TYPE_EXPIRED = 2;
 const TYPE_RETURNED = 3;
 const TYPE_ORDER = 4;
 const TYPE_ADJUSTED = 5;
 const TYPE_REFUND = 6;
	public static function getTypeOptions($id = null)
	{
		$list = array("Added","Substracted","Expired","Returned","Order","Adjusted","Order Refunded","B2B Sale");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
 	
	public static function getStatusOptions($id = null)
	{
		$list = array("Draft","Published","Archive");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}	
	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
			if ( !isset( $this->create_time )) $this->create_time = new CDbExpression('NOW()');
			}else{
				}
		return parent::beforeValidate();
	}

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{stock_log}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'StockLog|StockLogs', $n);
	}

	public static function representingColumn() {
		return 'batch_no';
	}

	public function rules() {
		return array(
			array('item_detail_id, item_id, batch_no, Qty', 'required'),
			array('item_detail_id, item_id, outlet_id, vendor_id, type_id, status', 'numerical', 'integerOnly'=>true),
			array('batch_no', 'length', 'max'=>255),
			array('create_time, update_time,Qty,current_qty,previous_qty', 'safe'),
			array('outlet_id, vendor_id, type_id, status, create_time, update_time', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, item_detail_id, item_id, batch_no, Qty, outlet_id, vendor_id, type_id, status, create_time, update_time', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'itemDetail' => array(self::BELONGS_TO, 'ItemDetail', 'item_detail_id'),
			'item' => array(self::BELONGS_TO, 'Item', 'item_id'),
			'outlet' => array(self::BELONGS_TO, 'Outlet', 'outlet_id'),
			'vendor' => array(self::BELONGS_TO, 'Vendor', 'vendor_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'item_detail_id' => null,
			'item_id' => null,
			'batch_no' => Yii::t('app', 'Batch No'),
			'Qty' => Yii::t('app', 'Qty'),
				'current_qty' => Yii::t('app', 'Current Qty'),
				'previous_qty' => Yii::t('app', 'Previous Qty'),
			'outlet_id' => null,
			'vendor_id' => null,
			'type_id' => Yii::t('app', 'Type'),
			'status' => Yii::t('app', 'Status'),
			'create_time' => Yii::t('app', 'Create Time'),
			'update_time' => Yii::t('app', 'Update Time'),
			'itemDetail' => null,
			'item' => null,
			'outlet' => null,
			'vendor' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('item_detail_id', $this->item_detail_id);
		$criteria->compare('item_id', $this->item_id);
		$criteria->compare('batch_no', $this->batch_no, true);
		$criteria->compare('Qty', $this->Qty);
		$criteria->compare('outlet_id', $this->outlet_id);
		$criteria->compare('vendor_id', $this->vendor_id);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('status', $this->status);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('update_time', $this->update_time, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}