<?php


 
/**
 * This is the model base class for the table "{{emp_shift}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EmpShift".
 *
 * Columns in table "{{emp_shift}}" available as properties of the model,
 * followed by relations of table "{{emp_shift}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $emp_id
 * @property integer $shift_id
 * @property integer $status
 * @property integer $type_id
 * @property string $create_time
 * @property integer $create_user_id
 * @property integer $updated_by
 *
 * @property User $createUser
 * @property Emp $emp
 * @property Shift $shift
 * @property User $updatedBy
 */
abstract class BaseEmpShift extends GxActiveRecord {

	
	public static function getStatusOptions($id = null)
	{
		$list = array("Draft","Published","Archive");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}	
	public static function getTypeOptions($id = null)
	{
		$list = array("TYPE1","TYPE2","TYPE3");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
 	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
			if ( !isset( $this->create_time )) $this->create_time = new CDbExpression('NOW()');
			if ( !isset( $this->create_user_id )) $this->create_user_id = Yii::app()->user->id;			
	}else{
				}
		return parent::beforeValidate();
	}

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{emp_shift}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'EmpShift|EmpShifts', $n);
	}

	public static function representingColumn() {
		return 'create_time';
	}

	public function rules() {
		return array(
			array('emp_id, shift_id, create_time, create_user_id', 'required'),
			array('emp_id, shift_id, status, type_id, create_user_id, updated_by', 'numerical', 'integerOnly'=>true),
			array('status, type_id, updated_by', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, emp_id, shift_id, status, type_id, create_time, create_user_id, updated_by', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'createUser' => array(self::BELONGS_TO, 'User', 'create_user_id'),
			'emp' => array(self::BELONGS_TO, 'Emp', 'emp_id'),
			'shift' => array(self::BELONGS_TO, 'Shift', 'shift_id'),
			'updatedBy' => array(self::BELONGS_TO, 'User', 'updated_by'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'emp_id' => null,
			'shift_id' => null,
			'status' => Yii::t('app', 'Status'),
			'type_id' => Yii::t('app', 'Type'),
			'create_time' => Yii::t('app', 'Create Time'),
			'create_user_id' => null,
			'updated_by' => null,
			'createUser' => null,
			'emp' => null,
			'shift' => null,
			'updatedBy' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('emp_id', $this->emp_id);
		$criteria->compare('shift_id', $this->shift_id);
		$criteria->compare('status', $this->status);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('create_user_id', $this->create_user_id);
		$criteria->compare('updated_by', $this->updated_by);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}