<?php

 
/**
 * This is the model base class for the table "{{outlet}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Outlet".
 *
 * Columns in table "{{outlet}}" available as properties of the model,
 * followed by relations of table "{{outlet}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $title
 * @property string $email
 * @property integer $contact_no
 * @property integer $secondary_contact_no
 * @property string $address
 * @property string $tax_no
 * @property integer $status
 * @property integer $type_id
 * @property string $create_time
 * @property integer $city_id
 * @property integer $state_id
 * @property integer $country_id
 * @property integer $organization_id
 * @property integer $create_user_id
 * @property integer $updated_by
 *
 * @property Mrn[] $mrns
 * @property MrnDetail[] $mrnDetails
 * @property Mrs[] $mrs
 * @property MrsDetail[] $mrsDetails
 * @property City $city
 * @property Country $country
 * @property User $createUser
 * @property Organization $organization
 * @property State $state
 * @property User $updatedBy
 * @property PurchaseBill[] $purchaseBills
 * @property PurchaseBillDetail[] $purchaseBillDetails
 * @property PurchaseOrder[] $purchaseOrders
 * @property PurchaseOrderDetail[] $purchaseOrderDetails
 * @property Vendor[] $vendors
 */
abstract class BaseOutlet extends GxActiveRecord {
public $bill_prefix;
	const STATUS_ACTIVE = 0;
	const STATUS_INACTIVE = 1;
	public static function getStatusOptions($id = null)
	{
		$list = array("Active","InActive");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
	public static function getTypeOptions($id = null)
	{
		$list = array("TYPE1","TYPE2","TYPE3");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
 	
	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
			if ( !isset( $this->create_time )) $this->create_time = new CDbExpression('NOW()');
			if ( !isset( $this->create_user_id )) $this->create_user_id = Yii::app()->user->id;			
	}else{
				}
		return parent::beforeValidate();
	}

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{outlet}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Outlet|Outlets', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('title, email, contact_no, address, create_time, city_id, state_id, country_id, organization_id, create_user_id', 'required'),
			array('contact_no,secondary_contact_no, status, type_id, city_id, state_id, country_id, organization_id, create_user_id, updated_by', 'numerical', 'integerOnly'=>true),
			array('title, email', 'length', 'max'=>255),
				array('email', 'email'),
			//	array('email', 'unique'),
			array('tax_no,bill_prefix,po_prefix,grn_prefix', 'safe'),
			array('secondary_contact_no, tax_no, status, type_id, updated_by', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, title, email, contact_no, secondary_contact_no, address, tax_no,bill_prefix,po_prefix,grn_prefix status, type_id, create_time, city_id, state_id, country_id, organization_id, create_user_id, updated_by', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'mrns' => array(self::HAS_MANY, 'Mrn', 'outlet_id'),
			'mrnDetails' => array(self::HAS_MANY, 'MrnDetail', 'outlet_id'),
			'mrs' => array(self::HAS_MANY, 'Mrs', 'outlet_id'),
			'mrsDetails' => array(self::HAS_MANY, 'MrsDetail', 'outlet_id'),
			'city' => array(self::BELONGS_TO, 'City', 'city_id'),
			'country' => array(self::BELONGS_TO, 'Country', 'country_id'),
			'createUser' => array(self::BELONGS_TO, 'User', 'create_user_id'),
			'organization' => array(self::BELONGS_TO, 'Organization', 'organization_id'),
			'state' => array(self::BELONGS_TO, 'State', 'state_id'),
			'updatedBy' => array(self::BELONGS_TO, 'User', 'updated_by'),
			'purchaseBills' => array(self::HAS_MANY, 'PurchaseBill', 'outlet_id'),
			'purchaseBillDetails' => array(self::HAS_MANY, 'PurchaseBillDetail', 'outlet_id'),
			'purchaseOrders' => array(self::HAS_MANY, 'PurchaseOrder', 'outlet_id'),
			'purchaseOrderDetails' => array(self::HAS_MANY, 'PurchaseOrderDetail', 'outlet_id'),
			'vendors' => array(self::HAS_MANY, 'Vendor', 'outlet_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'title' => Yii::t('app', 'Title'),
			'email' => Yii::t('app', 'Email'),
			'contact_no' => Yii::t('app', 'Contact No'),
			'secondary_contact_no' => Yii::t('app', 'Secondary Contact No'),
			'address' => Yii::t('app', 'Address'),
			'tax_no' => Yii::t('app', 'Tax No'),
			'status' => Yii::t('app', 'Status'),
			'type_id' => Yii::t('app', 'Type'),
			'create_time' => Yii::t('app', 'Create Time'),
			'city_id' => null,
			'state_id' => null,
			'country_id' => null,
			'organization_id' => null,
			'create_user_id' => null,
			'updated_by' => null,
			'mrns' => null,
			'mrnDetails' => null,
			'mrs' => null,
			'mrsDetails' => null,
			'city' => null,
			'country' => null,
			'createUser' => null,
			'organization' => null,
			'state' => null,
			'updatedBy' => null,
			'purchaseBills' => null,
			'purchaseBillDetails' => null,
			'purchaseOrders' => null,
			'purchaseOrderDetails' => null,
			'vendors' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('contact_no', $this->contact_no);
		$criteria->compare('secondary_contact_no', $this->secondary_contact_no);
		$criteria->compare('address', $this->address, true);
		$criteria->compare('tax_no', $this->tax_no, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('city_id', $this->city_id);
		$criteria->compare('state_id', $this->state_id);
		$criteria->compare('country_id', $this->country_id);
		$criteria->compare('organization_id', $this->organization_id);
		$criteria->compare('create_user_id', $this->create_user_id);
		$criteria->compare('updated_by', $this->updated_by);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}