<?php

 
/**
 * This is the model base class for the table "{{item_stock}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ItemStock".
 *
 * Columns in table "{{item_stock}}" available as properties of the model,
 * followed by relations of table "{{item_stock}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $item_detail_id
 * @property integer $item_id
 * @property string $batch_number
 * @property integer $qty
 * @property double $base_price
 * @property double $mrp
 * @property integer $status
 * @property integer $type_id
 * @property string $create_time
 * @property integer $create_user_id
 * @property integer $tax_id
 * @property integer $updated_by
 *
 * @property User $createUser
 * @property ItemDetail $itemDetail
 * @property Tax $tax
 * @property User $updatedBy
 */
abstract class BaseItemStock extends GxActiveRecord {
  const TYPE_ADDED = 0;
  const TYPE_SUBSTRACT = 1;
	
	public static function getStatusOptions($id = null)
	{
		$list = array("Draft","Published","Archive");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}	
	public static function getTypeOptions($id = null)
	{
		$list = array("Add","Substract");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
 	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
			if ( !isset( $this->create_time )) $this->create_time = new CDbExpression('NOW()');
			if ( !isset( $this->create_user_id )) $this->create_user_id = Yii::app()->user->id;			
	}else{
				}
		return parent::beforeValidate();
	}

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{item_stock}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ItemStock|ItemStocks', $n);
	}

	public static function representingColumn() {
		return 'batch_number';
	}

	public function rules() {
		return array(
			array('item_id, batch_number, purchase_qty, create_time, create_user_id', 'required'),
			array('item_detail_id, item_id,status, type_id, create_user_id, tax_id, updated_by', 'numerical', 'integerOnly'=>true),
			//array('base_price, mrp', 'numerical'),
				array('is_company_batch_no', 'safe'),
				array('outlet_id,vendor_id', 'numerical'),
			array('batch_number', 'length', 'max'=>255),
			array('item_detail_id, base_price, mrp, status, type_id, tax_id, updated_by', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, item_detail_id, item_id, batch_number, purchase_qty,balance_qty base_price, mrp, status, type_id, create_time, create_user_id, tax_id, updated_by', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'createUser' => array(self::BELONGS_TO, 'User', 'create_user_id'),
			'itemDetail' => array(self::BELONGS_TO, 'ItemDetail', 'item_detail_id'),
			'tax' => array(self::BELONGS_TO, 'Tax', 'tax_id'),
			'updatedBy' => array(self::BELONGS_TO, 'User', 'updated_by'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'item_detail_id' => Yii::t('app', 'Bar Code'),
			'item_id' => Yii::t('app', 'Item'),
			'batch_number' => Yii::t('app', 'Batch Number'),
			'purchase_qty' => Yii::t('app', 'Qty'),
			'base_price' => Yii::t('app', 'Base Price'),
			'mrp' => Yii::t('app', 'Mrp'),
			'status' => Yii::t('app', 'Status'),
			'type_id' => Yii::t('app', 'Type'),
			'create_time' => Yii::t('app', 'Create Time'),
			'create_user_id' => null,
			'tax_id' => null,
			'updated_by' => null,
			'createUser' => null,
			'itemDetail' =>  Yii::t('app', 'Bar Code'),
			'tax' => null,
			'updatedBy' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('item_detail_id', $this->item_detail_id);
		$criteria->compare('item_id', $this->item_id);
		$criteria->compare('batch_number', $this->batch_number, true);
		$criteria->compare('qty', $this->qty);
		$criteria->compare('base_price', $this->base_price);
		$criteria->compare('mrp', $this->mrp);
		$criteria->compare('status', $this->status);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('create_user_id', $this->create_user_id);
		$criteria->compare('tax_id', $this->tax_id);
		$criteria->compare('updated_by', $this->updated_by);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
	


	
	
	
	
}