<?php

/**
 * Company: ToXSL Technologies Pvt. Ltd. < www.toxsl.com >
 * Author : Shiv Charan Panjeta < shiv@toxsl.com >
 */
 
/**
 * This is the model base class for the table "{{item_return}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ItemReturn".
 *
 * Columns in table "{{item_return}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property double $discount_amt
 * @property double $other_charge
 * @property string $total_amt
 * @property integer $vendor_id
 * @property integer $outlet_id
 * @property integer $status
 * @property integer $type_id
 * @property string $create_time
 * @property integer $credit_note_id
 * @property integer $create_user_id
 * @property integer $updated_by
 *
 */
abstract class BaseItemReturn extends GxActiveRecord {
	const STATUS_PENDING =0;
	const STATUS_DONE =1;
	
	public static function getStatusOptions($id = null)
	{
		$list = array("Pending","Done");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}	
	public static function getTypeOptions($id = null)
	{
		$list = array("TYPE1","TYPE2","TYPE3");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
 	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
			if ( !isset( $this->create_time )) $this->create_time = new CDbExpression('NOW()');
			if ( !isset( $this->create_user_id )) $this->create_user_id = Yii::app()->user->id;			
	}else{
				}
		return parent::beforeValidate();
	}

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{item_return}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ItemReturn|ItemReturns', $n);
	}

	public static function representingColumn() {
		return 'create_time';
	}

	public function rules() {
		return array(
			array('vendor_id, outlet_id, create_time, create_user_id', 'required'),
			array('vendor_id, outlet_id, status, type_id, credit_note_id, create_user_id, updated_by', 'numerical', 'integerOnly'=>true),
			array('discount_amt, other_charge', 'numerical'),
			array('credit_note_no, bill_no,invoice_no,grn_no,credit_note_date,grn_save_date', 'safe'),
			array('total_amt', 'length', 'max'=>10),
			array('total_amt, status, type_id, updated_by', 'default', 'setOnEmpty' => true, 'value' => null),
			array('credit_note_no, bill_no,invoice_no,grn_no,id, discount_amt, other_charge, total_amt, vendor_id, outlet_id, status, type_id, create_time, credit_note_id, create_user_id, updated_by', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
				'vendor' => array(self::BELONGS_TO, 'Vendor', 'vendor_id'),
				'outlet' => array(self::BELONGS_TO, 'Outlet', 'outlet_id'),
			'creditNote' => array(self::BELONGS_TO, 'CreditNote', 'credit_note_id'),
				'itemReturnItems' => array(self::HAS_MANY, 'ItemReturnItem', 'return_id'),
				
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'discount_amt' => Yii::t('app', 'Discount Amt'),
			'other_charge' => Yii::t('app', 'Other Charge'),
			'total_amt' => Yii::t('app', 'Total Amt'),
			'vendor_id' => Yii::t('app', 'Vendor'),
			'outlet_id' => Yii::t('app', 'Outlet'),
			'status' => Yii::t('app', 'Status'),
			'type_id' => Yii::t('app', 'Type'),
			'create_time' => Yii::t('app', 'Create Time'),
			'credit_note_id' => Yii::t('app', 'Credit Note'),
			'create_user_id' => Yii::t('app', 'Create User'),
			'updated_by' => Yii::t('app', 'Updated By'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;
        $criteria->order = ('id DESC');
		$criteria->compare('id', $this->id);
		$criteria->compare('discount_amt', $this->discount_amt);
		$criteria->compare('other_charge', $this->other_charge);
		$criteria->compare('total_amt', $this->total_amt, true);
		$criteria->compare('vendor_id', $this->vendor_id);
		$criteria->compare('outlet_id', $this->outlet_id);
		$criteria->compare('status', $this->status);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('credit_note_id', $this->credit_note_id);
		$criteria->compare('create_user_id', $this->create_user_id);
		$criteria->compare('updated_by', $this->updated_by);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}

	public function listsearch() {
		$criteria = new CDbCriteria;
        $criteria->order = ('id DESC');
		$criteria->addInCondition('status',array(ItemReturn::STATUS_DONE,PurchaseBill::STATUS_RECEIVED));
		$criteria->compare('id', $this->id);
		$criteria->compare('discount_amt', $this->discount_amt);
		$criteria->compare('other_charge', $this->other_charge);
		$criteria->compare('total_amt', $this->total_amt, true);
		$criteria->compare('vendor_id', $this->vendor_id);
		$criteria->compare('outlet_id', $this->outlet_id);
		$criteria->compare('status', $this->status);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('credit_note_id', $this->credit_note_id);
		$criteria->compare('create_user_id', $this->create_user_id);
		$criteria->compare('updated_by', $this->updated_by);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
	
	public function reportsearch() {
		$criteria = new CDbCriteria ();
		
		$criteria->compare('id', $this->id);
		$criteria->compare('discount_amt', $this->discount_amt);
		$criteria->compare('other_charge', $this->other_charge);
		$criteria->compare('total_amt', $this->total_amt, true);
		$criteria->compare('vendor_id', $this->vendor_id);
		$criteria->compare('outlet_id', $this->outlet_id);
		$criteria->compare('status', $this->status);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('credit_note_id', $this->credit_note_id);
		$criteria->compare('create_user_id', $this->create_user_id);
		$criteria->compare('updated_by', $this->updated_by);
	
		return new CActiveDataProvider ( $this, array (
				'criteria' => $criteria
		) );
	}
	
	 public function defaultScope()

    {

        return array();

    }
	
}