<?php


 
/**
 * This is the model base class for the table "{{vendor_schemes}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "VendorSchemes".
 *
 * Columns in table "{{vendor_schemes}}" available as properties of the model,
 * followed by relations of table "{{vendor_schemes}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $vendor_id
 * @property integer $item_id
 * @property integer $total_sale
 * @property string $start_date
 * @property string $end_date
 * @property double $discount
 * @property integer $type_id
 * @property integer $status
 * @property string $create_time
 * @property string $update_time
 * @property integer $create_user_id
 * @property integer $updated_by
 *
 * @property User $createUser
 * @property Item $item
 * @property User $updatedBy
 * @property Vendor $vendor
 */
abstract class BaseVendorSchemes extends GxActiveRecord {

	public static function getTypeOptions($id = null)
	{
		$list = array("% Type","Amount Type");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
 	
	public static function getStatusOptions($id = null)
	{
		$list = array("Active","InActive");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}	
	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
			if ( !isset( $this->create_time )) $this->create_time = new CDbExpression('NOW()');
				if ( !isset( $this->create_user_id )) $this->create_user_id = Yii::app()->user->id;			
	}else{
					}
		return parent::beforeValidate();
	}

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{vendor_schemes}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'VendorSchemes|VendorSchemes', $n);
	}

	public static function representingColumn() {
		return 'start_date';
	}

	public function rules() {
		return array(
			array('vendor_id, item_id, total_sale, create_user_id', 'required'),
			array('vendor_id, total_sale, type_id, status, create_user_id, updated_by', 'numerical', 'integerOnly'=>true),
			array('discount', 'numerical'),
			array('start_date, end_date, create_time, update_time', 'safe'),
			array('start_date, end_date, discount, type_id, status, create_time, update_time, updated_by', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, vendor_id, item_id, total_sale, start_date, end_date, discount, type_id, status, create_time, update_time, create_user_id, updated_by', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'createUser' => array(self::BELONGS_TO, 'User', 'create_user_id'),
			'item' => array(self::BELONGS_TO, 'Item', 'item_id'),
			'updatedBy' => array(self::BELONGS_TO, 'User', 'updated_by'),
			'vendor' => array(self::BELONGS_TO, 'Vendor', 'vendor_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'vendor_id' =>  Yii::t('app', 'Vendor'),
			'item_id' =>  Yii::t('app', 'Item'),
			'total_sale' => Yii::t('app', 'Total Sale'),
			'start_date' => Yii::t('app', 'Start Date'),
			'end_date' => Yii::t('app', 'End Date'),
			'discount' => Yii::t('app', 'Discount'),
			'type_id' => Yii::t('app', 'Type'),
			'status' => Yii::t('app', 'Status'),
			'create_time' => Yii::t('app', 'Create Time'),
			'update_time' => Yii::t('app', 'Update Time'),
			'create_user_id' => null,
			'updated_by' => null,
			'createUser' =>Yii::t('app', 'Created By'),
				'updatedBy' =>Yii::t('app', 'Updated By'),
			'item' => null,
			
			'vendor' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('vendor_id', $this->vendor_id);
		$criteria->compare('item_id', $this->item_id);
		$criteria->compare('total_sale', $this->total_sale);
		$criteria->compare('start_date', $this->start_date, true);
		$criteria->compare('end_date', $this->end_date, true);
		$criteria->compare('discount', $this->discount);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('status', $this->status);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('update_time', $this->update_time, true);
		$criteria->compare('create_user_id', $this->create_user_id);
		$criteria->compare('updated_by', $this->updated_by);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}