<?php


 
/**
 * This is the model base class for the table "{{state}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "State".
 *
 * Columns in table "{{state}}" available as properties of the model,
 * followed by relations of table "{{state}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $title
 * @property integer $status
 * @property integer $type_id
 * @property integer $country_id
 * @property string $create_time
 * @property string $update_time
 * @property integer $create_user_id
 * @property integer $updated_by
 *
 * @property City[] $cities
 * @property Order[] $orders
 * @property OrderHold[] $orderHolds
 * @property OrderRefund[] $orderRefunds
 * @property Organization[] $organizations
 * @property Outlet[] $outlets
 * @property Country $country
 * @property User $createUser
 * @property User $updatedBy
 * @property Vendor[] $vendors
 */
abstract class BaseState extends GxActiveRecord {

	
	const STATUS_ACTIVE = 0;
	const STATUS_INACTIVE = 1;
	public static function getStatusOptions($id = null)
	{
		$list = array("Active","InActive");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
	public static function getTypeOptions($id = null)
	{
		$list = array("TYPE1","TYPE2","TYPE3");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
 	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
			if ( !isset( $this->create_time )) $this->create_time = new CDbExpression('NOW()');
				if ( !isset( $this->create_user_id )) $this->create_user_id = Yii::app()->user->id;			
	}else{
					}
		return parent::beforeValidate();
	}

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{state}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'State|States', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('title, create_user_id', 'required'),
			array('status, type_id, country_id, create_user_id, updated_by', 'numerical', 'integerOnly'=>true),
			array('title', 'length', 'max'=>255),
			array('create_time, update_time', 'safe'),
			array('status, type_id, country_id, create_time, update_time, updated_by', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, title, status, type_id, country_id, create_time, update_time, create_user_id, updated_by', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'cities' => array(self::HAS_MANY, 'City', 'state_id'),
			'orders' => array(self::HAS_MANY, 'Order', 'state_id'),
			'orderHolds' => array(self::HAS_MANY, 'OrderHold', 'state_id'),
			'orderRefunds' => array(self::HAS_MANY, 'OrderRefund', 'state_id'),
			'organizations' => array(self::HAS_MANY, 'Organization', 'state_id'),
			'outlets' => array(self::HAS_MANY, 'Outlet', 'state_id'),
			'country' => array(self::BELONGS_TO, 'Country', 'country_id'),
			'createUser' => array(self::BELONGS_TO, 'User', 'create_user_id'),
			'updatedBy' => array(self::BELONGS_TO, 'User', 'updated_by'),
			'vendors' => array(self::HAS_MANY, 'Vendor', 'state_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'title' => Yii::t('app', 'Title'),
			'status' => Yii::t('app', 'Status'),
			'type_id' => Yii::t('app', 'Type'),
			'country_id' => null,
			'create_time' => Yii::t('app', 'Create Time'),
			'update_time' => Yii::t('app', 'Update Time'),
			'create_user_id' => null,
			'updated_by' => null,
			'cities' => null,
			'orders' => null,
			'orderHolds' => null,
			'orderRefunds' => null,
			'organizations' => null,
			'outlets' => null,
			'country' => null,
			'createUser' => null,
			'updatedBy' => null,
			'vendors' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('country_id', $this->country_id);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('update_time', $this->update_time, true);
		$criteria->compare('create_user_id', $this->create_user_id);
		$criteria->compare('updated_by', $this->updated_by);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}