<?php

 
/**
 * This is the model base class for the table "{{purchase_order_detail}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PurchaseOrderDetail".
 *
 * Columns in table "{{purchase_order_detail}}" available as properties of the model,
 * followed by relations of table "{{purchase_order_detail}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $req_qty
 * @property integer $bal_qty
 * @property integer $status
 * @property integer $type_id
 * @property double $charge_amount
 * @property double $extra_charges
 * @property string $remarks
 * @property string $create_time
 * @property string $update_time
 * @property integer $create_user_id
 * @property integer $updated_by
 * @property integer $item_detail_id
 * @property integer $item_id
 * @property integer $purchase_order_id
 * @property integer $outlet_id
 *
 * @property User $createUser
 * @property ItemDetail $itemDetail
 * @property Outlet $outlet
 * @property PurchaseOrder $purchaseOrder
 * @property User $updatedBy
 */
abstract class BasePurchaseOrderDetail extends GxActiveRecord {

	public $start_date;
	public $mrp;
	public $vendor_id;
	public $salerate;
	public $vat;
	public $discount;
	public $discount_amt;
	public $other_charge;
	public $amount;
	public $price;
	const STATUS_PENDING = 0;
	const STATUS_HALF_DONE = 2;
	const STATUS_DONE = 1;
	const STATUS_ASSIGN = 3;
	const STATUS_REJECT = 4;
	public static function getStatusOptions($id = null)
	{
		$list = array("Pending","Half Done","Done","Assigned","Rejected");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
	public static function getTypeOptions($id = null)
	{
		$list = array("TYPE1","TYPE2","TYPE3");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
 	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
			if ( !isset( $this->create_time )) $this->create_time = new CDbExpression('NOW()');
				if ( !isset( $this->create_user_id )) $this->create_user_id = Yii::app()->user->id;			
	}else{
					}
		return parent::beforeValidate();
	}

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{purchase_order_detail}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PurchaseOrderDetail|PurchaseOrderDetails', $n);
	}

	public static function representingColumn() {
		return 'remarks';
	}

	public function rules() {
		return array(
			array('req_qty, item_detail_id, item_id, purchase_order_id', 'required'),
			array('status, type_id, create_user_id, updated_by, item_detail_id, item_id, purchase_order_id, outlet_id', 'numerical', 'integerOnly'=>true),
			array('charge_amount, extra_charges', 'numerical'),
			array('remarks,margin,create_time, update_time,start_date,igst_amt,igst_per,discount1,discount_amt1,approved_qty,item_id,mrp,sale_rate,discount,discount_amt,other_charge,amount,price,tax_id,other_charge,cgst_per,sgst_per,cess_per,cgst_amt,sgst_amt,cess_amt,vendor_id', 'safe'),
			array('bal_qty, status, type_id, charge_amount, extra_charges, remarks, create_time, update_time, updated_by, outlet_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, req_qty, bal_qty, status, type_id, charge_amount, extra_charges, remarks, create_time, update_time, create_user_id, updated_by, item_detail_id, item_id, purchase_order_id, outlet_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'createUser' => array(self::BELONGS_TO, 'User', 'create_user_id'),
			'itemDetail' => array(self::BELONGS_TO, 'ItemDetail', 'item_detail_id'),
			'outlet' => array(self::BELONGS_TO, 'Outlet', 'outlet_id'),
				'item' => array(self::BELONGS_TO, 'Item', 'item_id'),
			'purchaseOrder' => array(self::BELONGS_TO, 'PurchaseOrder', 'purchase_order_id'),
				'tax' => array(self::BELONGS_TO, 'Tax', 'tax_id'),
			'updatedBy' => array(self::BELONGS_TO, 'User', 'updated_by'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'req_qty' => Yii::t('app', 'Max Qty'),
			'bal_qty' => Yii::t('app', 'Bal Qty'),
			'status' => Yii::t('app', 'Status'),
			'type_id' => Yii::t('app', 'Type'),
			'charge_amount' => Yii::t('app', 'Charge Amount'),
			'extra_charges' => Yii::t('app', 'Extra Charges'),
			'remarks' => Yii::t('app', 'Remarks'),
			'create_time' => Yii::t('app', 'Create Time'),
			'update_time' => Yii::t('app', 'Update Time'),
			'create_user_id' => null,
			'updated_by' => null,
			'item_detail_id' => null,
			'discount' => Yii::t('app', 'Discount(%)'),
			'discount_amt' => Yii::t('app', 'Discount Amount'),
			'item_id' => Yii::t('app', 'Item'),
			'vendor_id' => Yii::t('app', 'Vendor'),
			'purchase_order_id' => null,
			'outlet_id' => null,
			'createUser' => null,
			'itemDetail' => null,
			'outlet' => null,
			'purchaseOrder' => null,
			'updatedBy' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;
		$criteria->with = 'item';
		$criteria->order = 'item.title asc';
		$purchase_order_ids = array();
		$criteria1 = new CDbCriteria;
		if($this->start_date != null){
			$criteria1->compare('start_date', $this->start_date);
		}
		if($this->vendor_id != null){
			$criteria1->compare('vendor_id', $this->vendor_id);
		}
		
		$criteria1->addCondition('status !='.PurchaseOrderDetail::STATUS_DONE);
		$purchaseorders= PurchaseOrder::model()->findAll($criteria1);
		Yii::log ( CVarDumper::dumpAsString ( $purchaseorders ), CLogger::LEVEL_WARNING, '$mrss' );
		if($purchaseorders){
			foreach($purchaseorders as $purchaseorder){
				$purchase_order_ids[] = $purchaseorder->id;
			}
		
		}
		$criteria->addInCondition('t.purchase_order_id', $purchase_order_ids);
		$criteria->addCondition('t.status !='.PurchaseOrderDetail::STATUS_DONE);
		$criteria->compare('t.id', $this->id);
		$criteria->compare('t.req_qty', $this->req_qty);
		$criteria->compare('t.bal_qty', $this->bal_qty);
		$criteria->compare('t.status', $this->status);
		$criteria->compare('t.type_id', $this->type_id);
		$criteria->compare('t.charge_amount', $this->charge_amount);
		$criteria->compare('t.extra_charges', $this->extra_charges);
		$criteria->compare('t.remarks', $this->remarks, true);
		$criteria->compare('t.create_time', $this->create_time, true);
		$criteria->compare('t.update_time', $this->update_time, true);
		$criteria->compare('t.create_user_id', $this->create_user_id);
		$criteria->compare('t.updated_by', $this->updated_by);
		$criteria->compare('t.item_detail_id', $this->item_detail_id);
		$criteria->compare('t.item_id', $this->item_id);
		$criteria->compare('t.purchase_order_id', $this->purchase_order_id);
		$criteria->compare('t.outlet_id', $this->outlet_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,'pagination'=>false
		));
	}
	public function Pdfsearch($id) {
		$criteria = new CDbCriteria;
		$criteria->with = 'item';
		$criteria->order = 'item.title asc';
		$criteria->addCondition('t.purchase_order_id ='. $id);
		Yii::log ( CVarDumper::dumpAsString ( $id ), CLogger::LEVEL_WARNING, '$id' );
		/* $criteria->compare('id', $this->id);
		$criteria->compare('req_qty', $this->req_qty);
		$criteria->compare('bal_qty', $this->bal_qty);
		$criteria->compare('status', $this->status);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('charge_amount', $this->charge_amount);
		$criteria->compare('extra_charges', $this->extra_charges);
		$criteria->compare('remarks', $this->remarks, true);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('update_time', $this->update_time, true);
		$criteria->compare('create_user_id', $this->create_user_id);
		$criteria->compare('updated_by', $this->updated_by);
		$criteria->compare('item_detail_id', $this->item_detail_id);
		$criteria->compare('item_id', $this->item_id); */
		//$criteria->compare('purchase_order_id', $this->purchase_order_id);
		//$criteria->compare('outlet_id', $this->outlet_id);
	
		return new CActiveDataProvider($this, array(
				'criteria' => $criteria,'pagination'=>false
		));
	}
	public function defaultScope() {
		return array ();
	}
	
}