<?php

 
/**
 * This is the model base class for the table "{{discount}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Discount".
 *
 * Columns in table "{{discount}}" available as properties of the model,
 * followed by relations of table "{{discount}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $title
 * @property double $amount
 * @property string $start_date
 * @property string $end_date
 * @property integer $status
 * @property string $create_time
 * @property string $update_time
 * @property integer $create_user_id
 * @property integer $updated_by
 *
 * @property User $createUser
 * @property User $updatedBy
 * @property ItemDiscount[] $itemDiscounts
 * @property OrderHoldItem[] $orderHoldItems
 * @property OrderItem[] $orderItems
 * @property OrderRefundItem[] $orderRefundItems
 */
abstract class BaseDiscount extends GxActiveRecord {
    public $item_detail_id;
	public $is_time_dependent;
	const STATUS_ACTIVE = 0;
	const STATUS_INACTIVE = 1;
	
	const TYPE_AMOUNT = 0;
	const TYPE_PERCENTAGE = 1;
	
	const TIME_DEPENDENT = 1;
	
	const DISCOUNT_ORDER = 0;
	const DISCOUNT_ITEM = 1;
	
	
	public static function getStatusOptions($id = null)
	{
		$list = array("Active","Inactive");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}	
	public static function getTypeOptions($id = null)
	{
		$list = array("amount","%age");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
	public static function getDiscountTypeOptions($id = null)
	{
		$list = array("Order","Item");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
			if ( !isset( $this->create_time )) $this->create_time = date('Y-m-d H:i:s');
				if ( !isset( $this->create_user_id )) $this->create_user_id = Yii::app()->user->id;			
	}else{
		if ( !isset( $this->update_time )) $this->update_time = date('Y-m-d H:i:s');
		if ( !isset( $this->updated_by )) $this->updated_by = Yii::app()->user->id;
					}
		return parent::beforeValidate();
	}

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{discount}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Discount|Discounts', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('title,amount,applicable_amt,start_date,end_date,create_user_id,discount_type', 'required'),
			array('status, create_user_id, updated_by', 'numerical', 'integerOnly'=>true),
			array('amount', 'numerical'),
			array('item_detail_id', 'safe'),
			array('title', 'length', 'max'=>255),
			array('start_date, end_date,start_time,end_time,create_time, update_time,is_time_dependent,applicable_amt,type_id', 'safe'),
			array('amount, start_date, end_date, status, create_time, update_time, updated_by', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, title, amount,discount_type,type_id,start_date, end_date, status, create_time, update_time, create_user_id, updated_by', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'createUser' => array(self::BELONGS_TO, 'User', 'create_user_id'),
			'updatedBy' => array(self::BELONGS_TO, 'User', 'updated_by'),
			'itemDiscounts' => array(self::HAS_MANY, 'ItemDiscount', 'discount_id'),
			'orderHoldItems' => array(self::HAS_MANY, 'OrderHoldItem', 'discount_id'),
			'orderItems' => array(self::HAS_MANY, 'OrderItem', 'discount_id'),
			'orderRefundItems' => array(self::HAS_MANY, 'OrderRefundItem', 'discount_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'title' => Yii::t('app', 'Title'),
			'amount' => Yii::t('app', 'Value'),
			'start_date' => Yii::t('app', 'Start Date'),
			'end_date' => Yii::t('app', 'End Date'),
				'item_detail_id' => Yii::t('app', 'Item'),
			'applicable_amt' => Yii::t('app', 'Discount Applicable On(Amount)'),
				'discount_type' => Yii::t('app', 'Discount Type'),
				
			'start_time' => Yii::t('app', 'Start Time'),
			'end_time' => Yii::t('app', 'End Time'),
			'status' => Yii::t('app', 'Status'),
				'type_id' => Yii::t('app', 'Amount or %age'),
			'create_time' => Yii::t('app', 'Create Time'),
			'update_time' => Yii::t('app', 'Update Time'),
			'create_user_id' => null,
			'updatedBy' => Yii::t('app', 'Updated By'),
			'createUser' => Yii::t('app', 'Created By'),
			'is_time_dependent' => Yii::t('app', 'Is time Dependent'),
				
			'itemDiscounts' => null,
			'orderHoldItems' => null,
			'orderItems' => null,
			'orderRefundItems' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('amount', $this->amount);
		$criteria->compare('start_date', $this->start_date, true);
		$criteria->compare('end_date', $this->end_date, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('discount_type', $this->discount_type);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('update_time', $this->update_time, true);
		$criteria->compare('create_user_id', $this->create_user_id);
		$criteria->compare('updated_by', $this->updated_by);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}