<?php

/**
 * This is the model base class for the table "{{item_tax}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ItemTax".
 *
 * Columns in table "{{item_tax}}" available as properties of the model,
 * followed by relations of table "{{item_tax}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $item_detail_id
 * @property integer $tax_id
 * @property integer $status
 * @property integer $type_id
 * @property string $create_time
 * @property integer $create_user_id
 * @property integer $updated_by
 *
 * @property User $createUser
 * @property ItemDetail $itemDetail
 * @property Tax $tax
 * @property User $updatedBy
 */
abstract class BaseItemTax extends GxActiveRecord {
	public $columns;
	public $item_id;
	public $sale_rate;
	public $match_total_tax;
	public $match_cgst;
	public $match_sgst_tax;
	public $match_cess_tax;
	public static function getStatusOptions($id = null) {
		$list = array (
				"Draft",
				"Published",
				"Archive" 
		);
		if ($id == null)
			return $list;
		if (is_numeric ( $id ))
			return $list [$id];
		return $id;
	}
	public static function getTypeOptions($id = null) {
		$list = array (
				"TYPE1",
				"TYPE2",
				"TYPE3" 
		);
		if ($id == null)
			return $list;
		if (is_numeric ( $id ))
			return $list [$id];
		return $id;
	}
	public function beforeValidate() {
		if ($this->isNewRecord) {
			if (! isset ( $this->create_time ))
				$this->create_time = new CDbExpression ( 'NOW()' );
			if (! isset ( $this->create_user_id ))
				$this->create_user_id = Yii::app ()->user->id;
		} else {
		}
		return parent::beforeValidate ();
	}
	public static function model($className = __CLASS__) {
		return parent::model ( $className );
	}
	public function tableName() {
		return '{{item_tax}}';
	}
	public static function label($n = 1) {
		return Yii::t ( 'app', 'ItemTax|ItemTaxes', $n );
	}
	public static function representingColumn() {
		return 'create_time';
	}
	public function rules() {
		return array (
				array (
						'item_detail_id, tax_id, create_time, create_user_id',
						'required' 
				),
				array (
						'item_detail_id, tax_id, status, type_id, create_user_id, updated_by',
						'numerical',
						'integerOnly' => true 
				),
				array (
						'columns,item_id',
						'safe' 
				),
				array (
						'status, type_id, updated_by',
						'default',
						'setOnEmpty' => true,
						'value' => null 
				),
				array (
						'match_sgst_tax,match_cess_tax,match_cgst,match_total_tax,sale_rate,id, item_detail_id, tax_id, status, type_id, create_time, create_user_id, updated_by',
						'safe',
						'on' => 'search' 
				) 
		);
	}
	public function relations() {
		return array (
				'createUser' => array (
						self::BELONGS_TO,
						'User',
						'create_user_id' 
				),
				'itemDetail' => array (
						self::BELONGS_TO,
						'ItemDetail',
						'item_detail_id' 
				),
				'tax' => array (
						self::BELONGS_TO,
						'Tax',
						'tax_id' 
				),
				'updatedBy' => array (
						self::BELONGS_TO,
						'User',
						'updated_by' 
				) 
		);
	}
	public function pivotModels() {
		return array ();
	}
	public function attributeLabels() {
		return array (
				'id' => Yii::t ( 'app', 'ID' ),
				'item_detail_id' => null,
				'tax_id' => null,
				'status' => Yii::t ( 'app', 'Status' ),
				'type_id' => Yii::t ( 'app', 'Type' ),
				'create_time' => Yii::t ( 'app', 'Create Time' ),
				'create_user_id' => null,
				'updated_by' => null,
				'createUser' => null,
				'itemDetail' => null,
				'tax' => null,
				'updatedBy' => null 
		);
	}
	public function search() {
		$criteria = new CDbCriteria ();
		
		// $criteria->alias = 'itemTax as t';
		
		// $criteria->compare('t.id', $this->id);
		
		$criteria->with = array (
				'itemDetail' => array (
						'with' => array (
								'item' 
						) 
				),
				'tax' 
		);
		
		$criteria->compare ( 'itemDetail.bar_code', $this->item_detail_id, true );
		
		$criteria->compare ( 'item.title', $this->item_id, true );
		$criteria->compare ( 'item.sale_price', $this->sale_rate );
		
		$criteria->compare ( 'tax.tax_val1', $this->match_cgst, true );
		$criteria->compare ( 'tax.hrn_code', $this->match_total_tax, true );
		$criteria->compare ( 'tax.tax_val2', $this->match_sgst_tax, true );
		$criteria->compare ( 'tax.tax_val3', $this->match_cess_tax, true );
		
		$criteria->compare ( 't.tax_id', $this->tax_id );
		$criteria->compare ( 't.status', $this->status );
		$criteria->compare ( 't.type_id', $this->type_id );
		$criteria->compare ( 't.create_time', $this->create_time, true );
		$criteria->compare ( 't.create_user_id', $this->create_user_id );
		$criteria->compare ( 't.updated_by', $this->updated_by );
		
		return new CActiveDataProvider ( $this, array (
				'criteria' => $criteria,
				'sort' => array (
						'defaultOrder' => 't.id DESC' 
				) 
		) );
	}
	public function defaultScope() {
		return array ();
	}
}