<?php


 
/**
 * This is the model base class for the table "{{order_hold_item}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "OrderHoldItem".
 *
 * Columns in table "{{order_hold_item}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $order_hold_id
 * @property integer $item_detail_id
 * @property integer $qty
 * @property double $price
 * @property integer $discount_id
 * @property double $discount_amt
 * @property integer $status
 * @property integer $type_id
 * @property string $create_time
 * @property string $update_time
 * @property integer $create_user_id
 * @property integer $updated_by
 *
 */
abstract class BaseOrderHoldItem extends GxActiveRecord {

	
	public static function getStatusOptions($id = null)
	{
		$list = array("Draft","Published","Archive");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}	
	public static function getTypeOptions($id = null)
	{
		$list = array("TYPE1","TYPE2","TYPE3");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
 	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
			if ( !isset( $this->create_time )) $this->create_time = new CDbExpression('NOW()');
				if ( !isset( $this->create_user_id )) $this->create_user_id = Yii::app()->user->id;			
	}else{
					}
		return parent::beforeValidate();
	}

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{order_hold_item}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'OrderHoldItem|OrderHoldItems', $n);
	}

	public static function representingColumn() {
		return 'create_time';
	}

	public function rules() {
		return array(
			array('create_user_id', 'required'),
			array('order_hold_id, item_detail_id, discount_id, status, type_id, create_user_id, updated_by', 'numerical', 'integerOnly'=>true),
			array('price, discount_amt', 'numerical'),
			array('create_time, update_time,item_id,cgst_per,sgst_per,igst_per,cess_per,cgst_amt,sgst_amt,cess_amt,igst_amt,sale_rate,total_amt', 'safe'),
			array('order_hold_id, item_detail_id, qty, price, discount_id, discount_amt, status, type_id, create_time, update_time, updated_by', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, order_hold_id, item_detail_id, qty, price, discount_id, discount_amt, status, type_id, create_time, update_time, create_user_id, updated_by', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
				'createUser' => array(self::BELONGS_TO, 'User', 'create_user_id'),
				'discount' => array(self::BELONGS_TO, 'Discount', 'discount_id'),
				'itemDetail' => array(self::BELONGS_TO, 'ItemDetail', 'item_detail_id'),
				'item' => array(self::BELONGS_TO, 'Item', 'item_id'),
				'order' => array(self::BELONGS_TO, 'OrderHold', 'order_id'),
				'updatedBy' => array(self::BELONGS_TO, 'User', 'updated_by'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'order_hold_id' => Yii::t('app', 'Order Hold'),
			'item_detail_id' => Yii::t('app', 'Item Detail'),
			'qty' => Yii::t('app', 'Qty'),
			'price' => Yii::t('app', 'Price'),
				'item_id' => Yii::t('app', 'Item'),
			'discount_id' => Yii::t('app', 'Discount'),
			'discount_amt' => Yii::t('app', 'Discount Amt'),
			'status' => Yii::t('app', 'Status'),
			'type_id' => Yii::t('app', 'Type'),
			'create_time' => Yii::t('app', 'Create Time'),
			'update_time' => Yii::t('app', 'Update Time'),
			'create_user_id' => Yii::t('app', 'Create User'),
			'updated_by' => Yii::t('app', 'Updated By'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('order_hold_id', $this->order_hold_id);
		$criteria->compare('item_detail_id', $this->item_detail_id);
		$criteria->compare('item_id', $this->item_id);
		$criteria->compare('qty', $this->qty);
		$criteria->compare('price', $this->price);
		$criteria->compare('discount_id', $this->discount_id);
		$criteria->compare('discount_amt', $this->discount_amt);
		$criteria->compare('status', $this->status);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('update_time', $this->update_time, true);
		$criteria->compare('create_user_id', $this->create_user_id);
		$criteria->compare('updated_by', $this->updated_by);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}