<?php


/**
 * This is the model base class for the table "{{b2bpurchase_bill_detail}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PurchaseBillDetail".
 *
 * Columns in table "{{b2bpurchase_bill_detail}}" available as properties of the model,
 * followed by relations of table "{{b2bpurchase_bill_detail}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $req_qty
 * @property integer $bal_qty
 * @property integer $approved_qty
 * @property double $mrp
 * @property double $price
 * @property double $discount
 * @property double $discount_amt
 * @property double $tax_id
 * @property double $other_charge
 * @property double $amount
 * @property double $sale_rate
 * @property integer $status
 * @property integer $type_id
 * @property double $charge_amount
 * @property double $extra_charges
 * @property string $remarks
 * @property string $create_time
 * @property string $update_time
 * @property integer $create_user_id
 * @property integer $updated_by
 * @property integer $item_detail_id
 * @property integer $purchase_bill_id
 * @property integer $outlet_id
 *
 * @property User $createUser
 * @property ItemDetail $itemDetail
 * @property Outlet $outlet
 * @property PurchaseBill $purchaseBill
 * @property User $updatedBy
 */
abstract class BaseB2bPurchaseBillDetail extends GxActiveRecord {
	public $expiry_date;
	public $packing_date;
	public $columns;
	public $start_date;
	public $tax_amount;
	public $end_date;
	public $min_amt;
	public $max_amt;
	public $tally_start_date;
	public $tally_end_date;
	public $bill_date;
	public $bill_no;
	public $vendor_id;
	public $bar_code;
	public $bill_amount;
	public $item_val_id;
	public $vendor;
	
	const STATUS_PENDING = 0;
	const STATUS_RECEIVED = 1;
	const STATUS_APPROVED = 2;
	public static function getFreeItemOptions($id = null) {
		$list = array (
				"No",
				"Yes",
				
		);
		if ($id == null)
			return $list;
			if (is_numeric ( $id ))
				return $list [$id];
				return $id;
	}
	public static function getStatusOptions($id = null) {
		$list = array (
				"Pending",
				"Received",
				"Approved",
		);
		if ($id == null)
			return $list;
		if (is_numeric ( $id ))
			return $list [$id];
		return $id;
	}
	public static function getTypeOptions($id = null) {
		$list = array (
				"TYPE1",
				"TYPE2",
				"TYPE3" 
		);
		if ($id == null)
			return $list;
		if (is_numeric ( $id ))
			return $list [$id];
		return $id;
	}
	public function beforeValidate() {
		if ($this->isNewRecord) {
			if (! isset ( $this->create_time ))
				$this->create_time = new CDbExpression ( 'NOW()' );
			if (! isset ( $this->create_user_id ))
				$this->create_user_id = Yii::app ()->user->id;
		} else {
			$this->update_time = new CDbExpression ( 'NOW()' );
		}
		return parent::beforeValidate ();
	}
	public static function model($className = __CLASS__) {
		return parent::model ( $className );
	}
	public function tableName() {
		return '{{b2bpurchase_bill_detail}}';
	}
	public static function label($n = 1) {
		return Yii::t ( 'app', 'B2B PurchaseBillDetail|B2B PurchaseBillDetails', $n );
	}
	public static function representingColumn() {
		return 'remarks';
	}
	public function rules() {
		return array (
				array('req_qty, item_detail_id, item_id, purchase_bill_id', 'required'),
				array (
						'status, type_id, create_user_id, updated_by, item_detail_id, purchase_bill_id, outlet_id',
						'numerical',
						'integerOnly' => true 
				),
				array (
						'mrp, price, discount, discount_amt, tax_id, other_charge, amount, sale_rate, charge_amount, extra_charges',
						'numerical' 
				),
				array (
						'hsn_code,item_val_id,grn_refrence_no,bar_code,tally_start_date,tally_end_date,start_date,remarks,is_free,order,margin,expiry_date,packing_date,vendor_id,create_time,columns,igst_amt,igst_per,update_time,discount1,discount_amt1,start_date,approved_qty,item_id,mrp,tax_id,other_charge,sale_rate,discount,discount_amt,other_charge,amount,price,cgst_per,sgst_per,cess_per,cgst_amt,sgst_amt,cess_amt,end_date,min_amt,max_amt,tax_amount,bill_amount,vendor',
						'safe' 
				),
				array (
						'bal_qty, status, type_id, charge_amount, extra_charges, remarks, create_time, update_time, updated_by,end_date, outlet_id',
						'default',
						'setOnEmpty' => true,
						'value' => null 
				),
				array (
						'id, req_qty, bal_qty, approved_qty, mrp, price, discount, discount_amt, tax_id, other_charge, amount, sale_rate, status, type_id, charge_amount, extra_charges, remarks, create_time, update_time, create_user_id, updated_by, item_detail_id, purchase_bill_id,end_date,outlet_id,tax_amount,bill_amount,vendor',
						'safe',
						'on' => 'search' 
				) 
		);
	}
	public function relations() {
		return array (
				'createUser' => array (
						self::BELONGS_TO,
						'User',
						'create_user_id' 
				),
				'itemDetail' => array (
						self::BELONGS_TO,
						'ItemDetail',
						'item_detail_id' 
				),
				'b2bPurchaseBill' => array (
						self::BELONGS_TO,
						'B2bPurchaseBill',
						'purchase_bill_id' 
				),
				'item' => array (
						self::BELONGS_TO,
						'Item',
						'item_id' 
				),
				'outlet' => array (
						self::BELONGS_TO,
						'Outlet',
						'outlet_id' 
				),
				'tax' => array (
						self::BELONGS_TO,
						'Tax',
						'tax_id' 
				),
				'purchaseBill' => array (
						self::BELONGS_TO,
						'B2bPurchaseBill',
						'purchase_bill_id' 
				),
				'state' => array (
						self::BELONGS_TO,
						'State',
						'state_id' 
				),
				'updatedBy' => array (
						self::BELONGS_TO,
						'User',
						'updated_by' 
				) 
		);
	}
	public function pivotModels() {
		return array ();
	}
	public function attributeLabels() {
		return array (
				'id' => Yii::t ( 'app', 'ID' ),
				'req_qty' => Yii::t ( 'app', 'Max Qty' ),
				'bal_qty' => Yii::t ( 'app', 'Bal Qty' ),
				'approved_qty' => Yii::t ( 'app', 'Approved Qty' ),
				'mrp' => Yii::t ( 'app', 'Mrp' ),
				'price' => Yii::t ( 'app', 'Price' ),
				'discount' => Yii::t ( 'app', 'Discount' ),
				'discount_amt' => Yii::t ( 'app', 'Discount Amt' ),
				'discount1' => Yii::t ( 'app', 'Other Discount' ),
				'discount_amt1' => Yii::t ( 'app', 'Other Discount Amt' ),
				'tax_id' => Yii::t ( 'app', 'tax_id' ),
				'other_charge' => Yii::t ( 'app', 'Other Charge' ),
				'amount' => Yii::t ( 'app', 'Amount' ),
				'sale_rate' => Yii::t ( 'app', 'Sale Rate' ),
				'tally_start_date' => Yii::t ( 'app', 'Start Date' ),
				'tally_end_date' => Yii::t ( 'app', 'End Date' ),
				'end_date' => Yii::t ( 'app', 'End Date' ),
				'status' => Yii::t ( 'app', 'Status' ),
				'type_id' => Yii::t ( 'app', 'Type' ),
				'tax_id' => Yii::t ( 'app', 'Tax' ),
				'cgst_per' => Yii::t ( 'app', 'CGST(%age)' ),
				'sgst_per' => Yii::t ( 'app', 'SGST(%age)' ),
				'cess_per' => Yii::t ( 'app', 'CESS(%age)' ),
				'cgst_amt' => Yii::t ( 'app', 'CGST Amount' ),
				'sgst_amt' => Yii::t ( 'app', 'SGST Amount' ),
				'cess_amt' => Yii::t ( 'app', 'CESS Amount' ),
				'min_amt' => Yii::t ( 'app', 'Minimum Total Amount' ),
				'max_amt' => Yii::t ( 'app', 'Maximum Total Amount' ),
				'charge_amount' => Yii::t ( 'app', 'Charge Amount' ),
				'extra_charges' => Yii::t ( 'app', 'Extra Charges' ),
				'remarks' => Yii::t ( 'app', 'Remarks' ),
				'create_time' => Yii::t ( 'app', 'Create Time' ),
				'update_time' => Yii::t ( 'app', 'Update Time' ),
				'create_user_id' => null,
				'updated_by' => null,
				'item_detail_id' => null,
				'purchase_bill_id' => null,
				'outlet_id' => null,
				'vendor_id' => Yii::t('app', 'Vendor'),
				'createUser' => null,
				'itemDetail' => null,
				'item_id' => Yii::t ( 'app', 'Item Name' ),
				'outlet' => null,
				'purchaseBill' => null,
				'updatedBy' => null 
		);
	}
	
	public function reportsearch() {
		$criteria = new CDbCriteria ();
		
		$purchase_bill_ids = array();
		$criteria1 = new CDbCriteria;
		if($this->start_date != null){
			$criteria1->compare('start_date', $this->start_date);
		} 
		if($this->vendor_id != null){
			$criteria1->compare('vendor_id', $this->vendor_id);
		}
		
		$criteria1->addCondition('status ='.B2bPurchaseBill::STATUS_APPROVED);
		$purchasebills= B2bPurchaseBill::model()->findAll($criteria1);
	//	Yii::log ( CVarDumper::dumpAsString ( $purchasebills ), CLogger::LEVEL_WARNING, '$mrss' );
		if($purchasebills){
			foreach($purchasebills as $purchasebill){
				$purchase_bill_ids[] = $purchasebill->id;
			}
	
		}
		
		$criteria->group = 'purchase_bill_id,tax_id';
		$criteria->addInCondition('purchase_bill_id', $purchase_bill_ids);
		Yii::log ( CVarDumper::dumpAsString ( Yii::app ()->session ['tally_start_date'] ), CLogger::LEVEL_WARNING, 'start_date' );
		Yii::log ( CVarDumper::dumpAsString ( Yii::app ()->session ['tally_start_date'] ), CLogger::LEVEL_WARNING, 'end_date' );
		if ((Yii::app ()->session ['tally_start_date'] != '') && (Yii::app ()->session ['tally_end_date'] != '')) {
			$criteria->addBetweenCondition ( 'date(create_time)', Yii::app ()->session ['tally_start_date'], Yii::app ()->session ['tally_end_date'] );
		}
		$criteria->compare ( 'id', $this->id );
		$criteria->compare ( 'req_qty', $this->req_qty );
		$criteria->compare ( 'bal_qty', $this->bal_qty );
		$criteria->compare ( 'approved_qty', $this->approved_qty );
		$criteria->compare ( 'mrp', $this->mrp );
		$criteria->compare ( 'price', $this->price );
		$criteria->compare ( 'discount', $this->discount );
		$criteria->compare ( 'discount_amt', $this->discount_amt );
		$criteria->compare ( 'tax_id', $this->tax_id );
		$criteria->compare ( 'other_charge', $this->other_charge );
		$criteria->compare ( 'amount', $this->amount );
		$criteria->compare ( 'sale_rate', $this->sale_rate );
		$criteria->compare ( 'status', $this->status );
		$criteria->compare ( 'type_id', $this->type_id );
		$criteria->compare ( 'charge_amount', $this->charge_amount );
		$criteria->compare ( 'extra_charges', $this->extra_charges );
		$criteria->compare ( 'remarks', $this->remarks, true );
	//	$criteria->compare ( 'create_time', $this->create_time, true );
	//	$criteria->compare ( 'update_time', $this->update_time, true );
		$criteria->compare ( 'create_user_id', $this->create_user_id );
		$criteria->compare ( 'updated_by', $this->updated_by );
		$criteria->compare ( 'item_detail_id', $this->item_detail_id );
		$criteria->compare ( 'item_id', $this->item_id );
		$criteria->compare ( 'purchase_bill_id', $this->purchase_bill_id );
		$criteria->compare ( 'outlet_id', $this->outlet_id );
	
		return new CActiveDataProvider ( $this, array (
				'criteria' => $criteria
		) );
	}
	public function search() {
		$criteria = new CDbCriteria ();
	
		$purchase_bill_ids = array();
		$criteria1 = new CDbCriteria;
		$user = Yii::app()->user->model;
		$role_id = $user->role_id;
		
		if($this->start_date != null){
			$criteria1->compare('start_date', $this->start_date);
		}
		
		if($this->vendor_id != null){
			$criteria1->compare('vendor_id', $this->vendor_id);
		}
		
		//$criteria1->addCondition('status ='.PurchaseBill::STATUS_UNAPPROVED);
		$criteria1->addCondition('status !='.B2bPurchaseBill::STATUS_APPROVED);
		$purchasebills= B2bPurchaseBill::model()->findAll($criteria1);
		
		
		
		//Yii::log ( CVarDumper::dumpAsString ( $purchasebills ), CLogger::LEVEL_WARNING, '$mrss' );
		if($purchasebills){
			foreach($purchasebills as $purchasebill){
				$purchase_bill_ids[] = $purchasebill->id;
			}
		
		}
		
		$criteria->addInCondition('purchase_bill_id', $purchase_bill_ids);
		$criteria->compare ( 't.id', $this->id );
		$criteria->compare ( 't.req_qty', $this->req_qty );
		$criteria->compare ( 't.bal_qty', $this->bal_qty );
		$criteria->compare ( 't.approved_qty', $this->approved_qty );
		$criteria->compare ( 't.mrp', $this->mrp );
		$criteria->compare ( 't.price', $this->price );
		$criteria->compare ( 't.discount', $this->discount );
		$criteria->compare ( 't.discount_amt', $this->discount_amt );
		$criteria->compare ( 't.tax_id', $this->tax_id );
		$criteria->compare ( 't.other_charge', $this->other_charge );
		$criteria->compare ( 't.amount', $this->amount );
		$criteria->compare ( 't.sale_rate', $this->sale_rate );
		$criteria->compare ( 't.status', $this->status );
		$criteria->compare ( 't.type_id', $this->type_id );
		$criteria->compare ( 't.charge_amount', $this->charge_amount );
		$criteria->compare ( 't.extra_charges', $this->extra_charges );
		$criteria->compare ( 't.remarks', $this->remarks, true );
		$criteria->compare ( 't.create_time', $this->create_time, true );
		$criteria->compare ( 't.update_time', $this->update_time, true );
		$criteria->compare ( 't.create_user_id', $this->create_user_id );
		$criteria->compare ( 't.updated_by', $this->updated_by );
		$criteria->compare ( 't.item_detail_id', $this->item_detail_id );
		$criteria->compare ( 't.purchase_bill_id', $this->purchase_bill_id );
		$criteria->compare ( 't.outlet_id', $this->outlet_id );
		
		return new CActiveDataProvider ( $this, array (
				'criteria' => $criteria ,'pagination'=>false,
				 'sort'=>array(
						'defaultOrder'=>'t.order Asc',
				), 
		) );
	}
	
	public function purchasesearch() {
		$criteria = new CDbCriteria ();
	
		
		$criteria->with = array (
				'itemDetail',
				'item'
		);
		
		$criteria->compare ( 'itemDetail.bar_code', $this->item_detail_id, true );
		$criteria->compare ( 'item.title', $this->item_id, true );
		$criteria->compare ( 't.req_qty', $this->req_qty );
		$criteria->compare ( 't.bal_qty', $this->bal_qty );
		$criteria->compare ( 't.approved_qty', $this->approved_qty );
		$criteria->compare ( 't.mrp', $this->mrp );
		$criteria->compare ( 't.price', $this->price );
		$criteria->compare ( 't.discount', $this->discount );
		$criteria->compare ( 't.discount_amt', $this->discount_amt );
		$criteria->compare ( 't.discount1', $this->discount1 );
		$criteria->compare ( 't.discount_amt1', $this->discount_amt1 );
		$criteria->compare ( 't.tax_id', $this->tax_id );
		$criteria->compare ( 't.other_charge', $this->other_charge );
		$criteria->compare ( 't.amount', $this->amount );
		$criteria->compare ( 't.sale_rate', $this->sale_rate );
		$criteria->compare ( 't.status', $this->status );
		$criteria->compare ( 't.type_id', $this->type_id );
		$criteria->compare ( 't.igst_per', $this->igst_per, true );
		$criteria->compare ( 't.cgst_per', $this->cgst_per, true );
		$criteria->compare ( 't.sgst_per', $this->sgst_per, true );
		$criteria->compare ( 't.cess_per', $this->cess_per , true);
		$criteria->compare ( 't.igst_amt', $this->igst_amt, true );
		$criteria->compare ( 't.cgst_amt', $this->cgst_amt, true );
		$criteria->compare ( 't.sgst_amt', $this->sgst_amt, true );
		$criteria->compare ( 't.cess_amt', $this->cess_amt, true );
		$criteria->compare ( 't.charge_amount', $this->charge_amount );
		$criteria->compare ( 't.extra_charges', $this->extra_charges );
		$criteria->compare ( 't.remarks', $this->remarks, true );
		$criteria->compare ( 't.create_time', $this->create_time, true );
		$criteria->compare ( 't.update_time', $this->update_time, true );
		$criteria->compare ( 't.create_user_id', $this->create_user_id );
		$criteria->compare ( 't.updated_by', $this->updated_by );
		
		$criteria->compare ( 't.purchase_bill_id', $this->purchase_bill_id );
		$criteria->compare ( 't.outlet_id', $this->outlet_id );
	
		return new CActiveDataProvider ( $this, array (
				'criteria' => $criteria,
				'pagination' => array (
						'pageSize' => '100'
				),
				'sort'=>array(
						'defaultOrder'=>'t.order Asc',
				),
		) );
	}
	public function itemwisesearch() {
		$criteria = new CDbCriteria;

		$criteria->with = array('itemDetail','item','b2bPurchaseBill');
		$criteria->select ='t.*, SUM(t.approved_qty) AS approved_qty, SUM(t.amount) AS amount ';
		$criteria->addCondition('b2bPurchaseBill.status ='. B2bPurchaseBill::STATUS_APPROVED);
		$criteria->group = 'item_detail_id';
		if ((Yii::app ()->session ['start_date'] != '') && (Yii::app ()->session ['end_date'] != '')) {
			$order_ids = array();
			$criteria1 = new CDbCriteria();
			$criteria1->addBetweenCondition ( 't.start_date', Yii::app ()->session ['start_date'], Yii::app ()->session ['end_date'] );
			$criteria1->addCondition('status ='. B2bPurchaseBill::STATUS_APPROVED);
			$B2bPurchaseBill = B2bPurchaseBill::model()->findAll($criteria1);
			
			
			
			// echo"<pre>"; print_r($B2bPurchaseBill); die;
			if($B2bPurchaseBill){
				foreach($B2bPurchaseBill as $order){
					$order_ids[] = $order->id;
				}
			}
			$criteria->addInCondition('t.purchase_bill_id',$order_ids);
			
		}
		
		
		
	
		if(!empty(Yii::app()->session['item_id'])){
			$criteria->addInCondition('item.id', Yii::app()->session['item_id']);
		}else{
			$criteria->compare('item.title', $this->item_id ,true);
		}
		// $criteria->compare('order.customer_id', $this->customer_id);
		$criteria->compare('itemDetail.bar_code', $this->item_detail_id ,true);

		// $criteria->compare('t.tax_amount', $this->tax_amount,true);
		// $criteria->compare('t.purchase_bill_id', $this->id);
		$criteria->compare('t.tax_id', $this->tax_id);
	
		
		$criteria->compare('t.price', $this->price,true);

		$criteria->compare('t.discount_amt', $this->discount_amt,true);

		/* $orderitems = OrderItem::model()->findAll($criteria);
		if($orderitems){
		$total = 0;
			foreach($orderitems as $orderitem){
				
				$total = $total + $orderitem->getItemTotalAmount();
			}
		Yii::app ()->session ['itemwise_total_amt']=number_format($total,2);
		} */
		return new CActiveDataProvider($this, array(
				'criteria' => $criteria,
				'sort'=>array(
						'defaultOrder'=>'t.id DESC',
				),
		));
	}
	
	
	
	
	public function getOrderBillNo()
    {
        $bill_prefix = 'B';
        $billno = $this->purchase_bill_id;
		
		$bill = B2bPurchaseBill::model()->findByPk($this->purchase_bill_id);
		
	
	
        $month = date('m', strtotime($bill->start_date));
        if ($month > 3) {
  $year = date('Y', strtotime($bill->start_date));
			$year= substr($year, -2);
            $yearlast = $year + 1;
			$yearlast= substr($yearlast, -2);
			
			
        } else {
            $year = date('Y', strtotime($bill->start_date));
            $year = $year - 1;
            $yearlast = date('Y', strtotime($bill->start_date));
        }

        $billyear = date('Y', strtotime($bill->start_date));
        $newyear = $billyear + 1;
        $outlet = Outlet::model()->findByPk($this->outlet_id);
        if ($outlet) {
            if ($outlet->bill_prefix == '') {
                $bill_prefix = $outlet->bill_prefix;
            } else {
                $bill_prefix = 'B';
            }
        }
        $_billno = 'B2B' . $year . '-' . $yearlast . '/' . $bill_prefix . '-' . $bill->grn_refrence_no;
        return $_billno;
    }
	
	
	public function TotalTax()
    {
        $bill_prefix = 'Tax';
        $total = ($this->cess_amt + $this->sgst_amt + $this->cgst_amt + $this->igst_amt);
		
	
        return $total;
    }
	public function getOrderBillDate()
    {
        $bill_prefix = 'B';
        $billno = $this->purchase_bill_id;
		
		$bill = B2bPurchaseBill::model()->findByPk($this->purchase_bill_id);
		
		
	
        return $bill->start_date;
    }
	
		public function getTaxTitle()
    {
        $bill_prefix = 'B';
        $tax = $this->tax_id;
		
		$bill = Tax::model()->findByPk($tax);
		
		
	
        return $bill->title;
    }
	public function createduser()
    {
        $bill_prefix = 'B';
        $billno = $this->create_user_id;
		
		$bill = User::model()->findByPk($this->create_user_id);
		
		
	
        return $bill->full_name;
    }
	public function getVendorName()
    {
	
		$billno = $this->purchase_bill_id;
		$bill = B2bPurchaseBill::model()->findByPk($this->purchase_bill_id);
		$vendor = Vendor::model()->findByPk($bill->vendor_id);
		
		
	
        return $vendor->name;
    }
	
	
	public function b2bsearch() {
		$order_ids = array();
		if(Yii::app()->session['order_item_item_id'] != ''){
			$this->item_id = Yii::app()->session['order_item_item_id'];
		}
		
		
		if(Yii::app()->session['order_item_customer_id'] != ''){
			$this->customer_id = Yii::app()->session['order_item_customer_id'];
		}
		
		
		if(Yii::app()->session['order_item_create_user_id'] != ''){
			$this->create_user_id = Yii::app()->session['order_item_create_user_id'];
		}
		
	
		Yii::log ( CVarDumper::dumpAsString ( Yii::app()->session['order_item_item_id']  ), CLogger::LEVEL_WARNING, '$orderItems' );
		$criteria1 = new CDbCriteria();
		if ((Yii::app ()->session ['order_item_start_date'] != '') && (Yii::app ()->session ['order_item_end_date'] != '')) {
			$criteria1->addBetweenCondition ( 't.start_date', Yii::app ()->session ['order_item_start_date'], Yii::app ()->session ['order_item_end_date'] );
		}
		if ((Yii::app ()->session ['order_item_min_amt'] != '') && (Yii::app ()->session ['order_item_max_amt'] != '')) {
			$criteria1->addBetweenCondition ( 't.total_Amt', Yii::app ()->session ['order_item_min_amt'], Yii::app ()->session ['order_item_max_amt'] );
		}
		// $criteria1->addCondition('t.status','1');
		$criteria1->addCondition('status ='.B2bPurchaseBill::STATUS_APPROVED);
		$orders = B2bPurchaseBill::model()->findAll($criteria1);
		Yii::log ( CVarDumper::dumpAsString ( Yii::app()->session['order_item_start_date']  ), CLogger::LEVEL_WARNING, '$order_item_start_date' );
		Yii::log ( CVarDumper::dumpAsString ( Yii::app()->session['order_item_end_date']  ), CLogger::LEVEL_WARNING, '$order_item_end_date' );
		if($orders){
			foreach($orders as $order){
				$order_ids[] = $order->id;
			}
		}
		Yii::log ( CVarDumper::dumpAsString ( $order_ids  ), CLogger::LEVEL_WARNING, '$order_ids' );
		$criteria = new CDbCriteria;
		$criteria->addInCondition('t.purchase_bill_id',$order_ids);
		$criteria->with = array('itemDetail','item');
		
		$criteria->compare('item.title', $this->item_id ,true);
		
		// $criteria->compare('B2bPurchaseBill.id', $this->purchase_bill_id);
	
		// $criteria->compare('B2bPurchaseBill.create_user_id', $this->create_user_id);
		// $criteria->compare('b2bpurchase_bill.total_amount', $this->total_amount);
		$criteria->compare('item.mrp', $this->mrp);
		$criteria->compare('itemDetail.bar_code', $this->item_detail_id ,true);
		
		$criteria->compare('t.tax_id', $this->tax_id);
		$criteria->compare('t.tax_amount', $this->tax_amount);
		
		// $criteria->compare('t.qty', $this->qty);
		$criteria->compare('t.price', $this->price);
		// $criteria->compare('t.discount_id', $this->discount_id);
		// $criteria->compare('t.discount_amt', $this->discount_amt);
	
		

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
				'pagination' => array (
						'pageSize' => '100'
				),
				'sort'=>array(
						'defaultOrder'=>'t.id DESC',
				),
		));
	}
	
	public function b2bTaxwise() {
	
		$order_ids = array();
		$criteria1 = new CDbCriteria();
		if ((Yii::app ()->session ['order_b2b_start_date'] != '') && (Yii::app ()->session ['order_b2b_end_date'] != '')) {
			$criteria1->addBetweenCondition ( 't.start_date', Yii::app ()->session ['order_b2b_start_date'], Yii::app ()->session ['order_b2b_end_date'] );
		}else{
			$criteria1->addBetweenCondition ( 't.start_date', $this->start_date, $this->end_date );
		}
		if(Yii::app ()->session ['order_mode_payment'] != ''){
		// $criteria1->addCondition ( 't.mode_of_payment ='.Yii::app ()->session ['order_mode_payment']);
		}
		$orders = B2bPurchaseBill::model()->findAll($criteria1);
		if($orders){
			foreach($orders as $order){
				$order_ids[] = $order->id;
			}
		}
	Yii::log ( CVarDumper::dumpAsString ( $order_ids ), CLogger::LEVEL_WARNING, '$order_ids_b2b' );
		$criteria = new CDbCriteria;
		$criteria->addInCondition('purchase_bill_id',$order_ids);
	
		$criteria->with = array('itemDetail','item','b2bPurchaseBill');
		$criteria->group = 't.tax_id';
		//$criteria->group = 't.tax_id,t.order_id';
		$criteria->compare('item.title', $this->item_id ,true);
	
		$criteria->compare('b2bPurchaseBill.bill_no', $this->purchase_bill_id);
		$criteria->compare('b2bPurchaseBill.start_date', $this->start_date);
		$criteria->compare('b2bPurchaseBill.vendor_id', $this->vendor_id);
		$criteria->compare('itemDetail.bar_code', $this->item_detail_id ,true);
	
		$criteria->compare('t.tax_id', $this->tax_id);
		$criteria->compare('t.tax_amount', $this->tax_amount);
		//$criteria->compare ('tax_id', $this->tax_id );
		// $criteria->compare ('t.date(start_date)', $this->start_date );
		$criteria->compare('t.approved_qty', $this->approved_qty);
		$criteria->compare('t.price', $this->price);
		// $criteria->compare('t.discount_id', $this->discount_id);
		// $criteria->compare('t.discount_amt', $this->discount_amt);
		
	
		return new CActiveDataProvider($this, array(
				'criteria' => $criteria,
				'sort'=>array(
						'defaultOrder'=>'t.id DESC',
				),
		));
	}
	
	public function b2bTaxwisesearch() {
		$order_ids = array();
		if(Yii::app()->session['order_item_item_id'] != ''){
			$this->item_id = Yii::app()->session['order_item_item_id'];
		}
		
		
		if(Yii::app()->session['order_item_customer_id'] != ''){
			$this->customer_id = Yii::app()->session['order_item_customer_id'];
		}
		
		
		if(Yii::app()->session['order_item_create_user_id'] != ''){
			$this->create_user_id = Yii::app()->session['order_item_create_user_id'];
		}
		
	
		Yii::log ( CVarDumper::dumpAsString ( Yii::app()->session['order_item_item_id']  ), CLogger::LEVEL_WARNING, '$orderItems' );
		$criteria1 = new CDbCriteria();
		if ((Yii::app ()->session ['order_item_start_date'] != '') && (Yii::app ()->session ['order_item_end_date'] != '')) {
			$criteria1->addBetweenCondition ( 't.start_date', Yii::app ()->session ['order_item_start_date'], Yii::app ()->session ['order_item_end_date'] );
		}
		if ((Yii::app ()->session ['order_item_min_amt'] != '') && (Yii::app ()->session ['order_item_max_amt'] != '')) {
			$criteria1->addBetweenCondition ( 't.total_Amt', Yii::app ()->session ['order_item_min_amt'], Yii::app ()->session ['order_item_max_amt'] );
		}
		$criteria1->addCondition('status ='.B2bPurchaseBill::STATUS_APPROVED);
		$orders = B2bPurchaseBill::model()->findAll($criteria1);
		Yii::log ( CVarDumper::dumpAsString ( Yii::app()->session['order_item_start_date']  ), CLogger::LEVEL_WARNING, '$order_item_start_date' );
		Yii::log ( CVarDumper::dumpAsString ( Yii::app()->session['order_item_end_date']  ), CLogger::LEVEL_WARNING, '$order_item_end_date' );
		if($orders){
			// 586
			foreach($orders as $order){
				$order_ids[] = $order->id;
			}
		}
		Yii::log ( CVarDumper::dumpAsString ( $order_ids  ), CLogger::LEVEL_WARNING, '$order_ids' );
		$criteria = new CDbCriteria;
		$criteria->with = array('itemDetail','item', 'b2bPurchaseBill');
		$criteria->addInCondition('purchase_bill_id',$order_ids);
		// $criteria->select ='t.*,SUM(cgst_amt) AS cgst_amt ,SUM(sgst_amt) AS sgst_amt,SUM(igst_amt) AS igst_amt,SUM(cess_amt) AS cess_amt,SUM(cgst_amt) AS cgst_amt';
		$criteria->select ='t.*, SUM(t.cgst_amt) AS cgst_amt ,SUM(t.sgst_amt) AS sgst_amt,SUM(t.igst_amt) AS igst_amt,SUM(t.cess_amt) AS cess_amt, SUM(t.price * approved_qty) AS price, SUM(t.amount ) AS amount, SUM(t.discount_amt) AS discount_amt,SUM(t.discount_amt1) AS discount_amt1';
		$criteria->group = 't.tax_id,b2bPurchaseBill.id';
		
		// $criteria->group = 't.tax_id,b2bPurchaseBill.vendor_id';
		$criteria->compare('item.title', $this->item_id ,true);
		
		 $criteria->compare('b2bPurchaseBill.id', $this->purchase_bill_id);
	
		$criteria->compare('b2bPurchaseBill.create_user_id', $this->create_user_id);
		// $criteria->compare('purchaseBill.total_amount', $this->total_amount);
		$criteria->compare('item.mrp', $this->mrp);
		$criteria->compare('itemDetail.bar_code', $this->item_detail_id ,true);
		
		$criteria->compare('t.tax_id', $this->tax_id);
		$criteria->compare('t.tax_amount', $this->tax_amount);
		
		// $criteria->compare('t.qty', $this->qty);
		$criteria->compare('t.price', $this->price);
		// $criteria->compare('t.discount_id', $this->discount_id);
		// $criteria->compare('t.discount_amt', $this->discount_amt);
	
		

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
				'pagination' => array (
						'pageSize' => '100'
				),
				'sort'=>array(
						'defaultOrder'=>'t.id DESC',
				),
		));
	}
	

	public function defaultScope() {
		return array ();
	}
}