<?php

 
/**
 * This is the model base class for the table "{{setting}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Setting".
 *
 * Columns in table "{{setting}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $check_val
 * @property integer $type_id
 * @property integer $status
 * @property string $create_time
 *
 */
abstract class BaseSetting extends GxActiveRecord {
	
	Const SETTING_YES='289765';
	Const SETTING_NO='765289';

	public static function getTypeOptions($id = null)
	{
		$list = array("TYPE1","TYPE2","TYPE3");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
 	
	public static function getStatusOptions($id = null)
	{
		$list = array("Draft","Published","Archive");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}	
	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
			if ( !isset( $this->create_time )) $this->create_time = new CDbExpression('NOW()');
		}else{
			}
		return parent::beforeValidate();
	}

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{setting}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Setting|Settings', $n);
	}

	public static function representingColumn() {
		return 'check_val';
	}

	public function rules() {
		return array(
			array('check_val', 'required'),
			array('type_id, status', 'numerical', 'integerOnly'=>true),
			array('check_val', 'length', 'max'=>255),
			array('create_time,api_key,ivr_username', 'safe'),
			array('type_id, status, create_time', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, check_val, type_id, status, create_time', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'check_val' => Yii::t('app', 'Check Val'),
			'type_id' => Yii::t('app', 'Type'),
			'status' => Yii::t('app', 'Status'),
			'create_time' => Yii::t('app', 'Create Time'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('check_val', $this->check_val, true);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('status', $this->status);
		$criteria->compare('create_time', $this->create_time, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}