<?php


 
/**
 * This is the model base class for the table "{{free_item}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "FreeItem".
 *
 * Columns in table "{{free_item}}" available as properties of the model,
 * followed by relations of table "{{free_item}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $title
 * @property integer $item_id
 * @property integer $item_detail_id
 * @property integer $item_category_id
 * @property integer $item_company_id
 * @property integer $qty
 * @property integer $stock_qty
 * @property integer $type_id
 * @property integer $status
 * @property string $create_time
 * @property string $update_time
 * @property integer $create_user_id
 * @property integer $updated_by
 *
 * @property User $createUser
 * @property ItemCategory $itemCategory
 * @property ItemCompany $itemCompany
 * @property ItemDetail $itemDetail
 * @property Item $item
 * @property User $updatedBy
 */
abstract class BaseFreeItem extends GxActiveRecord {
public $name;
	const STATUS_ACTIVE = 0;
	const STATUS_INACTIVE = 1;
	
	public static function getTypeOptions($id = null)
	{
		$list = array("TYPE1","TYPE2","TYPE3");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
 	
	public static function getStatusOptions($id = null)
	{
		$list = array("Active","InActive");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}	
	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
			if ( !isset( $this->create_time )) $this->create_time = new CDbExpression('NOW()');
				if ( !isset( $this->create_user_id )) $this->create_user_id = Yii::app()->user->id;			
	}else{
					}
		return parent::beforeValidate();
	}

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{free_item}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'FreeItem|FreeItems', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('title, item_id, item_detail_id, item_category_id, create_user_id', 'required'),
			array('item_id, item_detail_id, item_category_id, item_company_id, qty, stock_qty, type_id, status, create_user_id, updated_by', 'numerical', 'integerOnly'=>true),
			array('title', 'length', 'max'=>255),
			array('create_time, update_time,name', 'safe'),
			array('item_company_id, qty, stock_qty, type_id, status, create_time, update_time, updated_by', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, title, item_id, item_detail_id, item_category_id, item_company_id, qty, stock_qty, type_id, status, create_time, update_time, create_user_id, updated_by', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'createUser' => array(self::BELONGS_TO, 'User', 'create_user_id'),
			'itemCategory' => array(self::BELONGS_TO, 'ItemCategory', 'item_category_id'),
			'itemCompany' => array(self::BELONGS_TO, 'ItemCompany', 'item_company_id'),
			'itemDetail' => array(self::BELONGS_TO, 'ItemDetail', 'item_detail_id'),
			'item' => array(self::BELONGS_TO, 'Item', 'item_id'),
			'updatedBy' => array(self::BELONGS_TO, 'User', 'updated_by'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'title' => Yii::t('app', 'Title'),
			'item_id' => null,
			'item_detail_id' => null,
			'item_category_id' => null,
			'item_company_id' => null,
			'qty' => Yii::t('app', 'Qty'),
			'stock_qty' => Yii::t('app', 'Stock Qty'),
			'type_id' => Yii::t('app', 'Type'),
			'status' => Yii::t('app', 'Status'),
			'create_time' => Yii::t('app', 'Create Time'),
			'update_time' => Yii::t('app', 'Update Time'),
			'create_user_id' => null,
			'updated_by' => null,
			'createUser' => null,
			'itemCategory' => null,
			'itemCompany' => null,
			'itemDetail' => null,
			'item' => null,
			'updatedBy' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;
       
		$criteria->compare('id', $this->id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('item_id', $this->item_id);
		$criteria->compare('item_detail_id', $this->item_detail_id);
		$criteria->compare('item_category_id', $this->item_category_id);
		$criteria->compare('item_company_id', $this->item_company_id);
		$criteria->compare('qty', $this->qty);
		$criteria->compare('stock_qty', $this->stock_qty);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('status', $this->status);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('update_time', $this->update_time, true);
		$criteria->compare('create_user_id', $this->create_user_id);
		$criteria->compare('updated_by', $this->updated_by);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}