<?php


 
/**
 * This is the model base class for the table "{{order_item}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "OrderItem".
 *
 * Columns in table "{{order_item}}" available as properties of the model,
 * followed by relations of table "{{order_item}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $order_id
 * @property integer $item_detail_id
 * @property integer $qty
 * @property double $price
 * @property integer $discount_id
 * @property double $discount_amt
 * @property integer $status
 * @property integer $type_id
 * @property string $create_time
 * @property string $update_time
 * @property integer $create_user_id
 * @property integer $updated_by
 *
 * @property User $createUser
 * @property Discount $discount
 * @property ItemDetail $itemDetail
 * @property Order $order
 * @property User $updatedBy
 */
abstract class BaseOrderItem extends GxActiveRecord {
	public $mode_of_payment;
 public $refund_qty;
	public $columns;
	public $start_date;
	public $end_date;
	public $customer_id;
	
	public $mrp;
	public $total_amt;
	public $min_amt;
	public $max_amt;
	public $bill_date;
	public static function getStatusOptions($id = null)
	{
		$list = array("Draft","Published","Archive");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}	
	public static function getTypeOptions($id = null)
	{
		$list = array("TYPE1","TYPE2","TYPE3");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
 	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
			
			if ( !isset( $this->create_date )) $this->create_date = date('Y-m-d');
			if ( !isset( $this->create_time )) $this->create_time = new CDbExpression('NOW()');
				if ( !isset( $this->create_user_id )) $this->create_user_id = Yii::app()->user->id;			
	}else{
					}
		return parent::beforeValidate();
	}

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{order_item}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'OrderItem|OrderItems', $n);
	}

	public static function representingColumn() {
		return 'create_time';
	}

	public function rules() {
		return array(
			array('create_user_id', 'required'),
			array('order_id, item_detail_id, discount_id, status, type_id, create_user_id, updated_by', 'numerical', 'integerOnly'=>true),
			array('price, discount_amt', 'numerical'),
			array('create_time, update_time,columns,order_discount,item_id,tax_id,customer_id,mrp,total_amt,start_date,end_date,min_amt,max_amt,create_date,req_qty,qty,cgst_per,sgst_per,igst_per,cess_per,cgst_amt,sgst_amt,cess_amt,igst_amt,sale_rate,total_amt,mrp,mode_of_payment,original_tax,start_date,end_date,customer_id,order_id', 'safe'),
			array('order_id, item_detail_id, qty, price, discount_id, discount_amt, status, type_id, create_time, update_time, updated_by', 'default', 'setOnEmpty' => true, 'value' => null),
			array('tax_amount,id, order_id, item_detail_id, qty,customer_id,mrp,total_amt,price, discount_id, discount_amt, status, type_id, create_time, update_time, create_user_id, updated_by', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'createUser' => array(self::BELONGS_TO, 'User', 'create_user_id'),
			'discount' => array(self::BELONGS_TO, 'Discount', 'discount_id'),
			'itemDetail' => array(self::BELONGS_TO, 'ItemDetail', 'item_detail_id'),
				'item' => array(self::BELONGS_TO, 'Item', 'item_id'),
				'tax' => array(self::BELONGS_TO, 'Tax', 'tax_id'),
			'order' => array(self::BELONGS_TO, 'Order', 'order_id'),
			'updatedBy' => array(self::BELONGS_TO, 'User', 'updated_by'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'order_id' => null,
			'item_detail_id' => null,
			'qty' => Yii::t('app', 'Qty'),
			'price' => Yii::t('app', 'Price'),
				'min_amt' => Yii::t('app', 'Minimum Total Amount'),
				'max_amt' => Yii::t('app', 'Maximum Total Amount'),
			'discount_id' => null,
			'discount_amt' => Yii::t('app', 'Discount Amt'),
			'status' => Yii::t('app', 'Status'),
			'type_id' => Yii::t('app', 'Type'),
			'create_time' => Yii::t('app', 'Create Time'),
			'update_time' => Yii::t('app', 'Update Time'),
				'item_id' => Yii::t('app', 'Item'),
			'create_user_id' => null,
			'updated_by' => null,
			'createUser' => null,
			'discount' => null,
			'itemDetail' => null,
			'order' => null,
			'updatedBy' => null,
		);
	}
	
	public function itemwisesearch() {
		$criteria = new CDbCriteria;

		$criteria->with = array(
        'itemDetail' => array(
					'together' => true,
            'select' => 'id, bar_code', // Only select needed columns
            'joinType' => 'INNER JOIN' // Use INNER JOIN if you don't need NULL records
        ),
        'item' => array(
					'together' => true,
            'select' => 'id, title, item_code', // Only select needed columns
            'joinType' => 'INNER JOIN'
        ),
        'order' => array(
					'together' => true,
            'select' => 'id, bill_no, bill_date', // Only select needed columns
            'joinType' => 'INNER JOIN'
        )
    );
		$criteria->group = 'item_detail_id';
		// MySQL 5.7 sorted GROUP BY results implicitly; MySQL 8.0 does not. Order
		// explicitly by the grouped columns to preserve the previous output order.
		$criteria->order = 'item_detail_id';
		
		if ((Yii::app ()->session ['start_date'] != '') && (Yii::app ()->session ['end_date'] != '')) {
			$order_ids = array();
			$criteria1 = new CDbCriteria();
			$criteria1->addBetweenCondition ( 't.bill_date', Yii::app ()->session ['start_date'], Yii::app ()->session ['end_date'] );
			$orders = Order::model()->findAll($criteria1);
			if($orders){
				foreach($orders as $order){
					$order_ids[] = $order->id;
				}
			}
			$criteria->addInCondition('t.order_id',$order_ids);
			
		}
		
		
		
	
		if(!empty(Yii::app()->session['item_id'])){
			$criteria->addInCondition('item.id', Yii::app()->session['item_id']);
		}else{
			$criteria->compare('item.title', $this->item_id ,true);
		}
		$criteria->compare('order.customer_id', $this->customer_id);
		$criteria->compare('itemDetail.bar_code', $this->item_detail_id ,true);

		$criteria->compare('t.tax_amount', $this->tax_amount,true);
		$criteria->compare('t.order_id', $this->order_id);
		$criteria->compare('t.tax_id', $this->tax_id);
	
		$criteria->compare('t.qty', $this->qty);
		$criteria->compare('t.price', $this->price,true);

		$criteria->compare('t.discount_amt', $this->discount_amt,true);

		/* $orderitems = OrderItem::model()->findAll($criteria);
		if($orderitems){
		$total = 0;
			foreach($orderitems as $orderitem){
				
				$total = $total + $orderitem->getItemTotalAmount();
			}
		Yii::app ()->session ['itemwise_total_amt']=number_format($total,2);
		} */
		return new CActiveDataProvider($this, array(
				'criteria' => $criteria,
				'sort'=>array(
						'defaultOrder'=>'t.id DESC',
				),
		));
	}

	public function itemsearch($id) {
		$criteria = new CDbCriteria;
	   if($id == null){
	   	$ids = array();
	   	$criteria->addInCondition('id',$ids);
	   }
		$criteria->compare('id', $this->id);
		$criteria->compare('order_id', $this->order_id);
		$criteria->compare('item_detail_id', $this->item_detail_id);
		$criteria->compare('item_id', $this->item_id);
		$criteria->compare('qty', $this->qty);
		$criteria->compare('tax_id', $this->tax_id);
		$criteria->compare('tax_amount', $this->tax_amount);
		$criteria->compare('price', $this->price);
		$criteria->compare('discount_id', $this->discount_id);
		$criteria->compare('discount_amt', $this->discount_amt);
		$criteria->compare('status', $this->status);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('update_time', $this->update_time, true);
		$criteria->compare('create_user_id', $this->create_user_id);
		$criteria->compare('updated_by', $this->updated_by);
	
		return new CActiveDataProvider($this, array(
				'criteria' => $criteria,
				'sort'=>array(
						'defaultOrder'=>'id DESC',
				),
		));
	}
	public function search() {
		$order_ids = array();
		if(Yii::app()->session['order_item_item_id'] != ''){
			$this->item_id = Yii::app()->session['order_item_item_id'];
		}
		
		
		if(Yii::app()->session['order_item_customer_id'] != ''){
			$this->customer_id = Yii::app()->session['order_item_customer_id'];
		}
		
		
		if(Yii::app()->session['order_item_create_user_id'] != ''){
			$this->create_user_id = Yii::app()->session['order_item_create_user_id'];
		}
		
		
		Yii::log ( CVarDumper::dumpAsString ( Yii::app()->session['order_item_item_id']  ), CLogger::LEVEL_WARNING, '$orderItems' );
		$criteria1 = new CDbCriteria();
		if ((Yii::app ()->session ['order_item_start_date'] != '') && (Yii::app ()->session ['order_item_end_date'] != '')) {
			$criteria1->addBetweenCondition ( 't.bill_date', Yii::app ()->session ['order_item_start_date'], Yii::app ()->session ['order_item_end_date'] );
		}
		if ((Yii::app ()->session ['order_item_min_amt'] != '') && (Yii::app ()->session ['order_item_max_amt'] != '')) {
			$criteria1->addBetweenCondition ( 't.total_Amt', Yii::app ()->session ['order_item_min_amt'], Yii::app ()->session ['order_item_max_amt'] );
		}
		
		$orders = Order::model()->findAll($criteria1);
		Yii::log ( CVarDumper::dumpAsString ( Yii::app()->session['order_item_start_date']  ), CLogger::LEVEL_WARNING, '$order_item_start_date' );
		Yii::log ( CVarDumper::dumpAsString ( Yii::app()->session['order_item_end_date']  ), CLogger::LEVEL_WARNING, '$order_item_end_date' );
		if($orders){
			foreach($orders as $order){
				$order_ids[] = $order->id;
			}
		}
		Yii::log ( CVarDumper::dumpAsString ( $order_ids  ), CLogger::LEVEL_WARNING, '$order_ids' );
		$criteria = new CDbCriteria;
		$criteria->addInCondition('t.order_id',$order_ids);
		$criteria->with = array('itemDetail','item','order');
		$criteria->compare('item.title', $this->item_id ,true);
		
		$criteria->compare('order.bill_no', $this->order_id);
		$criteria->compare('order.customer_id', $this->customer_id);
		$criteria->compare('order.create_user_id', $this->create_user_id);
		$criteria->compare('order.total_amt', $this->total_amt);
		$criteria->compare('item.mrp', $this->mrp);
		$criteria->compare('itemDetail.bar_code', $this->item_detail_id ,true);
		
		$criteria->compare('t.tax_id', $this->tax_id);
		$criteria->compare('t.tax_amount', $this->tax_amount);
		
		$criteria->compare('t.qty', $this->qty);
		$criteria->compare('t.price', $this->price);
		$criteria->compare('t.discount_id', $this->discount_id);
		$criteria->compare('t.discount_amt', $this->discount_amt);
	
		

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
				'pagination' => array (
						'pageSize' => '100'
				),
				'sort'=>array(
						'defaultOrder'=>'t.id DESC',
				),
		));
	}
	public function b2bTaxsearch() {
	
		$order_ids = array();
		$criteria1 = new CDbCriteria();
		if ((Yii::app ()->session ['order_b2b_start_date'] != '') && (Yii::app ()->session ['order_b2b_end_date'] != '')) {
			$criteria1->addBetweenCondition ( 't.bill_date', Yii::app ()->session ['order_b2b_start_date'], Yii::app ()->session ['order_b2b_end_date'] );
		}else{
			$criteria1->addBetweenCondition ( 't.bill_date', $this->start_date, $this->end_date );
		}
		if(Yii::app ()->session ['order_mode_payment'] != ''){
		$criteria1->addCondition ( 't.mode_of_payment ='.Yii::app ()->session ['order_mode_payment']);
		}
		$orders = Order::model()->findAll($criteria1);
		if($orders){
			foreach($orders as $order){
				$order_ids[] = $order->id;
			}
		}
	Yii::log ( CVarDumper::dumpAsString ( $order_ids ), CLogger::LEVEL_WARNING, '$order_ids_b2b' );
		$criteria = new CDbCriteria;
		$criteria->addInCondition('order_id',$order_ids);
	
		$criteria->with = array('itemDetail','item','order');
		$criteria->group = 't.tax_id,t.create_date';
		// MySQL 5.7 sorted GROUP BY results implicitly; MySQL 8.0 does not. Order
		// explicitly by the grouped columns to preserve the previous output order.
		$criteria->order = 't.tax_id,t.create_date';
		//$criteria->group = 't.tax_id,t.order_id';
		$criteria->compare('item.title', $this->item_id ,true);
	
		$criteria->compare('order.bill_no', $this->order_id);
		$criteria->compare('order.bill_date', $this->bill_date);
		$criteria->compare('order.customer_id', $this->customer_id);
		$criteria->compare('itemDetail.bar_code', $this->item_detail_id ,true);
	
		$criteria->compare('t.tax_id', $this->tax_id);
		$criteria->compare('t.tax_amount', $this->tax_amount);
		//$criteria->compare ('tax_id', $this->tax_id );
		$criteria->compare ('t.date(create_date)', $this->create_date );
		$criteria->compare('t.qty', $this->qty);
		$criteria->compare('t.price', $this->price);
		$criteria->compare('t.discount_id', $this->discount_id);
		$criteria->compare('t.discount_amt', $this->discount_amt);
		
	
		return new CActiveDataProvider($this, array(
				'criteria' => $criteria,
				'sort'=>array(
						'defaultOrder'=>'t.id DESC',
				),
		));
	}
	public function groupHSNTaxsearch() {
	
		$order_ids = array();
		$criteria1 = new CDbCriteria();
		if ((Yii::app ()->session ['order_item_start_date'] != '') && (Yii::app ()->session ['order_item_end_date'] != '')) {
			$criteria1->addBetweenCondition ( 't.bill_date', Yii::app ()->session ['order_item_start_date'], Yii::app ()->session ['order_item_end_date'] );
		}else{
			$criteria1->addBetweenCondition ( 't.bill_date', $this->start_date, $this->end_date );
		}
		if ( $this->mode_of_payment != null) {
			$criteria1->addCondition ( 't.mode_of_payment ='.$this->mode_of_payment);
		}
		Yii::log ( CVarDumper::dumpAsString ( Yii::app ()->session ['order_item_start_date'] ), CLogger::LEVEL_WARNING, 'start_date' );
		Yii::log ( CVarDumper::dumpAsString ( Yii::app ()->session ['order_item_end_date'] ), CLogger::LEVEL_WARNING, 'end_date' );
		$orders = Order::model()->findAll($criteria1);
		if($orders){
			foreach($orders as $order){
				$order_ids[] = $order->id;
			}
		}
		
		$criteria = new CDbCriteria;
		$criteria->addInCondition('order_id',$order_ids);
	
		$criteria->with = array('itemDetail','item','order');
		$criteria->group = 't.item_id,t.tax_id,t.create_date';
		// MySQL 5.7 sorted GROUP BY results implicitly; MySQL 8.0 does not. Order
		// explicitly by the grouped columns to preserve the previous output order.
		$criteria->order = 't.item_id,t.tax_id,t.create_date';
		$criteria->compare('item.title', $this->item_id ,true);
	
		$criteria->compare('order.bill_no', $this->order_id);
		$criteria->compare('order.bill_date', $this->bill_date);
		$criteria->compare('order.customer_id', $this->customer_id);
		$criteria->compare('itemDetail.bar_code', $this->item_detail_id ,true);
	
		$criteria->compare('t.tax_id', $this->tax_id);
		$criteria->compare('t.tax_amount', $this->tax_amount);
		//$criteria->compare ('tax_id', $this->tax_id );
		$criteria->compare ('t.date(create_date)', $this->create_date );
		$criteria->compare('t.qty', $this->qty);
		$criteria->compare('t.price', $this->price);
		$criteria->compare('t.discount_id', $this->discount_id);
		$criteria->compare('t.discount_amt', $this->discount_amt);
	//    $orderItems = OrderItem::model()->findAll($criteria);
	   // Yii::log ( CVarDumper::dumpAsString ( $orderItems ), CLogger::LEVEL_WARNING, '$orderItems' );
	   /*   if($orderItems){
	     	$gst = 0;
	     	$cgst = 0;
	     	$sgst = 0;
	     	$cess = 0;
	     	$igst = 0;
	     	$total = 0;
	     	$taxable = 0;
	     	foreach($orderItems as $orderItem){
	     		$gst = $gst + $orderItem->getOrderTotalgstAmount();
	     		$cgst = $cgst + $orderItem->getGroupTaxCgstAmount();
	     		//Yii::log ( CVarDumper::dumpAsString ( $orderItem->getGroupTaxCgstAmount() ), CLogger::LEVEL_WARNING, '$cgst' );
	     		$sgst = $sgst + $orderItem->getGroupTaxSgstAmount();
	     		$cess = $cess + $orderItem->getGroupTaxCessAmount();
	     		$igst = $igst + $orderItem->getGroupTaxIgstAmount();
	     		$total = $total + $orderItem->getGroupTaxOrderTotalAmount();
	     		$taxable = $taxable + $orderItem->getTotalItemTaxableAmount();
	     	}
	     	Yii::app ()->session ['group_tax_gst'] = number_format($gst,2);
	     	Yii::app ()->session ['group_tax_cgst']= number_format($cgst,2);
	     	Yii::app ()->session ['group_tax_sgst']= number_format($sgst,2);
	     	Yii::app ()->session ['group_tax_cess']= number_format($cess,2);
	     	Yii::app ()->session ['group_tax_igst']= number_format($igst,2);
	     	Yii::app ()->session ['group_tax_total']=number_format($total,2);
	     	Yii::app ()->session ['group_taxable_total']=number_format($taxable,2);
	     } */
	
		return new CActiveDataProvider($this, array(
				'criteria' => $criteria,
				//'pagination' => array (
				//		'pageSize' => '400'
				//),
				//'pagination'=>false,
				'sort'=>array(
						'defaultOrder'=>'t.id DESC',
						
				),
		));
	}
	public function groupTaxsearch() {
	
		$order_ids = array();
		$criteria1 = new CDbCriteria();
		if ((Yii::app ()->session ['order_item_start_date'] != '') && (Yii::app ()->session ['order_item_end_date'] != '')) {
			$criteria1->addBetweenCondition ( 't.bill_date', Yii::app ()->session ['order_item_start_date'], Yii::app ()->session ['order_item_end_date'] );
		}else{
			$criteria1->addBetweenCondition ( 't.bill_date', $this->start_date, $this->end_date );
		}
		if ( $this->mode_of_payment != null) {
			$criteria1->addCondition ( 't.mode_of_payment ='.$this->mode_of_payment);
		}
		$orders = Order::model()->findAll($criteria1);
		if($orders){
			foreach($orders as $order){
				$order_ids[] = $order->id;
			}
		}
		
		$criteria = new CDbCriteria;
		$criteria->addInCondition('order_id',$order_ids);
	
		$criteria->with = array('itemDetail','item','order');
		$criteria->group = 't.tax_id,t.create_date';
		// MySQL 5.7 sorted GROUP BY results implicitly; MySQL 8.0 does not. Order
		// explicitly by the grouped columns to preserve the previous output order.
		$criteria->order = 't.tax_id,t.create_date';
		$criteria->compare('item.title', $this->item_id ,true);
	
		$criteria->compare('order.bill_no', $this->order_id);
		$criteria->compare('order.bill_date', $this->bill_date);
		$criteria->compare('order.customer_id', $this->customer_id);
		$criteria->compare('itemDetail.bar_code', $this->item_detail_id ,true);
	
		$criteria->compare('t.tax_id', $this->tax_id);
		$criteria->compare('t.tax_amount', $this->tax_amount);
		//$criteria->compare ('tax_id', $this->tax_id );
		$criteria->compare ('t.date(create_date)', $this->create_date );
		$criteria->compare('t.qty', $this->qty);
		$criteria->compare('t.price', $this->price);
		$criteria->compare('t.discount_id', $this->discount_id);
		$criteria->compare('t.discount_amt', $this->discount_amt);
	//    $orderItems = OrderItem::model()->findAll($criteria);
	   // Yii::log ( CVarDumper::dumpAsString ( $orderItems ), CLogger::LEVEL_WARNING, '$orderItems' );
	   /*   if($orderItems){
	     	$gst = 0;
	     	$cgst = 0;
	     	$sgst = 0;
	     	$cess = 0;
	     	$igst = 0;
	     	$total = 0;
	     	$taxable = 0;
	     	foreach($orderItems as $orderItem){
	     		$gst = $gst + $orderItem->getOrderTotalgstAmount();
	     		$cgst = $cgst + $orderItem->getGroupTaxCgstAmount();
	     		//Yii::log ( CVarDumper::dumpAsString ( $orderItem->getGroupTaxCgstAmount() ), CLogger::LEVEL_WARNING, '$cgst' );
	     		$sgst = $sgst + $orderItem->getGroupTaxSgstAmount();
	     		$cess = $cess + $orderItem->getGroupTaxCessAmount();
	     		$igst = $igst + $orderItem->getGroupTaxIgstAmount();
	     		$total = $total + $orderItem->getGroupTaxOrderTotalAmount();
	     		$taxable = $taxable + $orderItem->getTotalItemTaxableAmount();
	     	}
	     	Yii::app ()->session ['group_tax_gst'] = number_format($gst,2);
	     	Yii::app ()->session ['group_tax_cgst']= number_format($cgst,2);
	     	Yii::app ()->session ['group_tax_sgst']= number_format($sgst,2);
	     	Yii::app ()->session ['group_tax_cess']= number_format($cess,2);
	     	Yii::app ()->session ['group_tax_igst']= number_format($igst,2);
	     	Yii::app ()->session ['group_tax_total']=number_format($total,2);
	     	Yii::app ()->session ['group_taxable_total']=number_format($taxable,2);
	     } */
		// A debugging line that was left in:
		//
		//   echo $this->getCommandBuilder()->createFindCommand(
		//       $this->getTableSchema(), $criteria)->getText(); die;
		//
		// It echoed the query and stopped, so order/groupTax rendered its
		// search form, printed the SQL it was about to run and ended there -
		// before the layout, which is why the page had no styling either. The
		// report has never been shown. Removed in both trees in one commit so
		// the two stacks keep agreeing; see docs/live-bugs-found.md.

		return new CActiveDataProvider($this, array(
				'criteria' => $criteria,
				'sort'=>array(
						'defaultOrder'=>'t.id DESC',
				),
		));
	}
	
	public function defaultScope()
	{
		return array();
	}
}