<?php

/**
 * Company: ToXSL Technologies Pvt. Ltd. < www.toxsl.com >
 * Author : Shiv Charan Panjeta < shiv@toxsl.com >
 */

/**
 * This is the model base class for the table "{{item_return_item}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ItemReturnItem".
 *
 * Columns in table "{{item_return_item}}" available as properties of the model,
 * followed by relations of table "{{item_return_item}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $item_id
 * @property integer $item_detail_id
 * @property string $mrp
 * @property double $price
 * @property string $sale_rate
 * @property integer $free
 * @property integer $qty
 * @property double $discount
 * @property double $discount_amt
 * @property double $discount1
 * @property double $discount_amt1
 * @property double $cgst_per
 * @property double $sgst_per
 * @property double $cess_per
 * @property double $cgst_amt
 * @property double $sgst_amt
 * @property double $cess_amt
 * @property double $igst_per
 * @property double $igst_amt
 * @property integer $tax_id
 * @property double $other_charge
 * @property string $total_amt
 * @property integer $vendor_id
 * @property integer $outlet_id
 * @property integer $status
 * @property integer $type_id
 * @property integer $return_id
 * @property string $create_time
 * @property integer $create_user_id
 * @property integer $updated_by
 *
 * @property User $createUser
 * @property ItemDetail $itemDetail
 * @property Item $item
 * @property User $updatedBy
 */
abstract class BaseItemReturnItem extends GxActiveRecord {
	public $columns;
	public $tally_start_date;
	public $tally_end_date;
	public $bar_code ;
	public $item_val_id ;
	public $start_date;
	public $credit_note_no;
	public $credit_note_date;
	public static function getAPIOptions($id = null)
	{
		$list = array("Yes","No");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
	public static function getStatusOptions($id = null) {
		$list = array (
				"Draft",
				"Published",
				"Archive" 
		);
		if ($id == null)
			return $list;
		if (is_numeric ( $id ))
			return $list [$id];
		return $id;
	}
	public static function getTypeOptions($id = null) {
		$list = array (
				"TYPE1",
				"TYPE2",
				"TYPE3" 
		);
		if ($id == null)
			return $list;
		if (is_numeric ( $id ))
			return $list [$id];
		return $id;
	}
	public function beforeValidate() {
		if ($this->isNewRecord) {
			if (! isset ( $this->create_time ))
				$this->create_time = new CDbExpression ( 'NOW()' );
			if (! isset ( $this->create_user_id ))
				$this->create_user_id = Yii::app ()->user->id;
		} else {
		}
		return parent::beforeValidate ();
	}
	public static function model($className = __CLASS__) {
		return parent::model ( $className );
	}
	public function tableName() {
		return '{{item_return_item}}';
	}
	public static function label($n = 1) {
		return Yii::t ( 'app', 'ItemReturnItem|ItemReturnItems', $n );
	}
	public static function representingColumn() {
		return 'create_time';
	}
	public function rules() {
		return array (
				array (
						'price, tax_id, vendor_id, outlet_id, return_id, create_time, create_user_id',
						'required' 
				),
				array (
						'item_id, item_detail_id, free, tax_id, vendor_id, outlet_id, status, type_id, return_id, create_user_id, updated_by',
						'numerical',
						'integerOnly' => true 
				),
				array (
						'price, discount, discount_amt, discount1, discount_amt1, cgst_per, sgst_per, cess_per, cgst_amt, sgst_amt, cess_amt, igst_per, igst_amt, other_charge',
						'numerical' 
				),
				array (
						'margin,tally_end_date,tally_start_date',
						'safe' 
				),
				array (
						'mrp, sale_rate, total_amt',
						'length',
						'max' => 10 
				),
				array (
						'item_id, item_detail_id, mrp, sale_rate, free, qty, discount1, discount_amt1, igst_per, igst_amt, total_amt, status, type_id, updated_by',
						'default',
						'setOnEmpty' => true,
						'value' => null 
				),
				array (
						'id, item_id, item_detail_id, mrp, price, sale_rate, free, qty, discount, discount_amt, discount1, discount_amt1, cgst_per, sgst_per, cess_per, cgst_amt, sgst_amt, cess_amt, igst_per, igst_amt, tax_id, other_charge, total_amt, vendor_id, outlet_id, status, type_id, return_id, create_time, create_user_id, updated_by',
						'safe',
						'on' => 'search' 
				) 
		);
	}
	public function relations() {
		return array (
				'createUser' => array (
						self::BELONGS_TO,
						'User',
						'create_user_id' 
				),
				'itemDetail' => array (
						self::BELONGS_TO,
						'ItemDetail',
						'item_detail_id' 
				),
				'item' => array (
						self::BELONGS_TO,
						'Item',
						'item_id' 
				),
				'tax' => array (
						self::BELONGS_TO,
						'Tax',
						'tax_id' 
				),
				'updatedBy' => array (
						self::BELONGS_TO,
						'User',
						'updated_by' 
				),
				'itemReturn' => array (
						self::BELONGS_TO,
						'ItemReturn',
						'return_id' 
				),
		);
	}
	public function pivotModels() {
		return array ();
	}
	public function attributeLabels() {
		return array (
				'id' => Yii::t ( 'app', 'ID' ),
				'item_id' => null,
				'item_detail_id' => null,
				'mrp' => Yii::t ( 'app', 'Mrp' ),
				'price' => Yii::t ( 'app', 'Price' ),
				'sale_rate' => Yii::t ( 'app', 'Sale Rate' ),
				'free' => Yii::t ( 'app', 'Free' ),
				'qty' => Yii::t ( 'app', 'Qty' ),
				'discount' => Yii::t ( 'app', 'Discount' ),
				'discount_amt' => Yii::t ( 'app', 'Discount Amount' ),
				'discount1' => Yii::t ( 'app', 'Other Discount(%age)' ),
				'discount_amt1' => Yii::t ( 'app', 'Other Discount' ),
				'cgst_per' => Yii::t ( 'app', 'Cgst Per' ),
				'sgst_per' => Yii::t ( 'app', 'Sgst Per' ),
				'cess_per' => Yii::t ( 'app', 'Cess Per' ),
				'cgst_amt' => Yii::t ( 'app', 'Cgst Amt' ),
				'sgst_amt' => Yii::t ( 'app', 'Sgst Amt' ),
				'cess_amt' => Yii::t ( 'app', 'Cess Amt' ),
				'igst_per' => Yii::t ( 'app', 'Igst Per' ),
				'igst_amt' => Yii::t ( 'app', 'Igst Amt' ),
				'tax_id' => Yii::t ( 'app', 'Tax' ),
				'other_charge' => Yii::t ( 'app', 'Other Charge' ),
				'total_amt' => Yii::t ( 'app', 'Total Amt' ),
				'vendor_id' => Yii::t ( 'app', 'Vendor' ),
				'outlet_id' => Yii::t ( 'app', 'Outlet' ),
				'status' => Yii::t ( 'app', 'Status' ),
				'type_id' => Yii::t ( 'app', 'Type' ),
				'return_id' => Yii::t ( 'app', 'Return' ),
				'create_time' => Yii::t ( 'app', 'Create Time' ),
				'create_user_id' => null,
				'updated_by' => null,
				'createUser' => null,
				'itemDetail' => null,
				'item' => null,
				'updatedBy' => null 
		);
	}
	public function search() {
		$criteria = new CDbCriteria ();
	
		$criteria->compare ( 'id', $this->id );
		$criteria->compare ( 'item_id', $this->item_id );
		$criteria->compare ( 'item_detail_id', $this->item_detail_id );
		$criteria->compare ( 'mrp', $this->mrp, true );
		$criteria->compare ( 'price', $this->price );
		$criteria->compare ( 'sale_rate', $this->sale_rate, true );
		$criteria->compare ( 'free', $this->free );
		$criteria->compare ( 'qty', $this->qty );
		$criteria->compare ( 'discount', $this->discount );
		$criteria->compare ( 'discount_amt', $this->discount_amt );
		$criteria->compare ( 'discount1', $this->discount1 );
		$criteria->compare ( 'discount_amt1', $this->discount_amt1 );
		$criteria->compare ( 'cgst_per', $this->cgst_per );
		$criteria->compare ( 'sgst_per', $this->sgst_per );
		$criteria->compare ( 'cess_per', $this->cess_per );
		$criteria->compare ( 'cgst_amt', $this->cgst_amt );
		$criteria->compare ( 'sgst_amt', $this->sgst_amt );
		$criteria->compare ( 'cess_amt', $this->cess_amt );
		$criteria->compare ( 'igst_per', $this->igst_per );
		$criteria->compare ( 'igst_amt', $this->igst_amt );
		$criteria->compare ( 'tax_id', $this->tax_id );
		$criteria->compare ( 'other_charge', $this->other_charge );
		$criteria->compare ( 'total_amt', $this->total_amt, true );
		$criteria->compare ( 'vendor_id', $this->vendor_id );
		$criteria->compare ( 'outlet_id', $this->outlet_id );
		$criteria->compare ( 'status', $this->status );
		$criteria->compare ( 'type_id', $this->type_id );
		$criteria->compare ( 'return_id', $this->return_id );
		$criteria->compare ( 'create_time', $this->create_time, true );
		$criteria->compare ( 'create_user_id', $this->create_user_id );
		$criteria->compare ( 'updated_by', $this->updated_by );
		
		return new CActiveDataProvider ( $this, array (
				'criteria' => $criteria,
				'pagination' => false 
		) );
	}
	
	public function reportsearch() {
		$criteria = new CDbCriteria ();
		$criteria->order ="id DESC";
	if ((Yii::app ()->session ['returnitem_start_date'] != '') && (Yii::app ()->session ['returnitem_end_date'] != '')) {
			$criteria->addBetweenCondition ( 'date(create_time)', Yii::app ()->session ['returnitem_start_date'], Yii::app ()->session ['returnitem_end_date'] );
		}
		$criteria->compare ( 'id', $this->id );
		$criteria->compare ( 'item_id', $this->item_id );
		$criteria->compare ( 'item_detail_id', $this->item_detail_id );
		$criteria->compare ( 'mrp', $this->mrp, true );
		$criteria->compare ( 'price', $this->price );
		$criteria->compare ( 'sale_rate', $this->sale_rate, true );
		$criteria->compare ( 'free', $this->free );
		$criteria->compare ( 'qty', $this->qty );
		$criteria->compare ( 'discount', $this->discount );
		$criteria->compare ( 'discount_amt', $this->discount_amt );
		$criteria->compare ( 'discount1', $this->discount1 );
		$criteria->compare ( 'discount_amt1', $this->discount_amt1 );
		$criteria->compare ( 'cgst_per', $this->cgst_per );
		$criteria->compare ( 'sgst_per', $this->sgst_per );
		$criteria->compare ( 'cess_per', $this->cess_per );
		$criteria->compare ( 'cgst_amt', $this->cgst_amt );
		$criteria->compare ( 'sgst_amt', $this->sgst_amt );
		$criteria->compare ( 'cess_amt', $this->cess_amt );
		$criteria->compare ( 'igst_per', $this->igst_per );
		$criteria->compare ( 'igst_amt', $this->igst_amt );
		$criteria->compare ( 'tax_id', $this->tax_id );
		$criteria->compare ( 'other_charge', $this->other_charge );
		$criteria->compare ( 'total_amt', $this->total_amt, true );
		$criteria->compare ( 'vendor_id', $this->vendor_id );
		$criteria->compare ( 'outlet_id', $this->outlet_id );
		$criteria->compare ( 'status', $this->status );
		$criteria->compare ( 'type_id', $this->type_id );
		$criteria->compare ( 'return_id', $this->return_id );
		//$criteria->compare ( 'create_time', $this->create_time, true );
		$criteria->compare ( 'create_user_id', $this->create_user_id );
		$criteria->compare ( 'updated_by', $this->updated_by );
		
		return new CActiveDataProvider ( $this, array (
				'criteria' => $criteria,
				'pagination' => false 
		) );
	}
	
	
    public function defaultScope()

    {

        return array();

    }
	
}