<?php

/**
 * This is the model base class for the table "{{organization}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Organization".
 *
 * Columns in table "{{organization}}" available as properties of the model,
 * followed by relations of table "{{organization}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $title
 * @property string $link
 * @property string $email
 * @property integer $contact_no
 * @property integer $secondary_contact_no
 * @property string $address
 * @property string $tax
 * @property integer $status
 * @property integer $type_id
 * @property string $create_time
 * @property integer $city_id
 * @property integer $state_id
 * @property integer $country_id
 * @property integer $create_user_id
 * @property integer $updated_by
 *
 * @property Mrn[] $mrns
 * @property Mrs[] $mrs
 * @property City $city
 * @property Country $country
 * @property User $createUser
 * @property State $state
 * @property User $updatedBy
 * @property Outlet[] $outlets
 * @property PurchaseBill[] $purchaseBills
 * @property PurchaseOrder[] $purchaseOrders
 */
abstract class BaseOrganization extends GxActiveRecord {

	const STATUS_ACTIVE = 0;
	const STATUS_INACTIVE = 1;
	public static function getStatusOptions($id = null)
	{
		$list = array("Active","Inactive");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}	
	public static function getTypeOptions($id = null)
	{
		$list = array("TYPE1","TYPE2","TYPE3");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
 	
		
	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
			if ( !isset( $this->create_time )) $this->create_time = new CDbExpression('NOW()');
			if ( !isset( $this->create_user_id )) $this->create_user_id = Yii::app()->user->id;			
	}else{
				}
		return parent::beforeValidate();
	}

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{organization}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Organization|Organizations', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('title, email, contact_no, address, create_time, city_id, state_id, country_id, create_user_id', 'required'),
			array('contact_no, status, type_id, city_id, state_id, country_id, create_user_id, updated_by', 'numerical', 'integerOnly'=>true),
			array('title, link, email', 'length', 'max'=>255),
			array('secondary_contact_no,tax_no', 'safe'),
			array('status, type_id, updated_by', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, title, link, email, contact_no,secondary_contact_no, address,tax_no, status, type_id, create_time, city_id, state_id, country_id, create_user_id, updated_by', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'mrns' => array(self::HAS_MANY, 'Mrn', 'organization_id'),
			'mrs' => array(self::HAS_MANY, 'Mrs', 'organization_id'),
			'city' => array(self::BELONGS_TO, 'City', 'city_id'),
			'country' => array(self::BELONGS_TO, 'Country', 'country_id'),
			'createUser' => array(self::BELONGS_TO, 'User', 'create_user_id'),
			'state' => array(self::BELONGS_TO, 'State', 'state_id'),
			'updatedBy' => array(self::BELONGS_TO, 'User', 'updated_by'),
			'outlets' => array(self::HAS_MANY, 'Outlet', 'organization_id'),
			'purchaseBills' => array(self::HAS_MANY, 'PurchaseBill', 'organization_id'),
			'purchaseOrders' => array(self::HAS_MANY, 'PurchaseOrder', 'organization_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'title' => Yii::t('app', 'Title'),
			'link' => Yii::t('app', 'Link'),
			'email' => Yii::t('app', 'Email'),
			'contact_no' => Yii::t('app', 'Contact No'),
			'secondary_contact_no' => Yii::t('app', 'Secondary Contact No'),
			'address' => Yii::t('app', 'Address'),
			'tax_no' => Yii::t('app', 'Tax No'),
			'status' => Yii::t('app', 'Status'),
			'type_id' => Yii::t('app', 'Type'),
			'create_time' => Yii::t('app', 'Create Time'),
			'city_id' => null,
			'state_id' => null,
			'country_id' => null,
			'create_user_id' => null,
			'updated_by' => null,
			'mrns' => null,
			'mrs' => null,
			'city' => null,
			'country' => null,
			'createUser' => null,
			'state' => null,
			'updatedBy' => null,
			'outlets' => null,
			'purchaseBills' => null,
			'purchaseOrders' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('link', $this->link, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('contact_no', $this->contact_no);
		$criteria->compare('address', $this->address, true);
		$criteria->compare('status', $this->status);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('city_id', $this->city_id);
		$criteria->compare('state_id', $this->state_id);
		$criteria->compare('country_id', $this->country_id);
		$criteria->compare('create_user_id', $this->create_user_id);
		$criteria->compare('updated_by', $this->updated_by);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}