<?php


 
/**
 * This is the model base class for the table "{{mrn_detail}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MrnDetail".
 *
 * Columns in table "{{mrn_detail}}" available as properties of the model,
 * followed by relations of table "{{mrn_detail}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $req_qty
 * @property integer $approved_qty
 * @property integer $bal_qty
 * @property integer $status
 * @property integer $type_id
 * @property string $remarks
 * @property string $create_time
 * @property string $update_time
 * @property integer $create_user_id
 * @property integer $updated_by
 * @property integer $item_detail_id
 * @property integer $mrn_id
 * @property integer $outlet_id
 *
 * @property User $createUser
 * @property ItemDetail $itemDetail
 * @property Mrn $mrn
 * @property Outlet $outlet
 * @property User $updatedBy
 */
abstract class BaseMrnDetail extends GxActiveRecord {
 public $mrs_req_date;
 public $mrp;
 public $vendor_id;
 public $salerate;
 public $vat;
 public $discount;
 public $discount_amt;
 public $other_charge;
 public $amount;
 public $price;
 public $item_val_id;
 public $bar_code;
 const STATUS_PENDING = 0;
 const STATUS_HALF_DONE = 2;
 const STATUS_DONE = 1;
 const STATUS_ASSIGN = 3;
 const STATUS_REJECT = 4;
	public static function getStatusOptions($id = null)
	{
		$list = array("Pending","Half Done","Done","Assigned","Rejected");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}	
	public static function getTypeOptions($id = null)
	{
		$list = array("TYPE1","TYPE2","TYPE3");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
 	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
			if ( !isset( $this->create_time )) $this->create_time = new CDbExpression('NOW()');
				if ( !isset( $this->create_user_id )) $this->create_user_id = Yii::app()->user->id;			
	}else{
					}
		return parent::beforeValidate();
	}

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{mrn_detail}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MrnDetail|MrnDetails', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('req_qty, item_detail_id, mrn_id, outlet_id', 'required'),
			array('status, type_id, create_user_id, updated_by, item_detail_id, mrn_id, outlet_id', 'numerical', 'integerOnly'=>true),
			array('remarks,margin,create_time, update_time,item_id,mrn_req_date,vendor_id,gross_amt,igst_per,igst_amt,total_discount,tax_amount,bill_amount,mrp,sale_rate,tax_id,discount,discount_amt,discount1,discount_amt1,other_charge,amount,price,cgst_per,sgst_per,cess_per,cgst_amt,sgst_amt,cess_amt,item_val_id,bar_code,min_qty', 'safe'),
			array('approved_qty, bal_qty, status, type_id, remarks, create_time, update_time, updated_by', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, req_qty, approved_qty, bal_qty, status, type_id, remarks, create_time, update_time, create_user_id, updated_by, item_detail_id, mrn_id, outlet_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'createUser' => array(self::BELONGS_TO, 'User', 'create_user_id'),
			'itemDetail' => array(self::BELONGS_TO, 'ItemDetail', 'item_detail_id'),
				'tax' => array(self::BELONGS_TO, 'Tax', 'tax_id'),
				'item' => array(self::BELONGS_TO, 'Item', 'item_id'),
			'mrn' => array(self::BELONGS_TO, 'Mrn', 'mrn_id'),
			'outlet' => array(self::BELONGS_TO, 'Outlet', 'outlet_id'),
			'updatedBy' => array(self::BELONGS_TO, 'User', 'updated_by'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'req_qty' => Yii::t('app', 'Max Qty'),
			'approved_qty' => Yii::t('app', 'Approved Qty'),
			'bal_qty' => Yii::t('app', 'Bal Qty'),
			'status' => Yii::t('app', 'Status'),
			'type_id' => Yii::t('app', 'Type'),
			'remarks' => Yii::t('app', 'Remarks'),
			'create_time' => Yii::t('app', 'Create Time'),
			'update_time' => Yii::t('app', 'Update Time'),
				'item_id' => Yii::t('app', 'Item'),
			'create_user_id' => null,
			'updated_by' => null,
			'item_detail_id' =>  Yii::t('app', 'Bar Code'),
			'mrn_id' => null,
			'outlet_id' => null,
			'createUser' => null,
				'itemDetail' => Yii::t('app', 'Bar Code'),
				'vendor_id' => Yii::t('app', 'Vendor'),
			'mrn' => null,
			'outlet' => null,
			'updatedBy' => null,
		);
	}
public function pendingsearch() {
		$criteria = new CDbCriteria;
		
			$mrs_ids = array();
			$criteria1 = new CDbCriteria;
			if($this->mrs_req_date != null){
			$criteria1->compare('mrs_req_date', $this->mrs_req_date);
			}
			$criteria1->compare('status', Mrs::STATUS_HALF_DONE);
			
			$mrss= Mrn::model()->findAll($criteria1);
			Yii::log ( CVarDumper::dumpAsString ( $mrss ), CLogger::LEVEL_WARNING, '$mrss' );
			if($mrss){
				foreach($mrss as $mrs){
					$mrs_ids[] = $mrs->id;
				}
					
			}
			$criteria->addInCondition('mrn_id', $mrs_ids);
			$criteria->addCondition('status !='. Mrs::STATUS_DONE);
			
		$criteria->compare('id', $this->id);
		$criteria->compare('req_qty', $this->req_qty);
		$criteria->compare('status', MrsDetail::STATUS_HALF_DONE);
		//$criteria->compare('mrs_req_date', $this->mrs_req_date);
		$criteria->compare('approved_qty', $this->approved_qty);
		$criteria->compare('bal_qty', $this->bal_qty);
		$criteria->compare('status', $this->status);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('remarks', $this->remarks, true);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('update_time', $this->update_time, true);
		$criteria->compare('create_user_id', $this->create_user_id);
		$criteria->compare('updated_by', $this->updated_by);
		$criteria->compare('item_detail_id', $this->item_detail_id);
		$criteria->compare('item_id', $this->item_id);
		$criteria->compare('mrs_id', $this->mrs_id);
		$criteria->compare('outlet_id', $this->outlet_id);
	
		return new CActiveDataProvider($this, array(
				'criteria' => $criteria,
		));
	}
	public function search() {
		$criteria = new CDbCriteria;
		$criteria->with = 'item';
		$criteria->order = 'item.title asc';
		if($this->mrs_req_date != null || $this->vendor_id != null){
			$mrs_ids = array();
		$criteria1 = new CDbCriteria;
		if($this->mrs_req_date != null){
			$criteria1->compare('mrs_req_date', $this->mrs_req_date);
		}
		if($this->vendor_id != null){
			$criteria1->compare('vendor_id', $this->vendor_id);
		}
		$mrss= Mrn::model()->findAll($criteria1);
		Yii::log ( CVarDumper::dumpAsString ( $mrss ), CLogger::LEVEL_WARNING, '$mrss' );
		if($mrss){
			foreach($mrss as $mrs){
				$mrs_ids[] = $mrs->id;
			}
			
		}
		$criteria->addInCondition('t.mrn_id', $mrs_ids);
		}
		$criteria->addCondition('t.status !='. Mrs::STATUS_DONE);
		$criteria->compare('t.id', $this->id);
		$criteria->compare('t.req_qty', $this->req_qty);
		$criteria->compare('t.approved_qty', $this->approved_qty);
		$criteria->compare('t.bal_qty', $this->bal_qty);
		$criteria->compare('t.status', $this->status);
		$criteria->compare('t.type_id', $this->type_id);
		$criteria->compare('t.remarks', $this->remarks, true);
		$criteria->compare('t.create_time', $this->create_time, true);
		$criteria->compare('t.update_time', $this->update_time, true);
		$criteria->compare('t.create_user_id', $this->create_user_id);
		$criteria->compare('t.updated_by', $this->updated_by);
		$criteria->compare('t.item_detail_id', $this->item_detail_id);
		$criteria->compare('t.mrn_id', $this->mrn_id);
		$criteria->compare('t.outlet_id', $this->outlet_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,'pagination'=>false
		));
	}
	public function defaultScope() {
		return array ();
	}
}