<?php

/**
 * This is the model base class for the table "{{stock_adjust_log}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "StockAdjustLog".
 *
 * Columns in table "{{stock_adjust_log}}" available as properties of the model,
 * followed by relations of table "{{stock_adjust_log}}" available as properties of the model.
 *
 * @property integer $id
 * @property string $date
 * @property integer $item_detail_id
 * @property integer $item_id
 * @property double $mrp
 * @property integer $current_stock
 * @property integer $actual_stock
 * @property integer $adjusted
 * @property integer $outlet_id
 * @property integer $type_id
 * @property integer $status
 * @property string $create_time
 * @property string $update_time
 *
 * @property ItemDetail $itemDetail
 * @property Item $item
 * @property Outlet $outlet
 */
abstract class BaseStockAdjustLog extends GxActiveRecord {
	public $columns;
	public $start_date;
	public $end_date;
	public static function getTypeOptions($id = null) {
		$list = array (
				"TYPE1",
				"TYPE2",
				"TYPE3" 
		);
		if ($id == null)
			return $list;
		if (is_numeric ( $id ))
			return $list [$id];
		return $id;
	}
	public static function getStatusOptions($id = null) {
		$list = array (
				"Draft",
				"Published",
				"Archive" 
		);
		if ($id == null)
			return $list;
		if (is_numeric ( $id ))
			return $list [$id];
		return $id;
	}
	public function beforeValidate() {
		if ($this->isNewRecord) {
			if (! isset ( $this->create_time ))
				$this->create_time = new CDbExpression ( 'NOW()' );
			if ( !isset( $this->create_user_id )) $this->create_user_id = Yii::app()->user->id;	
		} else {
		}
		return parent::beforeValidate ();
	}
	public static function model($className = __CLASS__) {
		return parent::model ( $className );
	}
	public function tableName() {
		return '{{stock_adjust_log}}';
	}
	public static function label($n = 1) {
		return Yii::t ( 'app', 'StockAdjustLog|StockAdjustLogs', $n );
	}
	public static function representingColumn() {
		return 'date';
	}
	public function rules() {
		return array (
				array (
						'date, item_detail_id, item_id, mrp, current_stock, actual_stock, adjusted',
						'required' 
				),
				array (
						'item_detail_id, item_id,outlet_id, type_id, status',
						'numerical',
						'integerOnly' => true 
				),
				array (
						'mrp',
						'numerical' 
				),
				array (
						'create_time, update_time,columns,start_date,end_date,remarks',
						'safe' 
				),
				array (
						'outlet_id, type_id, status, create_time, update_time',
						'default',
						'setOnEmpty' => true,
						'value' => null 
				),
				array (
						'id, date, item_detail_id, item_id, mrp, current_stock, actual_stock, adjusted, outlet_id, type_id, status, create_time, update_time',
						'safe',
						'on' => 'search' 
				) 
		);
	}
	public function relations() {
		return array (
				'itemDetail' => array (
						self::BELONGS_TO,
						'ItemDetail',
						'item_detail_id' 
				),
				'item' => array (
						self::BELONGS_TO,
						'Item',
						'item_id' 
				),
				'outlet' => array (
						self::BELONGS_TO,
						'Outlet',
						'outlet_id' 
				),
				'createUser' => array (
					self::BELONGS_TO,
					'User',
					'create_user_id' 
			),
		);
	}
	public function pivotModels() {
		return array ();
	}
	public function attributeLabels() {
		return array (
				'id' => Yii::t ( 'app', 'ID' ),
				'date' => Yii::t ( 'app', 'Date' ),
				'item_detail_id' => Yii::t ( 'app', 'Bar Code' ),
				'item_id' => null,
				'mrp' => Yii::t ( 'app', 'Mrp' ),
				'current_stock' => Yii::t ( 'app', 'Current Stock' ),
				'actual_stock' => Yii::t ( 'app', 'Actual Stock' ),
				'adjusted' => Yii::t ( 'app', 'Adjusted' ),
				'outlet_id' => null,
				'type_id' => Yii::t ( 'app', 'Type' ),
				'status' => Yii::t ( 'app', 'Status' ),
				'start_date' => Yii::t ( 'app', 'Start Date' ),
				'end_date' => Yii::t ( 'app', 'End Date' ),
				'create_time' => Yii::t ( 'app', 'Create Time' ),
				'update_time' => Yii::t ( 'app', 'Update Time' ),
				'itemDetail' => Yii::t ( 'app', 'Bar Code' ),
				'item' => null,
				'outlet' => null 
		);
	}
	public function search() {
		$criteria = new CDbCriteria ();
		
		$criteria->with = array (
				'itemDetail',
				'item' 
		);
		
		if (($this->start_date != '') && ($this->end_date != '')) {
			$criteria->addBetweenCondition ( 't.date', $this->start_date, $this->end_date );
		}
		if ((Yii::app ()->session ['adjust_start_date'] != '') && (Yii::app ()->session ['adjust_end_date'] != '')) {
			$criteria->addBetweenCondition ( 't.date', Yii::app ()->session ['adjust_start_date'], Yii::app ()->session ['adjust_end_date'] );
		}else{
			$criteria->compare ( 't.date', $this->date, true );
		}
		Yii::log ( CVarDumper::dumpAsString ( Yii::app ()->session ['adjust_start_date'] ), CLogger::LEVEL_WARNING, 'startt_date' );
		Yii::log ( CVarDumper::dumpAsString ( Yii::app ()->session ['adjust_end_date'] ), CLogger::LEVEL_WARNING, 'end_date' );
		
		if ($this->create_user_id != null) {
			$criteria->compare ( 't.create_user_id', $this->create_user_id );
		}
		$criteria->compare ( 'itemDetail.bar_code', $this->item_detail_id, true );
		$criteria->compare ( 'item.title', $this->item_id, true );
		$criteria->compare ( 't.mrp', $this->mrp );
		$criteria->compare ( 't.current_stock', $this->current_stock );
		$criteria->compare ( 't.actual_stock', $this->actual_stock );
		$criteria->compare ( 't.adjusted', $this->adjusted );
		$criteria->compare ( 't.outlet_id', $this->outlet_id );
		
		return new CActiveDataProvider ( $this, array (
				'criteria' => $criteria ,
				'sort'=>array(
						'defaultOrder'=>'t.id DESC',
				),
		) );
	}
	
	public function defaultScope() {
		return array ();
	}
}