<?php


 
/**
 * This is the model base class for the table "{{order_hold}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "OrderHold".
 *
 * Columns in table "{{order_hold}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $bill_no
 * @property string $bill_date
 * @property string $mode_of_payment
 * @property string $mode_of_delivery
 * @property integer $qty
 * @property double $discount_amt
 * @property double $total_amt
 * @property double $paid_amt
 * @property integer $status
 * @property integer $type_id
 * @property integer $city_id
 * @property integer $state_id
 * @property integer $country_id
 * @property string $address
 * @property string $note
 * @property string $create_time
 * @property string $update_time
 * @property integer $customer_id
 * @property integer $updated_by
 *
 */
abstract class BaseOrderHold extends GxActiveRecord {

	
	
	public static function getTypeOptions($id = null)
	{
		$list = array("TYPE1","TYPE2","TYPE3");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
 	
	public static function getStatusOptions($id = null)
	{
		$list = array("Draft","Published","Archive");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}	
	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
			if ( !isset( $this->create_time )) $this->create_time = new CDbExpression('NOW()');
			}else{
				}
		return parent::beforeValidate();
	}

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{order_hold}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'OrderHold|OrderHolds', $n);
	}

	public static function representingColumn() {
		return 'bill_date';
	}

	public function rules() {
		return array(
			array('bill_date, mode_of_payment, mode_of_delivery', 'required'),
			array('bill_no, status, type_id, city_id, state_id, country_id, customer_id, updated_by', 'numerical', 'integerOnly'=>true),
			array('discount_amt, total_amt, paid_amt', 'numerical'),
			array('mode_of_payment, mode_of_delivery', 'length', 'max'=>255),
			array('address, note, create_time, update_time', 'safe'),
			array('qty, discount_amt, total_amt, paid_amt, status, type_id, address, note, create_time, update_time, updated_by', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, bill_no, bill_date, mode_of_payment, mode_of_delivery, qty, discount_amt, total_amt, paid_amt, status, type_id, city_id, state_id, country_id, address, note, create_time, update_time, customer_id, updated_by', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
				'city' => array(self::BELONGS_TO, 'City', 'city_id'),
				'country' => array(self::BELONGS_TO, 'Country', 'country_id'),
				'customer' => array(self::BELONGS_TO, 'Customer', 'customer_id'),
				'state' => array(self::BELONGS_TO, 'State', 'state_id'),
				'updatedBy' => array(self::BELONGS_TO, 'User', 'updated_by'),
				'orderItems' => array(self::HAS_MANY, 'OrderHoldItem', 'order_hold_id'),
				'orderRefunds' => array(self::HAS_MANY, 'OrderRefund', 'order_id'),
				'modePayment'=> array(self::BELONGS_TO, 'PaymentMode', 'mode_of_payment'),
				'modeDelivery'=> array(self::BELONGS_TO, 'PaymentMode', 'mode_of_delivery'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'bill_no' => Yii::t('app', 'Bill No'),
			'bill_date' => Yii::t('app', 'Bill Date'),
			'mode_of_payment' => Yii::t('app', 'Mode Of Payment'),
			'mode_of_delivery' => Yii::t('app', 'Mode Of Delivery'),
			'qty' => Yii::t('app', 'Qty'),
			'discount_amt' => Yii::t('app', 'Discount Amt'),
			'total_amt' => Yii::t('app', 'Total Amt'),
			'paid_amt' => Yii::t('app', 'Paid Amt'),
			'status' => Yii::t('app', 'Status'),
			'type_id' => Yii::t('app', 'Type'),
			'city_id' => Yii::t('app', 'City'),
			'state_id' => Yii::t('app', 'State'),
			'country_id' => Yii::t('app', 'Country'),
			'address' => Yii::t('app', 'Address'),
			'note' => Yii::t('app', 'Note'),
			'create_time' => Yii::t('app', 'Create Time'),
			'update_time' => Yii::t('app', 'Update Time'),
			'customer_id' => Yii::t('app', 'Customer'),
			'updated_by' => Yii::t('app', 'Updated By'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('bill_no', $this->bill_no);
		$criteria->compare('bill_date', $this->bill_date, true);
		$criteria->compare('mode_of_payment', $this->mode_of_payment, true);
		$criteria->compare('mode_of_delivery', $this->mode_of_delivery, true);
		$criteria->compare('qty', $this->qty);
		$criteria->compare('discount_amt', $this->discount_amt);
		$criteria->compare('total_amt', $this->total_amt);
		$criteria->compare('paid_amt', $this->paid_amt);
		$criteria->compare('status', $this->status);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('city_id', $this->city_id);
		$criteria->compare('state_id', $this->state_id);
		$criteria->compare('country_id', $this->country_id);
		$criteria->compare('address', $this->address, true);
		$criteria->compare('note', $this->note, true);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('update_time', $this->update_time, true);
		$criteria->compare('customer_id', $this->customer_id);
		$criteria->compare('updated_by', $this->updated_by);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}