#!/usr/bin/env python3
"""
Ports a list of CRUD controllers and verifies each against Yii 1.

Each one goes through the same three generators and is then compared page by
page. A controller that does not compare clean is reported and left out of
Ui::PORTED, so it stays on Yii 1 rather than shipping a page nobody checked.
"""
import subprocess, sys, os, re, json, glob

ROOT = '/root/pos/pos83'


def run(cmd, **kw):
    return subprocess.run(cmd, shell=True, capture_output=True, text=True, **kw)


def lcfirst(s):
    return s[0].lower() + s[1:]


def grid_id(model):
    """The grid id the Yii 1 admin view uses, which the comparison keys on."""
    for v in ('admin', '_list'):
        p = f'{ROOT}/protected/views/{lcfirst(model)}/{v}.php'
        if os.path.exists(p):
            m = re.search(r"'id'\s*=>\s*'([^']+)'", open(p, encoding='utf-8', errors='replace').read())
            if m:
                return m.group(1)
    return None


def table_of(model):
    p = f'{ROOT}/protected/models/_base/Base{model}.php'
    m = re.search(r"tableName\(\)\s*\{\s*return\s*'\{\{(\w+)\}\}'",
                  open(p, encoding='utf-8', errors='replace').read())
    return m.group(1) if m else None


def a_row_id(table):
    q = (f"docker exec pos-mysql-8 sh -c "
         f"'mysql -uroot -p$MYSQL_ROOT_PASSWORD $MYSQL_DATABASE -N -e "
         f'"SELECT id FROM tbl_{table} ORDER BY id DESC LIMIT 1"\' 2>/dev/null')
    out = run(q).stdout.strip()
    return out if out.isdigit() else None


def set_ported(names):
    p = f'{ROOT}/app2/components/Ui.php'
    s = open(p, encoding='utf-8').read()
    block = '    public const PORTED = [\n' + ''.join(
        "        '%s',\n" % n for n in names) + '    ];'
    s = re.sub(r'    public const PORTED = \[.*?\];', lambda m: block, s, flags=re.S)
    open(p, 'w', encoding='utf-8').write(s)


def current_ported():
    s = open(f'{ROOT}/app2/components/Ui.php', encoding='utf-8').read()
    m = re.search(r'public const PORTED = \[(.*?)\];', s, re.S)
    return re.findall(r"'([^']+)'", m.group(1))


# The docblock port_model.py writes at the top of a model it generated whole.
# A model the API port wrote by hand says something else, and is merged into
# rather than replaced.
GENERATED_MARKER = 'and its giix base class'


VIEW_MARKER = 'Ported from protected/views/'


def view_generated_by_us(path):
    """Whether this view file is this pipeline's own output."""
    with open(path, encoding='utf-8', errors='replace') as fh:
        return VIEW_MARKER in fh.read(500)


def generated_by_us(path):
    """
    Whether this model file is this pipeline's own output.

    It matters because merge() keeps existing methods. A model generated by a
    version of the generator that has since been fixed would otherwise keep the
    old output for ever - which is how a stale `Order::model()` call survived
    three rounds of fixes to the finder rules, including one commit.
    """
    with open(path, encoding='utf-8', errors='replace') as fh:
        return GENERATED_MARKER in fh.read(2000)


def ensure_logged_in():
    """
    Re-establish the session if it has lapsed.

    A batch of thirty controllers runs longer than PHP's default session
    lifetime of 24 minutes, so the later ones were being compared with an
    expired cookie: Yii 1 redirects to the login form, the reduction comes back
    empty, and the controller is reported as DIFFERS. Three controllers that
    had been green for hours "regressed" that way in a single run, which is how
    it was noticed.
    """
    # The status, not a string in the body: Yii 1's error page for a guest
    # contains the grid's id in its source excerpt.
    probe = run('curl -sS -o /dev/null -w "%{http_code}" -b /tmp/uic.txt '
                '--max-time 60 "http://127.0.0.1:8084/paymentMode/admin"')
    if probe.stdout.strip() == '200':
        return
    run('/root/pos/uilogin.sh')


def panel_views(ctrl):
    """
    Other controllers whose partials this one's views render.

    The argument list is not split on commas: the arguments contain commas of
    their own - $model->getRelatedDataProvider('items') - and splitting
    naively picked the wrong one and ported the wrong file. The view name is
    matched positionally on the quoted arguments instead.
    """
    out = set()
    vdir = f'{ROOT}/protected/views/{ctrl}'
    if not os.path.isdir(vdir):
        return out
    for f in os.listdir(vdir):
        if not f.endswith('.php'):
            continue
        src = open(os.path.join(vdir, f), encoding='utf-8', errors='replace').read()
        src = re.sub(r'/\*.*?\*/', '', src, flags=re.S)
        src = re.sub(r'//[^\n]*', '', src)
        for m in re.finditer(r"AddP?\w*Panel\s*\((.*?)\)\s*;", src, re.S):
            quoted = re.findall(r"'([^']*)'", m.group(1))
            for q in quoted:
                if (q and q != ctrl and not q.startswith('_')
                        and os.path.isdir(f'{ROOT}/protected/views/{q}')):
                    out.add(q)
    return out


def dependencies(model, ctrl):
    """Other models named by this one's relations or its views."""
    names = set()
    for p in [f'{ROOT}/protected/models/_base/Base{model}.php']:
        if os.path.exists(p):
            src = open(p, encoding='utf-8', errors='replace').read()
            m = re.search(r'function relations\(\)(.*?)\n\t\}', src, re.S)
            if m:
                names |= set(re.findall(r"self::\w+\s*,\s*'(\w+)'", m.group(1)))
    vdir = f'{ROOT}/protected/views/{ctrl}'
    if os.path.isdir(vdir):
        for f in os.listdir(vdir):
            if f.endswith('.php'):
                src = open(os.path.join(vdir, f), encoding='utf-8', errors='replace').read()
                names |= set(re.findall(r'\b([A-Z]\w+)::model\(\)', src))
                names |= set(re.findall(r'\b([A-Z]\w+)::get\w+', src))
    out = []
    for n in sorted(names):
        if n == model:
            continue
        if os.path.exists(f'{ROOT}/protected/models/_base/Base{n}.php'):
            out.append(n)
    return out


def main():
    # A generator that will not import takes every model down with it, and the
    # symptom - "dependency X produced no output" - points at the model rather
    # than at the tool. Check the tools first.
    for tool in ('port_model.py', 'port_controller.py', 'port_views.py'):
        r = run(f'python3 -c "import py_compile,sys; py_compile.compile(\'/root/pos/{tool}\', doraise=True)"')
        if r.returncode:
            print(f'{tool} does not compile:\n{r.stderr}')
            sys.exit(2)

    models = sys.argv[1:]
    base = current_ported()
    results = []

    for model in models:
        ctrl = lcfirst(model)
        notes = []

        # Models this one's pages display - a relation shown in a grid, a
        # dropdown filled from another table. They need a string form and a
        # label, and nothing more: they are already in use by the API port, so
        # their validation and save behaviour is left exactly as it is.
        for dep in dependencies(model, ctrl):
            r = run(f'cd /root/pos && python3 port_model.py {dep} --presentation-only')
            first = r.stdout.strip().splitlines()
            if r.returncode or not first:
                # A dependency that will not generate is not a footnote: the
                # pages that display it will fail, so say which one and why.
                notes.append('dependency %s FAILED: %s'
                             % (dep, (r.stderr or r.stdout).strip().splitlines()[-1:] or ['no output']))
            elif 'nothing to add' not in first[0]:
                notes.append('dependency %s: %s' % (dep, first[0]))

        # A model file this pipeline generated earlier is replaced, not merged
        # into. Merging keeps existing methods, so a model generated by a
        # version of the generator that has since been fixed would keep the old
        # output for ever - which is how `Order::model()` survived three
        # rounds of fixes to the finder rules.
        #
        # git is the test: tracked means committed or hand-written, and that is
        # merged into and never overwritten.
        model_path = f'{ROOT}/app2/models/{model}.php'
        if os.path.exists(model_path) and generated_by_us(model_path):
            os.remove(model_path)
            notes.append('regenerated the model from scratch')

        for script in ('port_model.py', 'port_controller.py'):
            r = run(f'cd /root/pos && python3 {script} {model}')
            notes += [l.strip() for l in r.stdout.splitlines() if 'NOTE' in l]
            if r.returncode:
                results.append((model, 'GENERATOR FAILED', (r.stderr or r.stdout)[-300:]))
                break
        else:
            # Remove only views this pipeline generated. A hand-ported view
            # can already live in that directory - app2/views/item/_pdf.php is
            # the invoice template the punchorder API renders - and blowing the
            # directory away replaced it with a mechanical translation that
            # broke a suite which had been green for weeks.
            # Provenance, not git status. A partial this pipeline generated for
            # another controller's relation panel gets committed with that
            # controller, and "tracked" would then freeze it at whatever the
            # transformer produced that day - which is how a CController call
            # survived a later fix and a commit. A view written by hand, like
            # app2/views/item/_pdf.php, carries no such header and is left
            # alone.
            if os.path.isdir(f'{ROOT}/app2/views/{ctrl}'):
                for f in os.listdir(f'{ROOT}/app2/views/{ctrl}'):
                    path = f'{ROOT}/app2/views/{ctrl}/{f}'
                    if view_generated_by_us(path):
                        os.remove(path)
            r = run(f'cd /root/pos && python3 port_views.py {ctrl} --keep-existing')
            notes += [l.strip() for l in r.stdout.splitlines() if 'UNCONVERTED' in l]

            # A view page's tabs render another controller's _list partial -
            # AddPanel($model->getRelatedDataProvider('items'), ..., 'item').
            # That file has to exist in the Yii 2 tree even though the item
            # controller itself is still served by Yii 1.
            for other in panel_views(ctrl):
                vdir = f'{ROOT}/protected/views/{other}'
                if not os.path.isdir(vdir):
                    continue
                for f in sorted(os.listdir(vdir)):
                    # Only the partials. A panel renders _list or _view from
                    # the other controller's directory; its full pages belong
                    # to that controller's own port.
                    if not f.startswith('_') or not f.endswith('.php'):
                        continue
                    dst = f'{ROOT}/app2/views/{other}/{f}'
                    if os.path.exists(dst):
                        if not view_generated_by_us(dst):
                            continue        # hand-written; leave it
                        os.remove(dst)
                    run(f'cd /root/pos && python3 port_views.py {other} --only {f}')
                    notes.append('also ported %s/%s for a relation panel' % (other, f))

            # syntax first - a parse error is not a comparison failure
            # The view directory has to exist and have files in it. An earlier
            # version globbed it in the shell, so a directory the generator had
            # failed to write came back as "PARSE ERROR *.php" - pointing at
            # syntax when the real story was that port_views.py had crashed.
            view_dir = f'{ROOT}/app2/views/{ctrl}'
            views = sorted(glob.glob(view_dir + '/*.php'))
            if not views:
                results.append((model, 'NO VIEWS',
                                'port_views.py wrote nothing to app2/views/%s' % ctrl))
                continue

            files = [f'{ROOT}/app2/models/{model}.php',
                     f'{ROOT}/app2/controllers/{model}Controller.php'] + views
            bad = []
            for f in files:
                rel = f[len(ROOT) + 1:]
                if run(f'docker exec pos-php-83 php -l "/var/www/html/{rel}" >/dev/null 2>&1').returncode:
                    bad.append(rel)
            if bad:
                results.append((model, 'PARSE ERROR', ', '.join(bad)))
                continue

            gid = grid_id(model)
            table = table_of(model)
            rid = a_row_id(table) if table else None
            if not gid:
                results.append((model, 'NO GRID ID', 'could not find the admin grid id'))
                continue

            set_ported(base + [ctrl])
            ensure_logged_in()
            cmp = run(f'cd {ROOT} && COOKIE_FILE=/tmp/uic.txt python3 tests/port/ui-difftest.py '
                      f'{ctrl} {model} {gid} {rid or ""}')
            if cmp.returncode == 0:
                base.append(ctrl)
                results.append((model, 'MATCHES', notes))
            else:
                set_ported(base)      # leave it on Yii 1
                fails = [l.strip() for l in cmp.stdout.splitlines()
                         if l.strip().startswith('FAIL') or l.strip().startswith('first')
                         or l.strip().startswith('yii1:') or l.strip().startswith('yii2:')
                         or l.strip().startswith('only in') or l.strip().startswith('row count')]
                results.append((model, 'DIFFERS', fails[:10]))

    set_ported(base)
    print('\n================ batch result ================')
    ok = [r for r in results if r[1] == 'MATCHES']
    print('ported and matching: %d of %d' % (len(ok), len(models)))
    for model, status, detail in results:
        print('\n%-22s %s' % (model, status))
        if isinstance(detail, list):
            for d in detail:
                print('    ' + d[:160])
        elif detail:
            print('    ' + str(detail)[:300])
    print('\nUi::PORTED is now: ' + ', '.join(base))


main()
